### PR TITLE
Update ember-cli-sri minimum version to 1.2.0.

### LINKED ISSUE #5110: reloading tests fails on chrome when using ember test --server
I have a repo demonstrating the failure, including steps to reproduce, and workaround/fix: https://github.com/kenglxn/ember-cli-reload-bug

Basically when making changes to a test, or adding a new test, tests blow up in chrome due to integrity check with the following message:

`Uncaught Error: Assertion Failed: The tests file was not loaded. Make sure your tests index.html includes "assets/tests.js"`

browser

console

### PR DESCRIPTION
**Pull request by rwjblue**
Fixes issues with rebuilds during tests getting invalid integrity values.

Fixes #5110.

### CODE REVIEW

**Comment by rwjblue** [comment]
@twokul - This needs to be pulled into stable-1-13 and included in 1.13.13 (AFAIK this is the last remaining item).

**Comment by twokul** [comment]
@rwjblue weird Travis failures with node modules installation. also PR is updated.

**Comment by rwjblue** [comment]
Restarted Node 5 build.

**Comment by rwjblue** [comment]
Node 5 failure is related to https://github.com/ember-cli/ember-cli/issues/5126.

**Comment by rwjblue** [comment]
Merging anyways, fixes large issues and Node 5.1/npm 3.3.12 issues are very likely unrelated.

**Pull request merged**
