### PR TITLE
Fix generate command when both usePods option and --pod argument is used

### PR DESCRIPTION
**Pull request by emrekutlu**
Resolves https://github.com/ember-cli/ember-cli/issues/7163

### CODE REVIEW

**Comment by rwjblue** [comment]
I agree that this is confusing, but the intent here was fhT --pod flag negates the value of usePods. So if you had usePods as true you would use --pod to get non-pods.

**Comment by emrekutlu** [comment]
Hmm, so what does <code>--classic</code> do?

**Comment by rwjblue** [comment]
@Turbo87 - This patch has nothing to do with using both `--pod` and `--classic` at the same time, what am I missing?

**Comment by hjdivad** [comment]
> @Turbo87 - This patch has nothing to do with using both --pod and --classic at the same time, what am I missing?

I think the point is that the existence of `--classic` implies the semantics of `--pod` is `--use-pods` and not `--toggle-pods` and not (only) that they're confusing when used together

**Comment by rwjblue** [comment]
I totally agree with you there, but this change would be a breaking change for anyone leveraging the existing behavior. 

I'd be totally fine with adding a deprecation / warning for anyone that has both `usePods` and specifies either `--pods` or `--classic` specified, but not with arbitrarily changing the meaning of the flags (at least not within the same release, but it could be feathered out)...

**Comment by Turbo87** [comment]
@emrekutlu can you prepare a PR that prints a warning to the console when `--pod` is used in combination with `usePods`?

**Comment by rwjblue** [comment]
@emrekutlu - Ping?

**Comment by emrekutlu** [comment]
@rwjblue sorry for the wait, I am going to update the pull request this week hopefully. Thanks for pinging.

**Comment by emrekutlu** [comment]
@rwjblue I updated the pull request.

**Comment by rwjblue** [comment]
Thank you!

**Pull request merged**
