### PR TITLE
Remove obsolete `BROCCOLI_2` and `SYSTEM_TEMP` experiments

### PR DESCRIPTION
**Pull request by Turbo87**
These experiments have been around for a while and were enabled by default 3 minor releases ago. Since things appear to be working well, I guess it's time to remove those experiments now.

This also has the nice side-effect of making our CI faster again :)

/cc @oligriffiths

### CODE REVIEW

**Comment by oligriffiths** [comment]
Works for me. The fallback will still works and output an error so I think we’re covered.

**Comment by Turbo87** [comment]
yep, it's not changing any behavior, just removing the env vars for completely opting out of Broccoli 2 and the system temp folder

**Comment by oligriffiths** [comment]
Dope. Ship it!

**Comment by Turbo87** [comment]
closing in favor of https://github.com/ember-cli/ember-cli/pull/8470

**Pull request closed without merging**
