### PR TITLE
adding fix to use NULL nodeModuleList to optimize when dealing with non-addons

### PR DESCRIPTION
**Pull request by dcombslinkedin**
courtesy of spenner, with some adjustments of my own.

### CODE REVIEW

**Comment by dcombslinkedin** [comment]
Fails in AppVeyor have nothing to do with the package-info-cache code. They're things like missing directories or files in other tests.

**Comment by stefanpenner** [comment]
This lgtm. But I am just about to head on vacation so I’ll leave this to @rwjblue

**Comment by dcombslinkedin** [comment]
Thanks, @stefanpenner. Have a good vacation!

**Comment by rwjblue** [comment]
Updated to target `beta` and rebased.

**Comment by dcombslinkedin** [comment]
Thanks, @rwjblue !

**Comment by dcombslinkedin** [comment]
This is once again the same set of errors that have been showing up in many builds lately. None of the errors has anything to do with the changes to the code being checked in. @rwjblue, could you do the merge since it passes Travis?

**Pull request merged**
