### PR TITLE
WIP: bump broccoli-caching-writer to 1.1.0

### PR DESCRIPTION
**Pull request by kellyselden**

### CODE REVIEW

**Comment by kellyselden** [comment]
re #4623

**Comment by stefanpenner** [comment]
doesn't the consumer need to call extend and stuff? Or did i misread the usage

**Comment by kellyselden** [comment]
My bad. Programming after midnight is not good for me. I will pick this back up in the morning.

**Comment by kellyselden** [comment]
Hmm. The tests all passed. Is that unexpected?

**Pull request merged**
