### PR TITLE
store add-on initialization/lookup times

### PR DESCRIPTION
**Pull request by stefanpenner**
This will enable further logging/instrumenting/warnings

### CODE REVIEW

**Comment by Turbo87** [comment]
@stefanpenner can you fix the ESLint issues?

**Comment by nathanhammond** [comment]
Kicked CI. One of them is a known CI bug.

**Comment by nathanhammond** [comment]
@homu r+

**Comment by nathanhammond** [comment]
@homu retry

**Comment by nathanhammond** [comment]
@homu retry

**Pull request merged**
