### PR TITLE
Support custom ENVs

### PR DESCRIPTION
**Pull request by dschmidt**
Hey,

so I started trying to implement the proposal from https://gist.github.com/rwjblue/51f1df4b21a23466ae47
To make sure I understood it right and to show up my problems I'm submitting this in a really early hacky stage.

Instead of adding methods to the EmberApp object I created a config model that is passed to the respective configuration module.

See the corresponding config files here: https://github.com/dschmidt/ember-cli-sass-demo/tree/customenvs/config

Going to add my questions as comments to the code below

Best regards,
Dominik

### CODE REVIEW

**Comment by stefanpenner** [comment]
we still intend to solve this, but master has diverged pretty far. I am going to close this, but we will sort this out.

**Comment by raido** [comment]
What's the status of this?

**Comment by Kuzirashi** [comment]
Status?

**Comment by trcarden** [comment]
@stefanpenner is there any update on this feature? We are trying to put our app up but we need staging environment support

**Comment by stefanpenner** [comment]
Please use the existing 3 env. And configure those further with environment variables

**Comment by trcarden** [comment]
Ah, thats pretty obvious in retrospect. For others that come across this i found a decent SO post here to help: http://stackoverflow.com/questions/26403334/how-to-pass-api-keys-in-environment-variables-to-ember-cli-using-process-env

**Comment by Senthe** [comment]
Two years later - is support for staging never going to be done? Documentation implies otherwise.

Honestly I just encountered this issue today and can't understand why isn't it added? Am I really supposed to pass variables from bash if I need them for staging, like the @trcarden post above suggests? I'm really lost.

**Comment by nathanhammond** [comment]
@zackthehuman can you paste in the snippet that you wrote?

**Comment by zackthehuman** [comment]
@nathanhammond I think this is what you're referring to.

I sometimes build my addon's dummy app in order to use it like a demo/api documentation. For certain reasons I am unable to use the production build, so I want to use the development build, but I need to override some settings when I'm building the "apidoc" mode.

```
// environment.js

if(process.argv.indexOf('--apidoc') !== -1) {
    console.log('This is an apidoc build so the environment settings will be adjusted.');
    ENV.locationType = 'hash';

    // We want to force the country code to be "us".
    ENV.i18n.requestIpCountryCode = 'us';
}
```

**Comment by meliborn** [comment]
Is there a better way how to add staging environment like production and development. I need to set API_HOST for my app, but I can't wait another 2 year for support this feature.

**Comment by nathanhammond** [comment]
@meliborn [See the comment above yours.](https://github.com/ember-cli/ember-cli/pull/1520#issuecomment-263004360) That represents a semi-official recommendation for how to toggle different information on a per-build basis. You'd use that code and something like:

`ember build -prod --api-host=asdfasdfasdf`

**Comment by meliborn** [comment]
@nathanhammond wrong link?

**Comment by wayne-o** [comment]
I use dot env - works a treat

**Comment by meliborn** [comment]
@wayne-o could you throw me an example please? Can't imagine how to use it without if-env block

**Comment by nathanhammond** [comment]
@meliborn [Corrected link](https://github.com/ember-cli/ember-cli/pull/1520#issuecomment-261023565). Literally the comment above yours provides a workaround you can use, and my comment demonstrates how you could use it.

**Comment by nathanhammond** [comment]
> but I can't wait another 2 year for support this feature

**Comment by nathanhammond** [comment]
Also, @meliborn 
> but I can't wait another 2 year for support this feature

This type of communication is not constructive in an open source community. This implies a demand. Our work on Ember is a labor of love. Very few of us are paid to work directly on Ember projects, and if we are those efforts are strongly directed by those who are paying. We're real human beings with hobbies and pastimes and friends and things we do other than this. We strive to be friendly and helpful in spite of this, but I wanted to provide a bit of feedback so you understand that it's frustrating and hurtful to read comments like that. We'd _love_ infinite time to address all things. I assure you. But we must prioritize.

**Pull request closed without merging**
