### PR TITLE
Bump portfinder to v1.0.4

### PR DESCRIPTION
**Pull request by eriktrom**
Adds support for/fixes issues outlined in https://github.com/indexzero/node-portfinder/pull/33

### CODE REVIEW

**Comment by eriktrom** [comment]
Don't merge until portfinder v1.0.4 is released to npm, I'll drop a note when that happens

**Comment by stefanpenner** [comment]
@eriktrom thank you sir!

**Comment by eriktrom** [comment]
portfinder v1.0.4 has been released to npm, i triggered travis to re-run the tests

ready to merge at will when tests are green

**Comment by stefanpenner** [comment]
@homu r+

**Pull request merged**
