### PR TITLE
Implement official new Ember CLI logo

### LINKED ISSUE #4850: Need help getting the homepage logo updated
Hey all!

We've finally got official logos for the CLI and Data projects (woot!) and I'd love for someone to help get the EmberCLI one live on the CLI homepage. 

These are large transparent PNG versions appropriate for dark and light backgrounds, respectively. I have vector art too, if needed.

ember cli on dark
ember cli on light

Looking for someone to make the changes, paste screenshots here or on the PR, so I can review and then merge :) Pretty please?

### PR DESCRIPTION
**Pull request by josemarluedke**
Fix #4850.

screen shot 2015-09-14 at 6 51 38 pm
screen shot 2015-09-14 at 6 51 55 pm

### CODE REVIEW

**Comment by stefanpenner** [comment]
@josemarluedke awesome, mind showing one with mobile resolution?

**Comment by stefanpenner** [comment]
cc @wiffelete

**Comment by josemarluedke** [comment]
@stefanpenner Sure!

screen shot 2015-09-14 at 7 42 27 pm

I have chosen to not change the header when scrolled because it didn't look good with the logo, so I left it as it is today.

screen shot 2015-09-14 at 7 42 45 pm

**Comment by stefanpenner** [comment]
@josemarluedke looks extremely good!

Waiting on @wifelette +1, when she is happy we :shipit:

**Comment by wifelette** [comment]
+1 indeed!

It might stand out a tiny bit better if we lightened the very top of the gradient header a bit. Nitpick though, I'm good to ship like this or to play with it a bit :)

@josemarluedke Thanks so much for jumping on this!

**Comment by stefanpenner** [comment]
:ship: but we can still :video_game:

**Pull request merged**
