### PR TITLE
Added ember-cli-release to app/addon devDeps blueprint for simple release cutting

### PR DESCRIPTION
**Pull request by jayphelps**
https://github.com/lytics/ember-cli-release

```bash
$ ember release
$ ember release --minor
$ ember release --major
```

### CODE REVIEW

**Comment by stefanpenner** [comment]
nice!

does this make sense for apps or just addons?

**Comment by jayphelps** [comment]
@stefanpenner I'm going to be pushing to use it for our apps here at NF. We're moving to ember-cli-deploy as well, so seems natural to me.

That said, many people probably don't version their apps but since it's dev-only and noop if not used, I don't see any harm.

**Comment by jayphelps** [comment]
IMO many people don't version their apps simply because it's not easy enough vs. the benefit for them. This addon makes it so simple that it may reduce that barrier for people and let them start versioning without all the work and worries.

**Comment by stefanpenner** [comment]
> @stefanpenner I'm going to be pushing to use it for our apps here at NF. We're moving to ember-cli-deploy as well, so seems natural to me.
> 
> That said, many people probably don't version their apps but since it's dev-only and noop if not used, I don't see any harm.

sounds reasonable.

Lets give @slindberg some time to respond, just want to get his take.

**Comment by slindberg** [comment]
SGTM :+1: 

We're currently using it to great effect with our app; it's made versioning with continuous deployment a breeze. The addon release story is a bit less fleshed out (see the unchecked bullets [here](https://github.com/lytics/ember-cli-release#workflow)), so I'd love to get more exposure to the needs of different release models.

**Comment by stefanpenner** [comment]
> SGTM 
> 
> We're currently using it to great effect with our app; it's made versioning with continuous deployment a breeze. The addon release story is a bit less fleshed out (see the unchecked bullets here), so I'd love to get more exposure to the needs of different release models.

awesome!

**Comment by jayphelps** [comment]
:+1: / :-1:

**Comment by stefanpenner** [comment]
thanks for the ping

**Comment by stefanpenner** [comment]
@jayphelps if you thoughts on how this should be made visible on the website, feel free to share :)

**Pull request merged**
