### PR TITLE
Delete reexport-template.js

### PR DESCRIPTION
**Pull request by Turbo87**
As suggested in the #dev-ember-cli channel on Slack this file is unused and should be deleted

### CODE REVIEW

**Comment by rwjblue** [comment]
:+1:

**Comment by rwjblue** [comment]
closing as this is included in https://github.com/ember-cli/ember-cli/pull/5455

**Comment by rwjblue** [comment]
(also, sorry for asking for the PR then closing it :crying_cat_face: )

**Comment by Turbo87** [comment]
no worries, I'm fast with git ;)

**Pull request closed without merging**
