### PR TITLE
Use GitHub Actions for CI

### PR DESCRIPTION
**Pull request by Turbo87**
because it's usually much faster and supports Windows too

### CODE REVIEW

**Comment by kellyselden** [comment]
Is there a chance we'll run out of free minutes on the OSS plan?

**Comment by Turbo87** [comment]
@kellyselden AFAIK they changed the policy and there is no limit anymore for public projects

**Comment by kellyselden** [comment]
Looks successful. Do they allow stages for our linting and unit check?

**Comment by Turbo87** [comment]
> Do they allow stages for our linting and unit check?

sort of. it's modeled as a graph, so for example later stage jobs care declare what previous jobs need to have run first using `needs`.

**Comment by rwjblue** [comment]
@Turbo87 - What is still pending here?

**Comment by Turbo87** [comment]
@rwjblue nothing... 😅 

Windows tests are not working yet for various reasons, but we can tackle that in a dedicated PR

**Comment by rwjblue** [comment]
This just adds GH actions, we can reevaluate usage of Travis and AppVeyor as we gain confidence here.

**Pull request merged**
