### PR TITLE
extract more util to decouple blueprints

### PR DESCRIPTION
**Pull request by stefanpenner**

### CODE REVIEW

**Comment by stefanpenner** [comment]
@homu r+

**Comment by stefanpenner** [comment]
@homu r+

**Comment by Turbo87** [comment]
@stefanpenner I've rebased this PR and removed the unused dependencies from `package.json`

**Comment by stefanpenner** [comment]
@Turbo87 rad, also I have added you as a homu reviewer

**Comment by Turbo87** [comment]
cool, thanks

**Comment by Turbo87** [comment]
@homu r+

**Pull request merged**
