### PR TITLE
cherry pick commit to put package-info-cache msgs behind DEBUG flag (…

### PR DESCRIPTION
**Pull request by dcombslinkedin**
…3ea02c9b73)

(from Dave Combs, not Stefan Penner, on 10/27/18)

### CODE REVIEW

**Comment by stefanpenner** [comment]
restarting node 6 failure.

**Comment by stefanpenner** [comment]
@rwjblue node failure seems to be strange, any ideaS? Also should we backport this, if the fix is already in 3.5?

**Comment by stefanpenner** [comment]
As 3.5 is already available, and this is not a show stopper, I think we don't need to back port this.

Thanks for the backport, but I this one I think we will have to pass on.

**Comment by dcombslinkedin** [comment]
Thanks, @stefanpenner -- I appreciate the help from both you and @rwjblue on this, and agree with the result.

**Pull request closed without merging**
