### PR TITLE
start using filesToRemove

### PR DESCRIPTION
**Pull request by kellyselden**
A good starting point with `Brocfile.js` and `testem.json` cleanup.

### CODE REVIEW

**Comment by rwjblue** [comment]
👍

**Comment by rwjblue** [comment]
We should also revert https://github.com/ember-cli/ember-cli/pull/6731 and add `bower.json` to the array (on master only)

**Comment by kellyselden** [comment]
> We should also revert #6731 and add bower.json to the array (on master only)

@rwjblue That one was a little more in flux, and didn't want to involve it with this uncontroversial PR.

**Comment by rwjblue** [comment]
haha, yes, I was talking generally (not for this PR)

**Comment by rwjblue** [comment]
@homu r+

**Pull request merged**
