### PR TITLE
Update Ember to 1.9.0.

### PR DESCRIPTION
**Pull request by rwjblue**

### CODE REVIEW

**Comment by pixelhandler** [comment]
So I tried updating an addon to Ember 1.9.1 but get the error:

```
> ember serve
version: 0.1.5
Missing template processor
Error: Missing template processor
    at module.exports.preprocessTemplates (/Users/billheat/code/pixelhandler/ember-off-canvas-components/node_modules/ember-cli/lib/preprocessors.js:83:11)
    at Class.Addon.compileTemplates (/Users/billheat/code/pixelhandler/ember-off-canvas-components/node_modules/ember-cli/lib/models/addon.js:241:12)
    at Class.Addon.compileAddon (/Users/billheat/code/pixelhandler/ember-off-canvas-components/node_modules/ember-cli/lib/models/addon.js:255:28)
    at Class.Addon.treeForAddon (/Users/billheat/code/pixelhandler/ember-off-canvas-components/node_modules/ember-cli/lib/models/addon.js:187:24)
    at Class._treeFor (/Users/billheat/code/pixelhandler/ember-off-canvas-components/node_modules/ember-cli/lib/models/addon.js:132:31)
    at Class.treeFor (/Users/billheat/code/pixelhandler/ember-off-canvas-components/node_modules/ember-cli/lib/models/addon.js:111:19)
    at EmberAddon.<anonymous> (/Users/billheat/code/pixelhandler/ember-off-canvas-components/node_modules/ember-cli/lib/broccoli/ember-app.js:264:20)
    at Array.map (native)
    at EmberAddon.EmberApp.addonTreesFor (/Users/billheat/code/pixelhandler/ember-off-canvas-components/node_modules/ember-cli/lib/broccoli/ember-app.js:262:30)
    at EmberAddon.EmberApp._processedVendorTree (/Users/billheat/code/pixelhandler/ember-off-canvas-components/node_modules/ember-cli/lib/broccoli/ember-app.js:514:38)
```

I tried an update to the ember-off-canvas-components repo to ember-cli v0.1.5 and updating to ember 1.9.1 as well.  I uninstalled the old template processor and installed the new one as suggested in the blog post for Ember 1.9 release here http://emberjs.com/blog/2014/12/08/ember-1-9-0-released.html 

Uninstalled "broccoli-ember-hbs-template-compiler": "^1.6.1",
Installed "ember-cli-htmlbars": "^0.6.0",

But `ember build` still results in an error “Error: Missing template processor”. The sad part is that the only template used in this repo is “{{yield}}”.  I pushed those changes to master at git@github.com:pixelhandler/ember-off-canvas-components.git I may not be able to update the ember cli addon to use ember 1.9.1 with this open issue.

**Comment by stefanpenner** [comment]
ya we should dig into this this weekend. It is related to correcting our add-on story. I suppose it depends how deep we want to go this time around.

**Comment by kielni** [comment]
@pixelhandler it's not a long-term or general fix, but if you need this to work now (like I do), you could use my fork where I changed the template preprocessor to ember-cli-htmlbars:

https://github.com/kielni/ember-cli/tree/ember-cli-htmlbars-preprocessor

**Comment by jayphelps** [comment]
Did something change w/ ember-cli-htmlbars `v0.6.0`? I just upgraded an app to ember `v1.10.0-beta.3` w/ ember-cli `v0.1.5` and it works flawlessly.

**Comment by rwjblue** [comment]
@jayphelps - It does work, but not for addons with templates (which is kind of a big deal).  The issue was explained best by @teddyzeeny in https://github.com/rondale-sc/ember-cli-htmlbars/issues/34.

**Comment by Gaurav0** [comment]
Any update on this issue?

**Comment by blesh** [comment]
Is there any way I can contribute on this? Are there any public discussions around what the problem is and what the fix should be so I can get a handle on what needs to be done?

**Comment by jayphelps** [comment]
@blesh See https://github.com/ember-cli/ember-cli/pull/3166

**Comment by stefanpenner** [comment]
> Is there any way I can contribute on this? Are there any public discussions around what the problem is and what the fix should be so I can get a handle on what needs to be done?

its just the way we config add ons. Also, please remember it is only the bundled version of ember-cli that can't be setup correctly. In your own apps everything will work fine, hence the somewhat low priority fix.

**Comment by blesh** [comment]
> Also, please remember it is only the bundled version of ember-cli that can't be setup correctly.

I'm confused about what a "bundled" version of ember-cli is, versus a "non-bundled" version.

**Comment by corsen2000** [comment]
I'm also having issues and am a little confused.  Is the gist of this that users developing addons can not upgrade at this time?

I am developing an addon and tried following the steps here:  
http://emberjs.com/blog/2014/10/16/handlebars-update.html#toc_ember-cli-steps

**Comment by lukemelia** [comment]
Currently, addons cannot use preprocessors that are not among the default
set registered by default by ember-cli. Unfortunately, the won't-work set
includes ember-cli-htmlbars and ember-cli-6to5. As linked above, I hope to
have a fix ready to merge in the next few days.

**Comment by corsen2000** [comment]
@lukemelia thanks for the clarification.

**Comment by stefanpenner** [comment]
we are on `1.10.x` now

**Comment by brandonjmckay** [comment]
A bit confused here, I have an addon I'm making that uses a template. Does this mean that currently no matter where I put it in the addon, it won't show up?

Been trying to place it all over trying to figure out what the right convention is for it to live.

**Pull request closed without merging**
