### PR TITLE
BUGFIX fixes vars-on-top error in ESLint

### PR DESCRIPTION
**Pull request by jonathanKingston**
Fixes an error reported by ESLint

### CODE REVIEW

**Comment by stefanpenner** [comment]
doesn't eslint have a setting that disables this?

**Comment by jonathanKingston** [comment]
Well you can turn it off globally however, I like the rule as it prevents obscurities like this:
```
f();
var me;
```

```
function f() {
  me = 12;
}
```

## Turning the rule off locally
```
/*eslint vars-on-top:0 */
```

However this then allows for the following code:
```
/*eslint vars-on-top:0 */

Ember.MODEL_FACTORY_INJECTIONS = true;

var App = Ember.Application.extend({
  modulePrefix: config.modulePrefix,
  podModulePrefix: config.podModulePrefix,
  Resolver: Resolver
});

loadInitializers(App, config.modulePrefix);

var somethingElse = window;
(function () {
 somethingElseBad.write('Hello world!');
}())
var somethingElseBad = document;

export default App;
```

This is why I have requested a more specific concessions file: https://github.com/eslint/eslint/issues/2203#issuecomment-89555519

This could be something that gets put into ember-cli-eslint as a default.

[vars-on-top documentation](http://eslint.org/docs/rules/vars-on-top.html)

**Comment by rwjblue** [comment]
This still annoys me (only slightly), but it seems harmless and if it makes folks using eslint happier I suppose it is fine.

**Comment by jonathanKingston** [comment]
:+1:  sorry for the annoyance and thanks.

**Comment by rwjblue** [comment]
To be clear: it wasn't you that was annoying.

**Comment by Globegitter** [comment]
Even though it is not relevant for this case anymore, @jonathanKingston there is also an option to turn off `eslint-rules` just for a single line via `//eslint-disable-line <ruleName>`, e.g. `//eslint-disable-line no-unused-expressions`

**Comment by jonathanKingston** [comment]
@Globegitter wow I had not seen that no.
I really don't like comment blocks like this as it leads to lots of meta data in comments and bad practice.
Especially as JSHint is the defacto here it would be pretty bad form to do that.

Also I think it is lost here:
````
var App = Ember.Application.extend({
  modulePrefix: config.modulePrefix,
  podModulePrefix: config.podModulePrefix,
  Resolver: Resolver
}); //eslint-disable-line vars-on-top
```

I'll start work on my global concessions for ESLint and see if anyone is interested as managing comments becomes very difficult quickly I think.

Any thoughts on this matter @rwjblue as it likely will raise it's ugly head again?

**Pull request merged**
