### PR TITLE
Declares node.js version as documented by Travis

### PR DESCRIPTION
**Pull request by xcambar**
As per http://docs.travis-ci.com/user/languages/javascript-with-nodejs/#Choosing-Node-versions-to-test-against

### CODE REVIEW

**Comment by xcambar** [comment]
From appveyor: 

```
PhantomJS not installed. An error occurred during installation:
 The remote server returned an error: (500) Internal Server Error.
```

**Comment by stefanpenner** [comment]
Travis ci for OS X does not support this. If we wish to restore that we would need to once again change this

**Comment by xcambar** [comment]
What are the odds/conditions for it to be restored? Did the Travis team say something about it?

**Comment by stefanpenner** [comment]
> What are the odds/conditions for it to be restored

Hopefully high, we disabled it because our tests where so slow. @kellyselden has been doing a great job improving them.

Im fine with merging this, and we can restore once we restore OSX ci. maybe by then travis will support the full travis.yml/lang: for OSX as well.

**Comment by stefanpenner** [comment]
@homu r+

**Pull request merged**
