### PR TITLE
[INTERNAL release] Tests: runCommand -> ember, speed up CI

### PR DESCRIPTION
**Pull request by kellyselden**
I'm gradually eliminating most uses of runCommand to speed up CI

### CODE REVIEW

**Comment by stefanpenner** [comment]
<3

**Comment by kellyselden** [comment]
Is this the correct title? @stefanpenner

**Comment by stefanpenner** [comment]
> Is this the correct title? @stefanpenner

yes

**Comment by kellyselden** [comment]
backported to stable in #4690

**Pull request merged**
