### PR TITLE
Fixed tests on Travis OS X

### PR DESCRIPTION
**Pull request by johanneswuerbach**
Travis installed an outdated nvm version (0.17.2)

### CODE REVIEW

**Comment by stefanpenner** [comment]
@johanneswuerbach oh nice! This was going to be my task this morning, thanks for saving me the time.

**Comment by johanneswuerbach** [comment]
Sure, I just saw it when looking through some build logs and remembered that I had the same issue previously.

**Comment by johanneswuerbach** [comment]
Looks like PhantomJS was also missing, added. Btw. should watchman also be installed?

**Comment by stefanpenner** [comment]
> Btw. should watchman also be installed?

nah, not for CI.

**Comment by johanneswuerbach** [comment]
0.10 & 0.12 are passing now on osx, iojs is running into a timeout...

**Comment by stefanpenner** [comment]
@johanneswuerbach this is already quite a bit better. I am going to merge, we can follow up with the IOJS fix next.

**Comment by johanneswuerbach** [comment]
Looks like this was accidentally closed? Should I recreate?

**Comment by stefanpenner** [comment]
not sure what happened there :P

**Pull request merged**
