### PR TITLE
context issue fix

### PR DESCRIPTION
**Pull request by bekzod**

### CODE REVIEW

**Comment by stefanpenner** [comment]
@bekzod mind adding a test to ensure this doesn't regress

**Comment by bekzod** [comment]
@stefanpenner ok, but it won't be quick :)

**Comment by stefanpenner** [comment]
@bekzod no worries. Although I suspect you can simply add an assertion here https://github.com/ember-cli/ember-cli/blob/93c4fd5763fa69fcb11eb0bee1b6b38e57ad4d15/tests/unit/models/builder-test.js#L206

**Comment by bekzod** [comment]
@stefanpenner done, thanks for hint 👍

**Comment by stefanpenner** [comment]
rebuilding node 4 windows.

**Comment by stefanpenner** [comment]
I believe this will need to be a bugfix, @Turbo87 can you confirm?

**Comment by Turbo87** [comment]
@stefanpenner if I read https://github.com/ember-cli/ember-cli/commit/6650df901e75050fba5840459f60588d95a80a84 correctly the bug was introduced in the 2.15 branch, so we only need to fix it there. @bekzod can you change the target branch of the PR to `beta`?

**Comment by bekzod** [comment]
@Turbo87 what is easiest way changing target ? or better to remake PR ?

**Comment by Turbo87** [comment]
@bekzod what you did above was correct, but you'll also need to adjust your branch. probably the easiest way is:

- copy the sha1 of the bugfix commit (3f2d5618801a48cdf911e3ca0b1328cba6ffe6f9)
- reset your `this-fix` branch to the current `beta` branch (`git reset --hard origin/beta`)
- cherry pick the bugfix commit on top (`git cherry-pick 3f2d5618801a48cdf911e3ca0b1328cba6ffe6f9`)
- force push to update this PR (`git push --force`)

**Comment by bekzod** [comment]
@Turbo87 thanks!, had similar thing in mind thought github had something easier :P

**Comment by Turbo87** [comment]
> thought github had something easier

unfortunately not yet 😞

**Pull request merged**
