### PR TITLE
Updated testem

### LINKED ISSUE #2973: `ember serve` reruns the whole test suite once finished
When the tests are run via `ember serve` and complete, the page is reloaded and the whole suite is run again from start. This results in an infinite running of tests. No error is printed on the console.

When I run the tests "manually", through `localhost:4200/tests`, it does not do that. The suite runs to completion once and then stops.

    $ ember --version
    version: 0.1.6
    node: 0.10.21
    npm: 2.1.8

I am running Ember 1.9.1 and Handlebars 2.0.0.

The machine is a MBP, and Chrome version is 39.0.2171.95 (64-bit) (latest stable).

### PR DESCRIPTION
**Pull request by johanneswuerbach**
Fixes #2973

Changelog: https://github.com/airportyh/testem/compare/v0.6.28...v0.6.30

### CODE REVIEW

**Comment by jgwhite** [comment]
Awesome, thanks!

**Comment by jgwhite** [comment]
AppVeyor has got itself confused but Travis passes and I can vouch for this working just fine in my own example app. Good to merge.

**Comment by stefanpenner** [comment]
re-triggered appveyor

**Comment by johanneswuerbach** [comment]
Looking into windows now.

**Comment by stefanpenner** [comment]
@johanneswuerbach danke

**Comment by chadhietala** [comment]
#3031 Will fix windows.

**Comment by stefanpenner** [comment]
#3031 is fixed

**Comment by johanneswuerbach** [comment]
The latest testem version also had an issue on Windows (https://github.com/airportyh/testem/pull/459), which is fixed and released.

**Comment by johanneswuerbach** [comment]
@stefanpenner this is good to go now.

**Comment by rwjblue** [comment]
Thank you!!!

**Pull request merged**
