### PR TITLE
broccoli/ember-app: Make app/index.html optional

### PR DESCRIPTION
**Pull request by Turbo87**
Resolves https://github.com/ember-cli/ember-cli/pull/6825#issuecomment-287962225

/cc @iezer

### CODE REVIEW

**Comment by iezer** [comment]
@Turbo87 Thanks!

**Comment by rwjblue** [comment]
@homu r+

**Comment by iezer** [comment]
@Turbo87 Found a related, unfortunate, bug. If you make an addon for example `ember-resolver`, it won't build because it doesn't have a file in `src/ui/index.html` :( Solution is to create an empty file.

**Comment by rwjblue** [comment]
@iezer - @mixonic and I spiked on a bunch of `src` related build issues this afternoon, he should be pushing up a branch that you can track soon...

**Pull request merged**
