### PR TITLE
make restore private in favor of safeRestore

### PR DESCRIPTION
**Pull request by kellyselden**
no one is using it, just to protect us.

### CODE REVIEW

**Comment by stefanpenner** [comment]
:+1:

**Comment by kellyselden** [comment]
@homu r+

**Comment by stefanpenner** [comment]
@homu retry

**Comment by stefanpenner** [comment]
bumping timers here: https://github.com/ember-cli/ember-cli/pull/5263

**Comment by stefanpenner** [comment]
@homu retry

**Comment by kellyselden** [comment]
Homu was stubborn on that one! Thanks Stefan.

**Pull request merged**
