### PR TITLE
preserve final newline in addon's package.json

### PR DESCRIPTION
**Pull request by kellyselden**
This regressed in https://github.com/ember-cli/ember-cli/commit/2a946538c416baa59a3276e4d43b045f2a6684de

Visible here https://github.com/ember-cli/ember-addon-output/compare/v2.15.1...v2.16.0-beta.2#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R49

cc @stefanpenner

### CODE REVIEW

**Comment by Turbo87** [comment]
@kellyselden should this target `beta`?

**Comment by kellyselden** [comment]
I couldn't remember if I should cherry-pick into beta.

**Comment by Turbo87** [comment]
nope, just target beta directly, otherwise things will be forgotten 😉

**Comment by kellyselden** [comment]
retargeted and ready for merge

**Pull request merged**
