### PR TITLE
Pr 4358

### PR DESCRIPTION
**Pull request by stefanpenner**

### CODE REVIEW

**Comment by chadhietala** [comment]
LGTM

**Comment by stefanpenner** [comment]
@homu r+

**Comment by stefanpenner** [comment]
addressed failures, lets see now what CI says.

**Comment by stefanpenner** [comment]
@homu retry

**Comment by chadhietala** [comment]
@homu retry

**Comment by stefanpenner** [comment]
@homu r+

**Comment by stefanpenner** [comment]
@martypenner thanks :) sorry for letting this idle for so long

**Comment by martypenner** [comment]
@stefanpenner No worries! A big, ambitious project like this is hard to manage, I'm sure. I'm happy to have been able to contribute.

**Comment by Turbo87** [comment]
- is there a reason for calling the command `show-asset-sizes` instead of just `asset-sizes`?
- would it make sense to add a `--json` flag to that command? e.g. for CI graphing

**Comment by stefanpenner** [comment]
> is there a reason for calling the command show-asset-sizes instead of just asset-sizes?

i prefer `asset-sizes`


> would it make sense to add a --json flag to that command? e.g. for CI graphing

ya very likely

**Pull request merged**
