### PR TITLE
Use "ember-cli-internal-test-helpers"

### PR DESCRIPTION
**Pull request by Turbo87**
This PR replaces some of the `tests/helpers` with helpers from the `ember-cli-internal-test-helpers` package. This is basically dogfooding to make sure `ember-cli-internal-test-helpers` works properly.

/cc @trabus

### CODE REVIEW

**Comment by Turbo87** [comment]
wow, even AppVeyor agrees this time :joy:

**Comment by trabus** [comment]
:+1:

**Comment by Turbo87** [comment]
@rwjblue @stefanpenner any objections?

**Comment by stefanpenner** [comment]
Lgtm

**Comment by Turbo87** [comment]
@homu r+

**Comment by stefanpenner** [comment]
> wow, even AppVeyor agrees this time

:trollface:

**Pull request merged**
