### PR TITLE
[Enhancement] Adding ember publish command

### PR DESCRIPTION
**Pull request by thoov**
Gives the ability to run ember publish which will publish your addon to npm.

### CODE REVIEW

**Comment by rwjblue** [comment]
What does this give us over just running `npm publish`?

**Comment by thoov** [comment]
@rwjblue Right now nothing. This is just the same as `ember install:addon <addon_name>` is basically `npm i --save-dev <addon_name>`. I would like to make this command take a version number such as:
`ember publish 0.0.1` and it will update package.json, do a version bump commit, and publish in one step. Not sure if thats doing to much. What are your thoughts?

**Comment by rwjblue** [comment]
`ember install:addon <addon_name>` does:

* `npm install --save-dev addon-name`
* `ember generate addon-name`

**Comment by rwjblue** [comment]
I'm not opposed to your idea though, I just think it should be an RFC so we can flesh out what the features should be...

**Comment by thoov** [comment]
@rwjblue makes sense. I will close this and we can discuss this in another place.

**Comment by rwjblue** [comment]
@thoov - https://github.com/ember-cli/rfcs is perfect for this

**Pull request closed without merging**
