### PR TITLE
Fix: in case of unlinked entries, `entry[2]` is undefined.

### PR DESCRIPTION
**Pull request by hansl**

### CODE REVIEW

**Comment by hansl** [comment]
Is your appveyor build flaky?  Seems like it's unrelated e2e failing.

**Comment by stefanpenner** [comment]
> Is your appveyor build flaky?

Ya, its abit flaky.

Do you mind adding a unit test?

**Comment by hansl** [comment]
@stefanpenner added a unittest. Verified it failed before my change, worked after.

**Comment by chadhietala** [comment]
@homu r+

**Pull request merged**
