### PR TITLE
added transparent-proxy option to ember serve command

### PR DESCRIPTION
**Pull request by badazz91**
with respect to https://github.com/ember-cli/ember-cli/commit/4fc7ce26ef17881618420e0852a9bdfcaa53a4ce

### CODE REVIEW

**Comment by Turbo87** [comment]
how do you set this option to `false`?

**Comment by badazz91** [comment]
```ember s --proxy http://localhost:3000 --transparent-proxy false```

**Comment by Turbo87** [comment]
hmm, wouldn't it be easier for the users if we used something like `--intransparent-proxy` without having to specify `true/false`?

**Comment by badazz91** [comment]
Yes, I agree. This would be better. Should I update the PR?

**Comment by Turbo87** [comment]
> Should I update the PR?

yes please :)

**Comment by badazz91** [comment]
I have updated the PR.

You can now enable the option like this:
``ember s --proxy http://localhost:3000 --intransparent-proxy`` or short style like this
``ember s --proxy http://localhost:3000 --intransp``.

**Comment by nathanhammond** [comment]
"intransparent" is such an awkward word (transparent's typical opposite is opaque, not negation). Let's wait a day and see if the hive mind can come up with a better name before landing?

Hey everybody! Naming help please!

**Comment by badazz91** [comment]
Hmm ```--opaque-proxy``` ...?

One could also think about ```--no-transparent-proxy``` or ```--non-transparent-proxy```?

**Comment by Turbo87** [comment]
`--no-x-fwd` because it's so much fun typing that :P

**Comment by stefanpenner** [comment]
looks good, but i do appreciate the further exploration of the short version of the flag.

**Comment by badazz91** [comment]
I like ```--no-x-fwd```, but nevertheless I also could stick with ```--intransparent-proxy```, because the ```x-forwared-headers-*```are used to make the requests ```transparent```, when proxying. According to wikipedia ... ;-)

**Comment by stefanpenner** [comment]
> I like --no-x-fwd, but nevertheless I also could stick with --intransparent-proxy,

both seems great IMHO

**Comment by badazz91** [comment]
Let me now, and I will update the PR ... again ;-)

**Comment by badazz91** [comment]
On the other hand, in my opinion, ```--intransparent-proxy```is a little bit more explicit than ```--no-x-fwd```, because it describes the actual behavior, and not what it actually does to achieve that. Furthermore I think it also aligns more with the option ```--insecure-proxy```. But I also understand, that ``opaque`` is better than ``intransparent``.

What's the general opinion on this?

**Comment by stefanpenner** [comment]
> --intransparent-proxy

lets do, individuals that use this commonly can set it in `.emberrc` file and it ends up being self documenting.

**Comment by badazz91** [comment]
FYI, there was already one failing test, when I forked from the master branch.

**Comment by rwjblue** [comment]
👍 to the feature, but 👎 to the word `intransparent` 😝 

Perhaps, `--transparent-proxy` (along with the `--no-transparent-proxy` option allowed for boolean flags via `nopt`)?  If the flag of `transparent-proxy` is set to a boolean these two should work properly, and defaulting to `false` gets us the desired behavior (roughly what we have in this PR already).

**Comment by badazz91** [comment]
@rwjblue ```--transparent-proxy false``` is what the flag in the first version was, before I changed it to ```--intransparent-proxy``` in order to save some typing efffort like suggested by @Turbo87 .

**Comment by rwjblue** [comment]
@badazz91:

Concrete proposal: 

* change the flag to `transparent-proxy`
* change the default value to `true`
* change the `xfwd` option to just use the flag directly (no negation)

With this setup:

* The current defaults are preserved (using `xfwd` by default)
* Disabling is as easy as `--no-transparent-proxy` (which is only a single char longer than `--intransparent-proxy`)
* My brain doesn't hurt trying to grok what `--intransparent-proxy=true`, `--intransparent-proxy=false`, `--no-intransparent-proxy` all do...

**Comment by Turbo87** [comment]
can we make sure somehow that `--no-transparent-proxy` is included in the help text?

**Comment by badazz91** [comment]
@rwjblue @Turbo87 to clearify. I will add :

1. ```transparent-proxy false (default: true)```
2. ```--no-transparent-proxy``` and  really short ```--ntransproxy```

which both can be used to disable xfwd.

**Comment by fpauser** [comment]
I would not add the `--no-transparent-proxy` because as a consequence of this all other boolean-options should also have their `--no-*` counterparts which leads to confusion due to many (possibly unclear/conficting) options.

I would vote for just adding the `--transparent-proxy` option that defaults to `true`.

Maybe it would be a good idea to also add a `--secure-proxy` option that defaults to true and to deprecate the `--insecure-proxy` option over the time, because `--insecure-proxy` right now is the only negating-option - and somehow not in-line with the other boolean-options.

**Comment by badazz91** [comment]
After further consideration, I think it is the best to leave it at just  ```--transparent-proxy false```. It is the most explicit way, in my opinion. As suggested by @stefanpenner, people who use it more often can config it in their ```.emberrc``` to save some typing effort. Furthermore I also agree with @fpauser's idea, to rename ```--insecure-proxy``` to ```--secure-proxy``` for better alignment with the other options.

**Comment by nathanhammond** [comment]
Okay, so it sounds to me like the proposal here is "no further change to this PR as it stands."

I kicked over the failure on Travis without investigation. Assuming that passes, this is last call for comments before merge.

**Comment by badazz91** [comment]
Strangely, Travis still has a failing test using `node v0.12.4`, that I cannot reproduce locally. All tests pass...

> 
  909 passing (18s)
  5 pending

> 
Mocha Tests Running Time: 20056ms

**Comment by stefanpenner** [comment]
@badazz91 rerunning the node 0.12 test

**Comment by badazz91** [comment]
@stefanpenner It still seems to fail. I investigated the test again, and also reran it with ```node v0.12.14```. Looks both good to me ... Why does it still fail? :(

**Comment by fpauser** [comment]
Rebased this on current master & fixed the failing test.

**Comment by stefanpenner** [comment]
@fpauser fantastic, looks great.

**Pull request merged**
