### PR TITLE
[BUGFIX] Fixes broccoli errors when `tests` dir is not present

### LINKED ISSUE #5946: Broccoli errors when tests/ are deleted
According to this person on Reddit: https://www.reddit.com/r/emberjs/comments/4m49rv/disable_tests_with_ember_cli/

I would advocate that if someone decides to opt-out of the test suite for whatever reason and deletes the directory the build should not error.

I have not confirmed this as I'm on a plane and don't want it to crash due to npm install.

### PR DESCRIPTION
**Pull request by twokul**
resolves #5946

### CODE REVIEW

**Comment by twokul** [comment]
cc @rwjblue

**Comment by rwjblue** [comment]
Seems good.  You also confirmed locally?

**Comment by twokul** [comment]
@rwjblue I did

**Comment by stefanpenner** [comment]
So to be clear this just makes it possible to start/stop ember server/test without the existence of `tests` but will still fail if `tests` is removed mid-build. (Which i think we are ok with)

**Comment by twokul** [comment]
@stefanpenner correct

**Comment by rwjblue** [comment]
I'm 👍 here, but CI is blocked until https://github.com/ember-cli/ember-cli/pull/6003 or testem fixes the underlying issue...

**Comment by rwjblue** [comment]
@homu r+

**Comment by nathanhammond** [comment]
Giving up on @homu here.

**Comment by Turbo87** [comment]
since this is a bugfix: do we want to backport this onto `release` or `beta`?

**Comment by nathanhammond** [comment]
It has always been this way and it took until June of this year for it to show up. I'd call it a rare enough scenario that it goes through the normal lifecycle. If somebody shows up here clamoring for it sooner we can revisit.

**Comment by rwjblue** [comment]
Agreed. I'm in favor of letting it ride on master through a full cycle...

**Pull request merged**
