### PR TITLE
Node 10 beta

### PR DESCRIPTION
**Pull request by stefanpenner**

### CODE REVIEW

**Comment by Turbo87** [comment]
we can/should merge upwards once #7792 is merged

**Comment by stefanpenner** [comment]
> we can/should merge upwards once #7792 is merged

whats the difference?

**Comment by Turbo87** [comment]
it is less duplication. if you refer to that change somewhere you only have one link, instead of three links. the changelog generator will also only show this change once instead of three times.

**Comment by stefanpenner** [comment]
> it is less duplication. if you refer to that change somewhere you only have one link, instead of three links. the changelog generator will also only show this change once instead of three times.

Sounds reasonable.

**Pull request closed without merging**
