### PR TITLE
Patched to generate correct files when pod-mode is on as this generat…

### LINKED ISSUE #5942: Blueprint util on ember-add-on with pod wrong folder structure
The following steps:
```bash
$ ember new new-addon
$ cd new-addon
$ ember generate util process --pod
installing util
  create addon/utils/process.js
installing util-test
  create tests/unit/utils/process-test.js
installing addon-import
  create app/process/util.js
```

Latest `app` file has a wrong folder, thus breaking the build:

```
not ok 10 PhantomJS 2.1 - TestLoader Failures: dummy/tests/unit/utils/process-test: could not be loaded
    ---
        actual: >
            null
        stack: >
            missingModule@http://localhost:7357/assets/vendor.js:210:93
            findModule@http://localhost:7357/assets/vendor.js:221:30
            reify@http://localhost:7357/assets/vendor.js:151:32
            build@http://localhost:7357/assets/vendor.js:173:15
            findModule@http://localhost:7357/assets/vendor.js:223:14
            requireModule@http://localhost:7357/assets/vendor.js:26:22
            require@http://localhost:7357/assets/test-loader.js:67:16
            loadModules@http://localhost:7357/assets/test-loader.js:58:25
            load@http://localhost:7357/assets/test-loader.js:89:35
            http://localhost:7357/assets/test-support.js:6477:20
        message: >
            Died on test #1 moduleLoadFailure@http://localhost:7357/assets/test-support.js:6468:15
            require@http://localhost:7357/assets/test-loader.js:69:31
            loadModules@http://localhost:7357/assets/test-loader.js:58:25
            load@http://localhost:7357/assets/test-loader.js:89:35
            http://localhost:7357/assets/test-support.js:6477:20: Could not find module `dummy/utils/process` imported from `dummy/tests/unit/utils/process-test`
        Log: |
    ...
```
So this is generating a wrong folder structure (and import) in `app` structure. I would expect that the file in app was `app/utils/process.js` with the following content:
```
export { default } from 'new-addon/utils/process';
```

Output from ember version --verbose:
```
ember-cli: 2.5.0
http_parser: 2.5.2
node: 4.4.0
v8: 4.5.103.35
uv: 1.8.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 46
openssl: 1.0.2g
os: linux x64
```

I'm not sure if this is related with #5908 , but looks like it.

### PR DESCRIPTION
**Pull request by morhook**
…or is not used for multiple files AsFarAsIKnow

Highly related with PR https://github.com/emberjs/ember.js/pull/13624

@Turbo87 can you look at this one? 

Resolves #5942

### CODE REVIEW

**Comment by Turbo87** [comment]
@morhook can you quickly outline what exactly this PR changes?

**Comment by morhook** [comment]
Sure @Turbo87 ! This PR is changing that the `addon-import` stops generating different `pod` files. According to what I've seen on `ember.js` blueprints, this generator is only used in cases when a generator doesn't have multiple files.

According to what I'm seeing in the generated files, when a generated file is a single-file, the `--pod` parameter is being ignored, as a single-file should be put inside a directory instead of the component-name (examples, routes, templates, controllers and componentes are multiple-files --pod sensitive).

I think for merging this one, it makes sense to verify on ember-data, ember-cli-qunit and ember-cli-mocha, that this generator is not called in multiple-files cases.

**Comment by Turbo87** [comment]
@morhook I think we should probably solve https://github.com/ember-cli/ember-cli/issues/5971 first so that we can test this properly. I have a branch ready for that, but https://github.com/ember-cli/ember-cli-blueprint-test-helpers/pull/61 needs to be merged before I can open that next PR... 😉

**Comment by morhook** [comment]
Go forward @Turbo87 !! :+1:

**Comment by morhook** [comment]
Modifying this will break controller-generation (in addon in pod mode). Closing PR

**Pull request closed without merging**
