### PR TITLE
Detect ember-cli from deps as well as devDeps

### PR DESCRIPTION
**Pull request by searls**
This is useful to folks who, for whatever reason, need to have access to 
ember-cli with production dependencies (certain shrinkwrap scenarios,
installation into some build server configs, and probably other cases).

Looks like #3015 was closed prematurely when @rwjblue gave a bit of good
implementation advice. Also addresses #2207.

### CODE REVIEW

**Comment by stefanpenner** [comment]
@searls can you add a test?

**Comment by searls** [comment]
@stefanpenner you bet you. Added characterization tests around the method too and fixed an unrelated issue (namely that the method would raise in the event that someone's package.json had no `devDependencies`)

**Comment by stefanpenner** [comment]
> (namely that the method would raise in the event that someone's package.json had no devDependencies)

:+1:

**Comment by stefanpenner** [comment]
one thing to be weary of, is that we don't want addons including ember-cli as a dependency.

**Pull request merged**
