### PR TITLE
use local bower for CI, rather then installing it twice

### PR DESCRIPTION
**Pull request by stefanpenner**

### CODE REVIEW

**Comment by rwjblue** [comment]
I think we need to test this in a real app, as our tests do not directly use this file...

**Comment by stefanpenner** [comment]
it works

**Comment by stefanpenner** [comment]
maybe not: https://travis-ci.org/stefanpenner/ember-jobs/jobs/54480422 looking shortly

**Comment by stefanpenner** [comment]
ug, thet validations prevented it..

**Pull request closed without merging**
