### PR TITLE
Update minimum Testem version to 1.0.0-rc.4.

### LINKED ISSUE #5288: [2.2.0-beta.2] Error: Callback was already called.
This happens during `ember test`, but not `ember test --server`.

```
/Users/mliu/Workspace/awesome-app/node_modules/ember-cli/node_modules/testem/node_modules/async/lib/async.js:43
            if (fn === null) throw new Error("Callback was already called.");
                             ^

Error: Callback was already called.
    at /Users/mliu/Workspace/awesome-app/node_modules/ember-cli/node_modules/testem/node_modules/async/lib/async.js:43:36
    at ChildProcess.<anonymous> (/Users/mliu/Workspace/awesome-app/node_modules/ember-cli/node_modules/testem/lib/launcher.js:200:9)
    at emitTwo (events.js:92:20)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

### LINKED ISSUE #5290: Tests are not auto run after changes (2.0.0-beta.2)
I have created a repo which reproduces the steps (https://github.com/andrewtimberlake/ember-test-autorun).
Each commit outlines the steps from a 1.13.13 build of a new app, through upgrade to 2.0.0-beta.2

Steps to reproduce the problem:
- Initial Commit from Ember CLI v1.13.13
- Added basic helper - tests autoran
- Update ember-cli (delete node_models and bower_components; then npm i && bower i)
- Restart `ember t -s`
- change and save test file, the tests are rebuilt but tests don't run

### PR DESCRIPTION
**Pull request by rwjblue**
Fixes #5290
Fixes #5288

### CODE REVIEW

**Comment by stefanpenner** [comment]
LGTM

**Comment by stefanpenner** [comment]
@homu r+

**Comment by toranb** [comment]
Anyone else felt some point after this upgrade? On our CI box (centOS) we run into this error frequently

```
# ok
/mnt/tmpfs/.jenkins/foobar/node_modules/async/lib/async.js:43
            if (fn === null) throw new Error("Callback was already called.");
                             ^

Error: Callback was already called.
    at /mnt/tmpfs/.jenkins/foobar/node_modules/async/lib/async.js:43:36
    at ChildProcess.<anonymous> (/mnt/tmpfs/.jenkins/foobar/node_modules/testem/lib/launcher.js:195:9)
    at ChildProcess.g (events.js:260:16)
    at emitTwo (events.js:92:20)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

**Comment by rwjblue** [comment]
@toranb - This PR was supposed to fix https://github.com/ember-cli/ember-cli/issues/5288 (which is the issue you are describing).

**Comment by toranb** [comment]
@rwjblue thanks for the quick reply - I'll look that commit over!

**Pull request merged**
