### PR TITLE
Install JSHint files via "ember-cli-jshint" blueprint

### LINKED ISSUE #6269: Remove remaining coupling to JSHint
Currently our `app` and `addon` blueprints still include `.jshintrc` files (see https://github.com/ember-cli/ember-cli/tree/master/blueprints/app/files), which are now also provided by the default blueprint in `ember-cli-jshint` (see https://github.com/ember-cli/ember-cli-jshint/pull/21). To remove the duplication we should remove the `.jshintrc` files from our blueprint and run the `ember-cli-jshint` blueprint once the dependency is installed.

Unfortunately it's not quite as simple as adding the `lookupBlueprint().install()` call to the `afterInstall()` hook of the `app` and `addon` blueprints, because that hook will run _before_ `npm install` was executed. So currently possible is only:
1. `app` blueprint adds a `package.json` file including the `ember-cli-jshint` dependency
2. `app` blueprint tries to install `ember-cli-jshint` blueprint but fails because the dependency is not yet installed
3. `npm install` will install the `ember-cli-jshint` dependency but not run the corresponding blueprint

Now I am looking for ways to install the blueprint _after_ `npm install` has finished without breaking the world. Is there a good way to do this in the current code base?

Should we maybe implement a public `installAddon()` method that only resolves once `npm install` for that addon has finished?

/cc @rwjblue @stefanpenner

### PR DESCRIPTION
**Pull request by Turbo87**
This PR resolves #6269. It changes the steps in the `ember init` flow to be: install blueprint, `npm install`, `bower install`, `ember generate ember-cli-jshint`, `git init && git add && git commit`.

This will bring us closer to switching to `ember-cli-eslint` instead.

### CODE REVIEW

**Comment by Turbo87** [comment]
As @rwjblue mentioned on Slack: this PR currently leaves the project in an inconsistent state when `--skip-npm` is used since the `ember-cli-jshint` addon is listed in `package.json`, but the blueprint won't be installed when `npm install` is run manually.

To resolve this we should remove `ember-cli-jshint` from the `package.json` file in the `app` blueprint and let NPM add it when installing the addon after the app itself has installed everything else. This is however currently blocked on #6502.

**Comment by Turbo87** [comment]
@rwjblue I think I've addressed your initial feedback now. would love to get a second review :)

**Comment by rwjblue** [comment]
LGTM

**Comment by stefanpenner** [comment]
@homu r+

**Comment by kellyselden** [comment]
A little late to the party, but should likes like [this](https://github.com/ember-cli/ember-cli/blob/master/blueprints/app/files/testem.js#L1) be removed as well and let the addon add them back? @Turbo87

**Comment by nathanhammond** [comment]
@kellyselden That would be ridiculously complicated to do well. We'd need a better blueprint api, which I think we can get to via blprnt.

**Comment by kellyselden** [comment]
@nathanhammond I may be missing something. Wouldn't it be easy to do with `Blueprint. insertIntoFile()`?

https://github.com/ember-cli/ember-cli/blob/master/lib/models/blueprint.js#L1156

**Comment by nathanhammond** [comment]
Yes-ish. If you knew which files existed. You end up introducing coupling between two separate projects without a specific API boundary and that gets a bit messy.

**Comment by kellyselden** [comment]
I can see that. At the least shouldn't we remove the jshint artifacts in our blueprints, even if ember-cli-jshint doesn't choose to re-add?

**Comment by nathanhammond** [comment]
Probably, open a tracking issue?

**Comment by kellyselden** [comment]
#6540

**Pull request merged**
