### PR TITLE
[INTERNAL] Extract broccoli-config-replace into its own repository See #4907

### PR DESCRIPTION
**Pull request by yaymukund**
As per #4907, I've extracted `broccoli-config-replace` into [its own repository][broccoli-config-replace] and written some tests. I cannot open a pull request in [ember-cli/broccoli-config-replace][ember-cli-broccoli-config-replace] using the github UI because it's totally empty. Please let me know if I did anything wrong. ^^

(Tests fail here because `broccoli-config-replace` isn't in npm yet.)

[broccoli-config-replace]: http://github.com/yaymukund/broccoli-config-replace
[ember-cli-broccoli-config-replace]: http://github.com/ember-cli/broccoli-config-replace

### CODE REVIEW

**Comment by stefanpenner** [comment]
@yaymukund awesome!

* repo primed -> https://github.com/ember-cli/broccoli-config-replace/blob/master/README.md
* you have been added to the repo as an admin

feel free to publish it to NPM, but if possible could you add myself and @rwjblue to the npm owners?

**Comment by yaymukund** [comment]
Thanks!! Hey, just a heads up... it looks like these tests are passing (at least in Travis as of now) BUT also like they failed [in the log][]:

`can render a component with a manually imported template`

The conflicting output is confusing me, so it would be helpful if someone could confirm that's indeed a failure. Regardless, I'll look into it later today.

[in the log]: https://travis-ci.org/ember-cli/ember-cli/jobs/87327985

**Comment by yaymukund** [comment]
It looks like this test failure exists in master. I've opened #4988

**Comment by yaymukund** [comment]
I think this is good to go, but please let me know if you need anything else from me. Cheers.

**Comment by stefanpenner** [comment]
@homu r+

**Pull request merged**
