### PR TITLE
Adds Node 7 to testing matrix

### PR DESCRIPTION
**Pull request by twokul**

### CODE REVIEW

**Comment by kellyselden** [comment]
hmm node 7 not supported yet on appveryor

**Comment by stefanpenner** [comment]
> hmm node 7 not supported yet on appveryor

maybe we should leave it off appveyor for now?

@twokul awesome!

**Comment by kellyselden** [comment]
> maybe we should leave it off appveyor for now?

yes, lets split into 2 PRs so we can get travis coverage at least.

**Comment by twokul** [comment]
sure, let me quickly change

**Comment by stefanpenner** [comment]
👍

**Comment by nathanhammond** [comment]
We need to add this to the engines key in package.json as well.

**Pull request merged**
