### PR TITLE
[ENHANCEMENT] Replace install:addon with install, remove install:bower and install:npm

### PR DESCRIPTION
**Pull request by DanielOchoa**
This closes https://github.com/ember-cli/ember-cli/issues/3204.

### CODE REVIEW

**Comment by stefanpenner** [comment]
I tried to rebase this, unfortunately that results in several test failures. @DanielOchoa mind digging in?

**Comment by stefanpenner** [comment]
awesome. This will land in `0.3.0`

**Comment by DanielOchoa** [comment]
I'll check it out for sure.

**Comment by DanielOchoa** [comment]
I pulled everything from master and did a rebase. It looks like the `uninstall:npm` command was added. Should this be changed to `uninstall` and just work for addons?

**Comment by stefanpenner** [comment]
i think this rebase was in-error, there are far to many commits

**Comment by DanielOchoa** [comment]
Oops. You are correct.

**Comment by DanielOchoa** [comment]
@stefanpenner it's now up to date.

**Comment by kellyselden** [comment]
@DanielOchoa I think the plan was to change `uninstall:npm` to `uninstall` for addons when this feature was ready.

**Comment by stefanpenner** [comment]
i just realized, we actually should do a deprecation phase here...

thoughts @rwjblue ?

**Comment by stefanpenner** [comment]
in retro-spec we should likely keep `install:bower` until we kill bower entirely, `npm:install` should be replaced with a command that errors, and informs the user of the change.

**Comment by DanielOchoa** [comment]
sounds good. I'll make the necessary changes.

**Comment by DanielOchoa** [comment]
@stefanpenner 
> in retro-spec.. 
lol I didn't see what you did there until now. :)

`install:bower` is untouched. I also included the deprecation warning for the command `uninstall:npm` and throwing a friendly error. `ember:install` also throws a friendly error for when users try to use it like before the change (without arguments).

**Comment by Gaurav0** [comment]
Could you have kept install:addon but thrown a deprecation warning? A lot of addons now have out of date installation instructions.

**Comment by stefanpenner** [comment]
@Gaurav0 Ya likely a good point, got time for a pr to deprecate?

**Comment by DanielOchoa** [comment]
I'll add it back by throwing a deprecation warning if @Gaurav0 hasn't done it yet.

**Pull request merged**
