### PR TITLE
upgrade testem

### PR DESCRIPTION
**Pull request by stefanpenner**
* no longer leaks subprocesses (chrome / phantoms)
* only supports modern node

---

I would love to also backport this beta/stable, thoughts?

### CODE REVIEW

**Comment by twokul** [comment]
I can backport once we land

**Comment by twokul** [comment]
related to https://github.com/ember-cli/ember-cli/pull/7575

**Comment by stefanpenner** [comment]
oops, fixed commit message...

**Comment by stefanpenner** [comment]
@rwjblue any concerns with me backporting?

**Comment by rwjblue** [comment]
No, none.  AFAICT the only breaking changes were dropping old Node support, which we have done a while ago.  Seems totally good to get this out in a patch release...

**Pull request merged**
