### PR TITLE
[ENHANCEMENT] Deprecate `outputPaths` build option

### LINKED ISSUE #9478: Deprecate outputPaths usage under Embroider
Under Embroider the output paths of `/dist` are no longer predetermined. For example the application's javascript which would normally be `/dist/assets/app_name.js` will become for example: `/dist/assets/chunk.adjasld33lk23jol.js` + `/dist/assets/chunk.zsiojladj20ljk23jl.js`. The amount of "chunks" can vary based on the size / structure of your app especially if you have route based code splits, lazy engines, and/or dynamic imports. Each of these will create their own chunk(s). This issue is a reminder that we need to add the appropriate deprecations before enabling Embroider.

### PR DESCRIPTION
**Pull request by bertdeblock**
Closes #9478.

### CODE REVIEW

**Comment by bertdeblock** [comment]
Draft, as I don't think we can land this before v5.1.0.

**Comment by locks** [comment]
@bertdeblock I think it's time 😅 Might need to update the version values.

**Comment by NullVoxPopuli** [comment]
what would they be? 5.2 or 5.3?

**Comment by bertdeblock** [comment]
Updated. Beta has its own branch, so master should be `5.3.0` at the moment.

**Review by locks — APPROVED** [review]

**Comment by boris-petrov** [comment]
I can't seem to find a migration path anywhere. What are we supposed to change `outputPaths` with?

**Comment by bertdeblock** [comment]
It was deprecated without a replacement if I remember correctly:
https://deprecations.emberjs.com/ember-cli/v5.x#toc_ember-cli-outputPaths-build-option

**Pull request merged**
