### PR TITLE
return currentURL() rather than path, ref #3719

### PR DESCRIPTION
**Pull request by mariogintili**
Originally referenced on #3719, in this PR I have:

- Updated the fixture, replacing `currentPath()` for `currentUrl()`
- Changed the template accordingly

### CODE REVIEW

**Comment by mariogintili** [comment]
```
 1 failing
 
  1) Acceptance: ember generate pod adapter foo/bar --pod:
     Error: timeout of 5000ms exceeded. Ensure the done() callback is being called in this test.
      at null.<anonymous> (C:\projects\ember-cli\node_modules\mocha\lib\runnable.js:170:19)
      at Timer.listOnTimeout (timers.js:110:15)
 ```

Looks like this fail is unrelated to my branch could be a random fail @jgwhite ?

**Comment by jgwhite** [comment]
Yeah, appveyor isn’t super reliable. Restarting the build.

**Comment by jgwhite** [comment]
@ember-cli/owners I’m struggling to decipher this AppVeyor failure. Any cause for concern?

**Comment by stefanpenner** [comment]
looks like it is rebuilding... lets wait it out.

**Pull request merged**
