### PR TITLE
Add new `search` command

### PR DESCRIPTION
**Pull request by thoov**
Adds a new command called `search`. It currently supports 3 search modes: addon discovery, code discovery, and code exploration which are explained below.

### Addon Discovery

The addon discovery mode allows you to search for addons based on a given keyword. This is a great way to discovery addons within the community:

```
ember search --addon 'i18n'
```

### Code Discovery

The code discovery mode allows you to search all addons that contain a given code snippet. This is great to find other addons that are using a method or hook that you would like to learn more about. As an example, hooks within your index.js file such as: `included`, `treeForApp`, `treeForPublic`, etc. are not well documented. Here we can search to find other addons which are using one of these hooks:

```
ember search --code 'treeForPublic'
```

### Code Exploration

The last mode is code exploration. This allows you to see actual code diffs based on that code snippet. Note that we must supply the exact addon name via --addon.

```
ember search --addon 'ember-intl' --code 'treeForPublic'
```

Slightly unrelated note: It would be interesting to explore (if the cli-core team hasn't already) a way to install global commands like this one via addons without having to add code to ember-cli's code base.

### CODE REVIEW

**Comment by Cryrivers** [comment]
nice to see such a feature integrated to Ember CLI! 👍

**Comment by rwjblue** [comment]
Might be nice to pull from emberobserver.com's API instead of npm directly, at which point we could provide ratings, categories, etc...

**Comment by thoov** [comment]
@rwjblue Sounds good. I will use emberobserver's and bring in ratings + categories

**Comment by thoov** [comment]
Using emberobservers code search allow us to do this:

kapture 2017-01-11 at 15 56 46

**Comment by kategengler** [comment]
Just for awareness, Ember Observer's API is about to change to JSONAPI. I plan to support both APIs for a short time but the old version has some serious performance issues so it needs to go.

**Comment by thoov** [comment]
@kategengler Do you have a sample JSON output ready yet or a dev environment with the new response by chance?

**Comment by rondale-sc** [comment]
@thoov Would it be possible to include a link to the github repo with the line number when doing code search so that it would be command clickable right from the terminal?

**Comment by thoov** [comment]
@rondale-sc Good idea. I will add that

**Comment by thoov** [comment]
@rwjblue @stefanpenner r? Also Im not sure why the build is failing. It looks to be pulling an old commit that I rebased over. Not sure if one of you could clear the cache or something.

**Comment by les2** [comment]
this is awesome

**Pull request closed without merging**
