### PR TITLE
Allow addons to have pod based templates

### LINKED ISSUE #3586: Pod templates inside addons don't get compiled
Currently there seems to be an issue with templates being imported from pods inside in-repo-addons (I haven't yet verified if the same issue affects addons as well). [This repo](https://github.com/trabus/in-repo-addon-pod-template) illustrates it, where trying to load a pod based component's template fails. The non-pod component is able to load with no issue, but the pod component fails because the template is not compiled.

Running the example app above, the following error occurs:
```
 Uncaught Error: Could not find module `foo-bar/components/foo-bar/template` imported from `foo-bar/components/foo-bar/component`
```

The error is not present when the `foo-bar` component is removed from the `application.hbs`.

I believe the issue lies with the way the templates are processed in addons. The [tree passed]( is `addon/templates`, so) into [compileTemplates](https://github.com/ember-cli/ember-cli/blob/master/lib/models/addon.js#L443)  is `addon/templates`, so it seems the `addon` tree is missing templates inside pod structure folders.

### PR DESCRIPTION
**Pull request by pzuraq**
Updated version of #3596, fixes #3586.

### CODE REVIEW

**Comment by gmurphey** [comment]
Thanks for getting the ball rolling on this again, @pzuraq!

**Comment by pzuraq** [comment]
No prob! I realize the [upcoming packager refactor](https://github.com/ember-cli/rfcs/pull/14) may make this approach obsolete, but we're pushing pod structure in our addons so the sooner it gets in the better.

**Comment by stefanpenner** [comment]
@pzuraq yes, i believe an intermediate step is very reasonable.

@chadhietala can you review this, I want to be sure we don't deviate from the packager works.

**Comment by chadhietala** [comment]
@stefanpenner We may not need this in the future, but this doesn't deviate.

**Pull request merged**
