### PR TITLE
Improve error message for app.import of a dir

### PR DESCRIPTION
**Pull request by stefanpenner**

### CODE REVIEW

**Comment by stefanpenner** [comment]
@homu r+

**Comment by rwjblue** [comment]
@homu r+

**Comment by stefanpenner** [comment]
@homu retry

**Comment by stefanpenner** [comment]
@homu retry

**Comment by stefanpenner** [comment]
This may actually need to be a warning, because it appears to break some current options/assumptions

**Comment by stefanpenner** [comment]
will revisit, this will be a breaking change....

**Pull request closed without merging**
