### PR TITLE
Add missing annotations.

### PR DESCRIPTION
**Pull request by rwjblue**
These annotations help us track things down while visualization...

### CODE REVIEW

**Comment by Turbo87** [comment]
@rwjblue any idea where the build failures are coming from?

**Comment by rwjblue** [comment]
Yes, I added `annotation` to calls to `broccoli-babel-transpiler`, and (as you know) it passes its options directly through to `babel` so babel is erroring that `annotation` isn't a valid babel option. 😿

**Comment by Turbo87** [comment]
@rwjblue should we deprecated that type of usage in `broccoli-babel-transpiler`? we could instead use a `babel` key in the options hash

**Comment by rwjblue** [comment]
Yes, we should basically deprecate not having a `options.babel` key...

**Comment by Turbo87** [comment]
Yeah, that's what I meant. Similar to `rollup` in https://github.com/chadhietala/broccoli-rollup.

**Comment by nathanhammond** [comment]
Can we just drop the two babel annotations and do the rest? And then file a tracking issue for the rest of the work?

**Comment by rwjblue** [comment]
@nathanhammond - Makes sense, yeah I can do that.

**Comment by rwjblue** [comment]
Updated broccoli-babel-transpiler to allow annotations in https://github.com/babel/broccoli-babel-transpiler/pull/108 and https://github.com/babel/broccoli-babel-transpiler/pull/107 (6.0-alpha), and rebased (geez we've been busy).

Assuming Travis is 👍, this is finally good to go...

**Comment by nathanhammond** [comment]
@homu r+

**Pull request merged**
