### PR TITLE
update babel deprecation message

### PR DESCRIPTION
**Pull request by kellyselden**
borrowed from https://github.com/babel/ember-cli-babel/pull/215

### CODE REVIEW

**Comment by rwjblue** [comment]
Seems good to me, mind adding a test or two of the util?

**Comment by rwjblue** [comment]
CI failure seems related:

```
not ok 256 EmberApp shows ember-cli-shims deprecation
  TypeError: Cannot read property 'name' of undefined
      at calcAddonChain (lib/utilities/calc-addon-chain.js:10:26)
      at EmberApp._checkEmberCliBabel (lib/broccoli/ember-app.js:542:32)
      at EmberApp._initVendorFiles (lib/broccoli/ember-app.js:450:38)
      at new EmberApp (lib/broccoli/ember-app.js:135:10)
      at Context.<anonymous> (tests/unit/broccoli/ember-app-test.js:1029:11)
```

**Comment by Turbo87** [comment]
@kellyselden do you have time to revive this?

**Comment by rwjblue** [comment]
@kellyselden - Ping 😸

**Comment by rwjblue** [comment]
Probably not worth resurrecting at this point...

**Pull request closed without merging**
