### PR TITLE
[INTERNAL] Rip out broccoli-config-loader into its own repository See #4907

### PR DESCRIPTION
**Pull request by yaymukund**
As per #4907, I've extracted `broccoli-config-loader` into [its own repository][broccoli-config-loader] and ported the tests. I cannot open a pull request in [ember-cli/broccoli-config-loader][ember-cli-broccoli-config-loader] using the UI because it's totally empty. Please let me know if I did anything wrong. ^^

(Tests fail here because `broccoli-config-loader` isn't in npm yet.)

[broccoli-config-loader]: http://github.com/yaymukund/broccoli-config-loader
[ember-cli-broccoli-config-loader]: http://github.com/ember-cli/broccoli-config-loader

### CODE REVIEW

**Comment by trabus** [comment]
@yaymukund I just added a readme so you should be able to add a PR now.

**Comment by yaymukund** [comment]
Thanks, @trabus! I've gone ahead and done that in https://github.com/ember-cli/broccoli-config-loader/pull/1

**Comment by stefanpenner** [comment]
am i blocking this on anything?

**Comment by yaymukund** [comment]
@stefanpenner https://github.com/ember-cli/broccoli-config-loader/pull/1 needs to be merged/published and then I can rebase this branch and (cross fingers) tests will pass

**Comment by stefanpenner** [comment]
> @stefanpenner ember-cli/broccoli-config-loader#1 needs to be merged/published and then I can rebase this branch and (cross fingers) tests will pass

its rebased, publishing once i get travis setup

**Comment by stefanpenner** [comment]
@yaymukund travis published: ➜  broccoli-config-loader git:(master) npm publish
+ broccoli-config-loader@1.0.0

**Comment by yaymukund** [comment]
@stefanpenner I think this is good to merge as well, when you get a chance.

**Comment by stefanpenner** [comment]
@homu r+

**Comment by yaymukund** [comment]
It looks like travis is failing to `nvm install` again :confounded:

**Comment by stefanpenner** [comment]
@homu retry

**Pull request merged**
