### PR TITLE
Unfortunately remove CSP add-on

### PR DESCRIPTION
**Pull request by stefanpenner**
* UX in browsers is so poor, this confuses most
* it is a painful barrier for new users
* it can still be pulled in for those security savvy
* Pain has been brought up with vendors, but no movement yet

—

I would love to restore this once the UX is reasonable,
right now it does more harm then good.

### CODE REVIEW

**Comment by stefanpenner** [comment]
@homu +r

**Comment by stefanpenner** [comment]
@homu r+

**Comment by kellyselden** [comment]
I think this warrants a special step in the changelog upgrade steps. "This plugin is now optional. If you liked it, keep it in your package.json". Some people might zealously remove it because our official blueprint removed it, when they may want to keep it. Thoughts?

**Comment by rwjblue** [comment]
@kellyselden - Yeah, I agree. I'll try to come up with some good wording, will ping you on release note PR so you can review...

**Comment by kellyselden** [comment]
@rwjblue Many thanks. I will add an issue to track.

**Pull request merged**
