### PR TITLE
remove bower install from travis

### PR DESCRIPTION
**Pull request by kellyselden**
Don't know if it is the right time for this yet, but we will probably want to do this eventually.

### CODE REVIEW

**Comment by Turbo87** [comment]
this should probably be coupled with #6739

**Comment by kellyselden** [comment]
Agreed. Feel free to close this when that happens.

**Comment by rwjblue** [comment]
Needs a rebase to deal with `yarn` conditional in `.travis.yml`.

**Comment by rwjblue** [comment]
OK, I rebased and whatnot via githubs UI, this is ready for another review...

**Comment by rwjblue** [comment]
Ya, kinda annoying, but we can live with it.  Next time I'll be less lazy 😛...

**Comment by rwjblue** [comment]
@homu r+

**Pull request merged**
