### PR TITLE
Updated podModulePrefix documentation

### PR DESCRIPTION
**Pull request by Matt-Jensen**
Update to the Github pages to reflect the new location, in app.js, to set the pod structure naming convention.

### CODE REVIEW

**Comment by stefanpenner** [comment]
i don't believe this is correct

**Comment by Matt-Jensen** [comment]
Fair enough, was just attempting to reflect the suggestions in #4094. However, I'm happy to close if this is counterproductive.

**Comment by stefanpenner** [comment]
It appears reasonable. I am just unsure what the final fork will be. @trabus do you have thoughts to share?

**Comment by trabus** [comment]
We reverted the change for 0.2.6, as the removal was a bit too early. I'd prefer to keep things as they currently are on master, for which the existing docs are correct.

Eventually, we will remove it, but not until the final state of pods is determined, and naming conflicts with reserved words can be mitigated. Until then, podModulePrefix is a necessary evil for those that need it.

**Comment by stefanpenner** [comment]
> Eventually, we will remove it, but not until the final state of pods is determined, and naming conflicts with reserved words can be mitigated. Until then, podModulePrefix is a necessary evil for those that need it.

:+1: aligned with my thoughts.

@Matt-Jensen i appreciate the contribution, but It may be slightly pre-mature.

**Pull request closed without merging**
