### PR TITLE
Add a book position in the 'tutorials' section.

### PR DESCRIPTION
**Pull request by gregzx**
I suggest adding this second book to the tutorials list.

### CODE REVIEW

**Comment by stefanpenner** [comment]
In-order to not offend any authors, we should insert them in chronological order of inserting (or alphabetically)

**Comment by gregzx** [comment]
Good point. In this case alphabeticall equals chronological so no dilema here ;)

**Comment by stefanpenner** [comment]
thanks for the submission :) I feel bad that i forgot to add @balinterdi  book!

**Comment by gregzx** [comment]
Yea come on, shame on you! ;)

**Comment by stefanpenner** [comment]
:(

**Comment by balinterdi** [comment]
@stefanpenner I forgive you, son :) @gregzx Thank you from saving me from having to tout my own horn ;)

**Comment by gregzx** [comment]
My pleasure @balinterdi . Your book is a great intro to Emberjs - it surely deserves a spot on that list.. Just keep rarwe up to date please! ;) cheers.

**Pull request merged**
