### PR TITLE
Extracting watch-detector to standalone module

### PR DESCRIPTION
**Pull request by chrmod**
To be merged after https://github.com/chrmod/watch-detector/issues/3

### CODE REVIEW

**Comment by chrmod** [comment]
@stefanpenner should I push `watch-detector` initial release to npm now or rather wait before we move it under github organization ?

**Comment by stefanpenner** [comment]
@chrmod https://github.com/chrmod/watch-detector/issues/3#issuecomment-350872418

Feel free to release whenever but add @rwjblue / @kellyselden / @Turbo87  and myself to the npm package owners list

**Comment by chrmod** [comment]
@stefanpenner okay, pushed to npm. Can you please trigger CI tests for this PR?

**Comment by stefanpenner** [comment]
triggering

**Comment by chrmod** [comment]
@stefanpenner seems to be fine now

**Pull request merged**
