### PR TITLE
Changes match application regex

### LINKED ISSUE #3403: ember-cli project failing because project name is 'query'
Do `ember new query` and then `ember server` and you'll get:

```
version: 0.2.0-beta.1
Livereload server on port 35729
Serving on http://0.0.0.0:4200/
File: bower_components/jquery/src/intro
Unexpected token (45:0)
SyntaxError: Unexpected token (45:0)
    at raise (/Users/btecu/Desktop/query/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/acorn.js:333:15)
    at unexpected (/Users/btecu/Desktop/query/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/acorn.js:1366:5)
    at parseExprAtom (/Users/btecu/Desktop/query/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/acorn.js:2153:7)
    at parseExprSubscripts (/Users/btecu/Desktop/query/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/acorn.js:2012:28)
    at parseMaybeUnary (/Users/btecu/Desktop/query/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/acorn.js:1995:16)
    at parseExprOps (/Users/btecu/Desktop/query/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/acorn.js:1946:24)
    at parseMaybeConditional (/Users/btecu/Desktop/query/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/acorn.js:1930:16)
    at parseMaybeAssign (/Users/btecu/Desktop/query/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/acorn.js:1913:16)
    at parseExpression (/Users/btecu/Desktop/query/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/acorn.js:1898:16)
    at parseStatement (/Users/btecu/Desktop/query/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/acorn.js:1586:38)
```

I just spent two hours trying on multiple computers, both Windows and Mac to realize that the problem was name of the project. Somehow `ember-cli` doesn't like the name `query` and I'm not aware of any reserved keywords other than `store` and JS keywords.

Funny thing, I was trying to create a small project to reproduce a bug in `queryParams`...

### PR DESCRIPTION
**Pull request by twokul**
Changes match regex for application tree to "startsWith".
(fixes the case when jQuery files were matched when project's name is `query`).

Fixes https://github.com/ember-cli/ember-cli/issues/3403.

### CODE REVIEW

**Comment by twokul** [comment]
cc @chadhietala

**Comment by chadhietala** [comment]
Restarting CI.

**Comment by rwjblue** [comment]
test please

**Comment by stefanpenner** [comment]
cc @twokul

**Comment by stefanpenner** [comment]
@twokul friendly reminder

**Comment by twokul** [comment]
@stefanpenner do you mind helping me out with the test? I'm not 100% I wrote it correctly.

**Comment by twokul** [comment]
@chadhietala @rwjblue fellas, mind restarting appveyor?

**Comment by chadhietala** [comment]
Appveyor restarted.

**Comment by twokul** [comment]
@chadhietala :+1:

**Pull request merged**
