### PR TITLE
Revert amd module support

### PR DESCRIPTION
**Pull request by stefanpenner**
- breaks https://github.com/ember-cli/ember-cli/issues/5538 although https://github.com/stefanpenner/broccoli-persistent-filter/pull/48/files fixes
- walks + processes over all inputDependency paths (basically everything in bower_components) causing a performance regression in proportion to the number of files in bower_components

I originally thought the performance hit would be ok, but I overlooked the fact that this forces substantially more work in its current form. I would like to bring this back once the performance regression is addressed.

I suspect addressing the performance regression will also address #5538, as we should only be processing files we explicitly need to.

Currently we rely on funnel + mergeTrees not traversing to the leaves of these directories, and then finally concat [carefully only reading the files it truly cares about](https://github.com/ember-cli/ember-cli/blob/master/lib/broccoli/ember-app.js#L1140-L1151) this prevents us from incurring a large penalty if bower_components happens to contain many files, most of which are not used.

I suspect this tool could do something similar, pluck those files out first, or maybe become part of the concat story.

cc @ef4

### CODE REVIEW

**Comment by rwjblue** [comment]
:+1: - LGTM

**Comment by rwjblue** [comment]
I'm happy to help @ef4 work through the identified issues, but I think it is important for us to get a 2.4.1 out soonish fixing #5538.

**Comment by ef4** [comment]
I think we can do something much more focused here, because the user is
declaring explicitly which files are subject to this feature. We can
construct a completely separate broccoli tree for them.

**Comment by stefanpenner** [comment]
@ef4 ya totally, I just don't have cycles today or I would try and sort it out. We can restore once its updated.

as @kellyselden mentioned in chat, we should likely consider feature flags or similar.

**Comment by stefanpenner** [comment]
@homu r+

**Pull request merged**
