### PR TITLE
Prints correct phantomjs version

### LINKED ISSUE #5906: phantomjs --version in .travis.yml is wrong version
found here https://github.com/ember-cli/ember-cli/pull/5901#issuecomment-219645184

might need to change to something like `node_modules/phantomjs-prebuilt/bin/phantomjs --version`. I might get to it, but anyone feel free to fix!

### PR DESCRIPTION
**Pull request by twokul**
resolves #5906

### CODE REVIEW

**Comment by nathanhammond** [comment]
@homu r+

**Comment by Turbo87** [comment]
@twokul it seems that we missed this in 2.7.0. can you verify? I thought the version output was introduced in 2.8.0 instead.

**Comment by twokul** [comment]
@Turbo87 correct, noticed it last night

**Comment by twokul** [comment]
@Turbo87 not a huge deal though imo

**Pull request merged**
