### PR TITLE
[BUGFIX beta] Don't merge `emberCLITree` twice

### LINKED ISSUE #7222: Including `emberCLITree` twice?
It seems like we include `emberCLITree` twice, [here](https://github.com/ember-cli/ember-cli/blob/master/lib/broccoli/ember-app.js#L1206) and [here](https://github.com/ember-cli/ember-cli/blob/master/lib/broccoli/ember-app.js#L1344).

I haven't run the tests but removing [this merge](https://github.com/ember-cli/ember-cli/blob/master/lib/broccoli/ember-app.js#L1342-L1348) seemed to "just work" (tested with the app locally).

needs a proper bugfix though, created to start tracking.

### PR DESCRIPTION
**Pull request by twokul**
Fixes #7222

### CODE REVIEW

**Comment by twokul** [comment]
`node@4` only fails on Appveyor; failure seems unrelated to the code change.

**Comment by rwjblue** [comment]
Can you link where `appJs` gets the processed ember-cli tree the other time?

**Comment by twokul** [comment]
we push `emberCLITree` to `sourceTrees` inside `appAndDependecies()` [here](https://github.com/ember-cli/ember-cli/blob/master/lib/broccoli/ember-app.js#L1206). And then push `emberCLITree` again inside `javascript()` call [here](https://github.com/ember-cli/ember-cli/blob/master/lib/broccoli/ember-app.js#L1344).

@rwjblue does that answer your question?

**Comment by stefanpenner** [comment]
@twokul thanks for digging into this, and providing the links. I reviewed, and I agree this is redundant step (and likely a pretty costly one).

Here is my analysis, let me know if this is also what you saw:

1. `appAndDependencies` includes `emberCLITree` https://github.com/ember-cli/ember-cli/blob/master/lib/broccoli/ember-app.js#L1206-L1218
2. `appAndDependencies` is only invoked from `javascript()`: https://github.com/ember-cli/ember-cli/blob/master/lib/broccoli/ember-app.js#L1333
3. the `CLITree` is then merged with `appJs` https://github.com/ember-cli/ember-cli/blob/master/lib/broccoli/ember-app.js#L1344
4. this merge is redundant since, the CLITree is already included (last tree to be merged) in the `appjs` tree

We are essentially doing:

```js
merge([merge([..., cliTree]), cliTree]);
```

Which is equivalent to:

```js
merge([..., cliTree]);
```

And interestingly, I suspect this may actually be buggy for users who don't have `ember-cli-babel` installed (super rare, and for old setups.. but possible). As they will clobber a module compiled cliTree with one that is not... https://github.com/ember-cli/ember-cli/blob/master/lib/broccoli/ember-app.js#L1338

**Comment by stefanpenner** [comment]
I feel good about this one (would like @rwjblue to also sign-off). We should now decide if this should ride the canary train, or land as a `[BUGFIX beta]`. I would vote `[BUGFIX beta]` if @twokul can try it out in some non-trivial apps, and make sure everything seems ok.

**Comment by twokul** [comment]
@stefanpenner your analysis is correct, this is exactly what's happening :P thanks much for looking at it!

I tried it with one of the internal LinkedIn apps and it did work fine. I can tag this commit as `[BUGFIX beta]` and we could ship unless good Sir @rwjblue has concerns/other suggestions.

**Comment by stefanpenner** [comment]
Chatted with @rwjblue, he's good with this.

**Comment by stefanpenner** [comment]
Ah this also needs to be submitted to beta branch, @twokul mind doing that?

**Comment by twokul** [comment]
@stefanpenner absolutely

**Pull request merged**
