### PR TITLE
hot-fix tomster ` -> ., prevents breaking the initial git commit

### PR DESCRIPTION
**Pull request by stefanpenner**

### CODE REVIEW

**Comment by cibernox** [comment]
This bug is just billiant :grin:

**Comment by najamm** [comment]
i got ember-cli 0.1.11 yesterday and I'm still seeing the issue of slice of null, i even cleaned out npm and bower cache on machine.

i had to modify the package.json that gets generated by the "ember new" command

from

"ember-cli-app-version": "0.3.0"

to 

"ember-cli-app-version": "0.3.1" // fixed version

**Comment by cibernox** [comment]
I fixed the bug, but maybe it deserves a new release of ember-cli

**Comment by najamm** [comment]
Yes, i noticed the bug is fixed and they did release 0.1.11 with that bug fix. 

I just checked my npm-cache and npm_modules for the "C:\Users\username\AppData\Roaming\npm\node_modules\ember-cli\blueprints\app\files\package.json"

and they are still pointing to 0.3.0 version, maybe the npm repo is not updated?

**Comment by rwjblue** [comment]
@cibernox - Yes, we are planning on releasing tonight/tomorrow.

**Comment by najamm** [comment]
Ok, great, thanks. I saw that 0.1.11 was in the release section in GIT so i assumed it was officially released to public. Glad to know i wasn't doing anything wrong on my side.

Thanks all for the hard work!

**Pull request merged**
