### PR TITLE
Native deps now gone

### LINKED ISSUE #3857: Ember-cli install fails with build errors
Versions:
  windows 7
  node 0.12.2
  npm 2.7.4

I am new to node and npm, just trying to get started with ember, and I am stuck at the very first step.   Plz help, what am I doing wrong? "npm install -g ember-cli" has the following results:

> ws@0.5.0 install C:\Users\mjeghers\AppData\Roaming\npm\node_modules\ember-cli\node_modules\testem\node_modules\socket.io\node_modules\engine.io\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

[edit] full stack -> https://gist.github.com/stefanpenner/f8fdabb80328b7c07c85

### LINKED ISSUE #3993: testem introduces a non-optional native extension
https://github.com/Automattic/socket.io/issues/2107

TL;DR we need socket.io to release a new version that whos dependencies ultimately have an optional dependency on node-gyp of `bufferutil`

- [x] update socket.io
- [x] update engine.io
- [x] update testem
- [x] our use of npm.install must be `no-optional=false`

### PR DESCRIPTION
**Pull request by stefanpenner**
- [fixes #3993]
- [fixes #3857]

### CODE REVIEW

**Comment by stefanpenner** [comment]
@johanneswuerbach looks like our upgrade to testem 0.9 has some hickups, i'll try to look why in the next 24 hours. But maybe something jumps out at you?

**Comment by chadhietala** [comment]
Travis does not agree.

**Comment by stefanpenner** [comment]
> Travis does not agree.

yup, as noted in the above comment. Some testem related adjustments are needed.

**Comment by johanneswuerbach** [comment]
@stefanpenner thanks, I'm afk over the weekend and planning to release testem 0.9 stable early next week.

The socket.io patch itself shouldn't require 0.9 as the latest 0.8 release already allows 1.3.6 https://github.com/airportyh/testem/blob/2333cb6d02c0d7f98296a6dc02e8f4bedd9acf60/package.json#L43

**Comment by stefanpenner** [comment]
> The socket.io patch itself shouldn't require 0.9 as the latest 0.8 release already allows 1.3.6 https://github.com/airportyh/testem/blob/2333cb6d02c0d7f98296a6dc02e8f4bedd9acf60/package.json#L43

perfect, easy rollback them :)

**Comment by stefanpenner** [comment]
@johanneswuerbach i believe all we will need to do on our end is release a new ember-cli with the slightly adjusted package / bundle step. I expect to cut tomorrow unless issues arise.

**Pull request merged**
