### PR TITLE
Fix addon smoke test on Windows

### PR DESCRIPTION
**Pull request by Turbo87**
or at least I hope this is fixing it...

### CODE REVIEW

**Comment by Turbo87** [comment]
well, looks like that approach didn't work...

**Comment by Turbo87** [comment]
@stefanpenner I've disabled the test on Windows for now. Not ideal but certainly better than the current situation. 

r?

**Comment by trabus** [comment]
Nice work tracking this down!

**Comment by stefanpenner** [comment]
@homu r+

@Turbo87 goodjob

**Comment by nathanhammond** [comment]
@Turbo87 Needs a rebase.

**Comment by Turbo87** [comment]
@nathanhammond done

@homu retry

**Comment by nathanhammond** [comment]
@homu r+

**Pull request merged**
