### PR TITLE
[ENHANCEMENT] Add in-repo-addon generate and destroy support

### PR DESCRIPTION
**Pull request by trabus**
This PR adds the ability to generate and destroy blueprints inside of in-repo-addons by adding a `--in-repo-addon` flag to the generate and destroy commands. It also adds support for components as the first blueprint to be able to generate inside an in-repo-addon.

`ember generate component foo-bar --in-repo-addon my-addon`
or using shorthand:
`ember g component foo-bar -in-repo my-addon` 

This needs some follow up with docs, it would be helpful to know that you can generate blueprints inside in-repo-addons.

### CODE REVIEW

**Comment by stefanpenner** [comment]
LGTM, my only comment is: it makes me slightly un-easy to add many if statements to add this sort of functionality. It would be great if a later refactoring utilized polymorphism instead.

**Comment by trabus** [comment]
@stefanpenner [This is what structures would provide](https://github.com/trabus/rfcs/blob/e68c778593b8ad924893cf9e8d6f730b250451bf/active/0000-structures.md#rough-concept)

**Comment by stefanpenner** [comment]
> @stefanpenner This is what structures would provide

:+1:

**Comment by stefanpenner** [comment]
kicking appveyor.

**Comment by noslouch** [comment]
I think this caused a regression to #2329. I'm seeing vim swap and undo history files get swept up in the build process.

**Pull request merged**
