### PR TITLE
[BUGFIX] - fix reference for `ui.prompt`

### PR DESCRIPTION
**Pull request by tgandee79**
Fixes an issue I just added: [issues/6187](https://github.com/ember-cli/ember-cli/issues/6187)

### CODE REVIEW

**Comment by rwjblue** [comment]
Seems good to me.

**Comment by tgandee79** [comment]
Looks like it's trailing spaces that are failing.  Fixing now.

**Comment by tgandee79** [comment]
Is this my problem?  I don't know how I can fix this test.

image

**Comment by nathanhammond** [comment]
@homu r+

**Comment by nathanhammond** [comment]
@tgandee79 Thank you for your attention to detail!

**Comment by tgandee79** [comment]
I'll look for more doc issues.  About to write a blog post on using the `this.ui.prompt` while creating a blueprint.

**Pull request merged**
