### PR TITLE
[1.X] Deprecate vendor-prefix and vendor-suffix.

### PR DESCRIPTION
**Pull request by nathanhammond**
These hooks make it easy to do bad things inside of ember-cli. Deprecating them to make the world a better place.

Don't merge yet, need to come up with a solution for https://github.com/rwjblue/ember-disable-prototype-extensions first.

### CODE REVIEW

**Comment by stefanpenner** [comment]
:+1:

**Comment by rwjblue** [comment]
LOL. I guess I have to review all PR's before asking for more back porting ;)

**Comment by nathanhammond** [comment]
Landable if we bump the version of https://github.com/rwjblue/ember-disable-prototype-extensions

**Comment by rwjblue** [comment]
```
% npm publish
+ ember-disable-prototype-extensions@1.1.0
```

**Comment by nathanhammond** [comment]
:shipit: if you wish.

**Comment by nathanhammond** [comment]
Can we restart travis-ci and appveyor? This should pass.

**Comment by stefanpenner** [comment]
@nathanhammond gave them a kick :)

**Comment by stefanpenner** [comment]
@homu r+

**Pull request merged**
