### PR TITLE
Remove extra input tree filtering.

### PR DESCRIPTION
**Pull request by rwjblue**
Tested in Stress App and while there is not a huge performance improvement here, less work/steps is definitely better.

Stress App timings: https://gist.github.com/rwjblue/dd8b0af2c55b5d9cb803

### CODE REVIEW

**Comment by stefanpenner** [comment]
this appears to break pod templates: specifically  -> https://github.com/ember-cli/ember-cli/blob/master/tests/acceptance/brocfile-smoke-test-slow.js#L74-L82

**Comment by stefanpenner** [comment]
needs rebase

**Comment by stefanpenner** [comment]
@rwjblue ping

**Comment by stefanpenner** [comment]
@rwjblue ping

**Comment by Turbo87** [comment]
@rwjblue can this PR be closed or is it still relevant?

**Comment by stefanpenner** [comment]
@rwjblue did this land, or deferring it for now.

**Comment by rwjblue** [comment]
Deferring for now, too many open fronts and this will be more work to rebase and pick up the pieces than just do it over again.

**Comment by stefanpenner** [comment]
@rwjblue sg

**Pull request closed without merging**
