### PR TITLE
Add assertion to make sure tests file is included when running tests

### PR DESCRIPTION
**Pull request by trentmwillis**

### CODE REVIEW

**Comment by rwjblue** [comment]
This looks good and should help folks quite a bit while upgrading. Can you tweak it to actually load the tests also?

**Comment by trentmwillis** [comment]
@rwjblue sure, via `$.getScript`? Do you think it would be worthwhile concatenating this stuff into `test-loader.js` instead of via `content-for`?

**Comment by stefanpenner** [comment]
@rwjblue I am inclined (5/10) to just fail with a good error, if you feel strongly i'll gladly swing in in-favor of  your suggestion

**Comment by rwjblue** [comment]
I don't care a ton, some messaging (as is added here) is massively better than none.  This particular gotcha has tripped me up while upgrading a few apps to master.  An error like the one added here would have let me fix it instantly...

**Comment by stefanpenner** [comment]
> An error like the one added here would have let me fix it instantly...

:+1: 

im good with this then, @rwjblue r?

**Comment by rwjblue** [comment]
@homu r+

**Pull request merged**
