### PR TITLE
Overhaul website

### PR DESCRIPTION
**Pull request by chnn**
Hello,

The goal of this PR is to improve the clarity of the website. To do this I have:

- Split the website up into sections
- Redesigned portions of the website

You can view the site here: ~~http://ember-cli-docs.divshot.io/~~ http://chnn.github.io/ember-cli/

As it stands right now, the documentation reads like one very long README. This means that the docs for a first-time user who needs an introduction and the docs for an experienced user remembering an obscure addon hook are lumped together in one place. By splitting the docs into sections we can better treat each audience in isolation. Eventually I hope that this change will let us improve the “narrative” of each section to make reading the docs more effective and enjoyable.

I see this as a _work in progress_—if people generally see this as an improvement over the existing site I'll do whatever is needed to get it to completion. I did my best to separate the existing docs out into sections, but there is likely a better way to do it then I have done. I know there's some people out there with strong opinions on how docs should be, it would be great to hear from them.

#### Still todo

- Integrate GA code
- Is the logo I created fair use of Ember's logo? (or even wanted? any designers out there?)
- Ensure works in IE
- Better copy for the landing page (“command line interface for building ambitious web applications” is fairly vague)
- Need a favicon.ico

### CODE REVIEW

**Comment by stefanpenner** [comment]
@joostdevries @chnn @jonharmon you fine gentlemen available this week or this weekend to circle up on this? Lets get the ball rolling again.

**Comment by chnn** [comment]
Busy in general, but after 9 PM pacific this week or anytime this weekend I can find some time.

**Comment by stefanpenner** [comment]
> Busy in general, but after 9 PM pacific this week or anytime this weekend I can find some time. Excited for this, especially integration withe API docs.

i would love for @joostdevries to attend, so lets aim for this saturday afternoon 1pm EST. Does that work?

**Comment by chnn** [comment]
Works great for me.

**Comment by stefanpenner** [comment]
email me at stefan.penner@gmail.com for those that are interested in joining the hangout

**Comment by joostdevries** [comment]
works for me!

**Comment by zeppelin** [comment]
@stefanpenner are you recording the session? I can't make it on saturday, but I'm extremely interested about the conversation.

**Comment by jonharmon** [comment]
1pm Saturday works for me.

**Comment by stefanpenner** [comment]
@jonharmon / @chnn did u get an invite?

**Comment by chnn** [comment]
Nope just sent one more email to you.

**Comment by jonharmon** [comment]
yep got the invite

**Comment by stefanpenner** [comment]
FYI: https://github.com/emberjs/website/pull/1956

**Comment by joostdevries** [comment]
Next steps from the hangout: The idea is to work on the next version in [ember-cli/website](https://github.com/ember-cli/website) and publish it to next.ember-cli.com. @jonharmon @chnn are you available for a 15-30m hangout anywhere this week between 11am-3pm EST?

My initial questions:
- Starting point (initial commit on master): Current `gh-pages`, @chnn's version or blank repo.
- Build tool: Jekyll, Rake, Grunt, Ember?
- Deploy: Ember uses emberjs/emberjs.github.io for their deploys and emberjs/website for the src. I like this because it eliminates the need for external hosting. I'm a little scared it will break the current site though. Any ideas?

@stefanpenner additions/comments?

**Comment by chnn** [comment]
@joostdevries Anytime after 12 EST on Tuesday or Thursday works for me. Also flexible other days if that works better for others.

Let's continue this discussion on the website repo. I created an issue here: https://github.com/ember-cli/website/issues/1

I've got some ideas on your questions and few of my own, but we can leave that for the hangout.

**Comment by stefanpenner** [comment]
> @stefanpenner additions/comments?

no sounds great, thank you for being mindful of not breaking the current site.

**Comment by tomdale** [comment]
If there is going to be significant work to overhaul the website, including from scratch from a new repo, can we focus those efforts on integrating the Ember CLI docs into the primary Ember website?

**Comment by joostdevries** [comment]
@tomdale Are you talking about the complete scope of the current Ember CLI site?

**Comment by jonharmon** [comment]
@joostdevries @chnn I'm available any day this week during 11am-3pm 
EST.  Although @tomdale's inquiry leaves the agenda in question.

@tomdale @stefanpanner Should we switch gears and focus on integration 
into emberjs.com instead?

> Chris Henn <mailto:notifications@github.com>
> Monday, January 26, 2015 3:54 PM
>
> @joostdevries <https://github.com/joostdevries> Anytime after 12 EST 
> on Tuesday or Thursday works for me. Also flexible other days if that 
> works better for others.
>
> Let's continue this discussion on the website repo. I created an issue 
> here: ember-cli/website#1 <https://github.com/ember-cli/website/issues/1>
>
> I've got some ideas on your questions and few of my own, but we can 
> leave that for the hangout.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/ember-cli/ember-cli/pull/2589#issuecomment-71536097>.
>

-- 
Jon Harmon
Web Developer

574.214.5162
jonharmondesign.com
<http://www.getpostbox.com>

**Comment by joostdevries** [comment]
@chnn @jonharmon would Wed. 1pm EST work? tue+thursday are a little tricy for me..

**Comment by stefanpenner** [comment]
> @tomdale @stefanpanner Should we switch gears and focus on integration
> into emberjs.com instead?

My only concern with emberjs.com is the potential scope of that project, and the availability of individuals like yourself to work on it. If we can give our users are great experience, perfect. If this means we are many months away from improving our current experience, I don't feel good about it.

**Comment by stefanpenner** [comment]
If we are going to move this effort to emberjs.com, we should start at the home-page, and incrementally push the work throughout the site. This will allow us to get the best bang for our buck, and move forward.

Another concern though, is that ember-cli is not at the same stability level at ember.js core, we have not yet reached 1.0, and as such are very prone to breakage. This must be taken into account when deciding the marketing push.

Several upcoming likely breaking changes:

* configuration story
* broccoli 1.0
* add-on story improvements

**Comment by joostdevries** [comment]
@chnn @jonharmon I could make today 1pm est too.

**Comment by chnn** [comment]
@joostdevries @jonharmon 1pm EST Wednesday works for me.

**Comment by chnn** [comment]
@joostdevries @jonharmon and I have decided to take a content first approach to next.ember-cli.com instead of continuing from this PR. Our basic plan is to try and get the content and structure of the docs correct, and then from there develop a site that best communicates the content. Eventually some of the docs, but not all, will be better off on emberjs.com, but for now ember-cli doesn't have the API stability to make the Ember website a feasible starting point. Hopefully we can structure the content in such a way that migrating docs could be easy. 

We'll be working in the ember-cli/website repository.

/cc @stefanpenner

**Comment by stefanpenner** [comment]
@chnn awesome, thank you for the update :)

**Comment by tomdale** [comment]
@chnn Can you say more about which parts of the docs will/won't be appropriate for emberjs.com? I think the plan is to go full in on Ember CLI for the docs for the main site, so I'd like to make sure we're all on the same page and not duplication effort. The point about stability is a good one but one we just need to live with, I think.

**Comment by chnn** [comment]
@tomdale Ah ok I was under the impression that moving the CLI docs to the Ember site would happen in the distant future. If you think we are close to a point where that can happen sooner, I would absolutely love to focus on that instead. 

I know there's a lot of moving parts to the Ember website (versioned API docs, written but not published portions of the guide using Ember CLI...) Do you have any insight as to when/how the Ember CLI docs can be merged?

**Comment by joostdevries** [comment]
@chnn I think it's best to first do an iteration on the content/sitemap from a first-time Ember (CLI) user perspective and based on that see whether it's sensible to start moving stuff to emberjs.com and what the additional effort would be. Once we have got the outline of the content it should be pretty clear whether combining efforts would make sense.

@tomdale Do you have an idea on how emberjs.com would look once this stuff gets merged into it? Specifically how to deal with globals-mode users (right now a majority I think)?

**Comment by tomdale** [comment]
Our plan is to migrate the entirety of the guides over to assuming Ember CLI, an effort @bsclifton is heading up. We will also include a guide for globals users on how to translate Ember CLI examples to globals.

You guys are, of course, free to proceed as you'd like… but given we've got what seems to be a similar effort going on in parallel, I'd at least like to make sure we're all on the same page to avoid the pain of merging the content later, which usually means either throwing away one set of work, or disjointed narrative if they're poorly integrated.

**Comment by bsclifton** [comment]
Wow; definitely nice work @chnn! :smile: 

I've personally taken an approach of gradually improving the emberjs.com site.  I don't think the site needs all of the details up front. Since so many things are in flux, for example server side rendering, I think taking a slower iterative approach makes sense

From my experience, the docs on ember-cli.com are definitely lower level (more technical), compared to what's in the "Guides" section of emberjs.com.  Some of the work we're doing for a new "Getting started" experience will definitely overlap with Ember CLI.  Maybe you can join us?

**Pull request closed without merging**
