### PR TITLE
proxy requires hash based routing

### PR DESCRIPTION
**Pull request by baijum**
I am not sure whether changing the documentation or setting the default `locationType` to `hash` is better.

### CODE REVIEW

**Comment by rwjblue** [comment]
You should sill be able to use auto or history location with proxying. 

If you cannot, it is a bug.

**Comment by baijum** [comment]
The proxy is not working here without changing the `locationType` value from `auto` to `hash`. Do you want me to report this issue and close this pull request ?

**Comment by stefanpenner** [comment]
Are you proxying / ?  If so its working as expected.  Typically we proxy only sub paths like Api/*

**Comment by baijum** [comment]
When I give the value as `hash` and `none` the the proxy works. But if I give the value as `history` or `auto` (tested from Chrome 40+ browser) it doesn't work.

**Pull request closed without merging**
