### PR TITLE
bump portfinder to v1.0.7

### LINKED ISSUE #6083: `ember s` fails with `EADDRNOTAVAIL` after updating to `port-finder@1.0.4`

### PR DESCRIPTION
**Pull request by eriktrom**
Will push upstream dep `portfinder@1.0.7` once we receive consensus from the crowd that this works on all machines. This PR is for book keeping.

See https://github.com/ember-cli/ember-cli/issues/6083 to help out with the testing process. It should only take a minute of your time. :)

fixes #6083

### CODE REVIEW

**Comment by eriktrom** [comment]
@stefanpenner - ready to go when ci passes (although this is just book keeping, so merge at will)

**Comment by stefanpenner** [comment]
@homu r+

**Comment by Turbo87** [comment]
@stefanpenner @nathanhammond FYI https://github.com/indexzero/node-portfinder/blob/master/package.json#L32

**Comment by stefanpenner** [comment]
@Turbo87 hmmm, thanks for pointing that point. @eriktrom is that a hard dependency on node >= 0.10 ?

**Comment by eriktrom** [comment]
@stefanpenner - sorry whats the concern? Does portfinder only work w/ node >= 0.12? It should work with 0.10, I believe I bumped that at some point for travis, but the way the code is written now should work with 0.10 unless we're seeing issues in the wild where this is not the case

**Comment by Turbo87** [comment]
@eriktrom the only issue I noticed so far is that NPM prints a compatibility warning during install when used with Node 0.10. if the package works with Node 0.10 then everything is fine.

**Comment by eriktrom** [comment]
@Turbo87 - gotcha - yes it'll print warnings but should work just fine AFAIK

**Comment by eriktrom** [comment]
I can change that to 0.10 if we think that's ideal - let me know, no biggie

**Pull request merged**
