### PR TITLE
Implement application level resolver in blueprint.

### LINKED ISSUE #5368: resolver in app + tests should come from same location
1. add `app/resolver.js` which by default `export { default } from 'ember-resolver';`
2. in `app.js` -> `import resolver from './resolver';`
3. in [tests/helpers/resolver.js](https://github.com/ember-cli/ember-cli/blob/master/blueprints/app/files/tests/helpers/resolver.js) we should import `<app-name>/resolver`

----

obviously needs deprecation phase etc.

### PR DESCRIPTION
**Pull request by rwjblue**
Closes #5368.

### CODE REVIEW

**Comment by rwjblue** [comment]
#5368 discusses a deprecation phase, but I'm not sure that is needed here. New apps would be generated with the correct content, any properly upgraded apps will be updated to the new content, and any apps that do not update content will continue to work.

**Comment by stefanpenner** [comment]
Ya. I can go either way, i figured the deprecation would be nice to quickly get everyone on-board, but meh.

**Comment by stefanpenner** [comment]
@homu r+

**Comment by rwjblue** [comment]
Wat, says it passed and merged but no merge :(

**Pull request merged**
