### PR TITLE
Update ember-data to 1.13.5

### PR DESCRIPTION
**Pull request by trabus**
:facepunch:

### CODE REVIEW

**Comment by stefanpenner** [comment]
woohoo

**Comment by trabus** [comment]
I'm not sure what is going on with appveyor, but can we go ahead and merge this?

**Comment by stefanpenner** [comment]
i think we are just behind this job: https://ci.appveyor.com/project/embercli/data/build/2128

This PR should really not matter for windows users, as it is basically JS only. I would like to be sure we circle back if problems arise though.

**Comment by trabus** [comment]
Absolutely. I'm going to be rebasing the changelog after this is merged, so it will be tested. I just want to kick it off before I start my commute. :)

**Pull request merged**
