### PR TITLE
lint js for node@4 compatibility

### PR DESCRIPTION
**Pull request by ro0gr**
It should help contributors to detect issues locally in the editor instead of [CI](https://travis-ci.org/ember-cli/ember-cli/jobs/334482664#L521)

### CODE REVIEW

**Comment by kellyselden** [comment]
Looks like it needs more configuration.

**Comment by ro0gr** [comment]
I believe all `node/no-unpublished-require` errors detected in the `tests/**/*/test.js`
> tests/unit/tasks/test-test.js
>    3:24  error  "chai" is not published  node/no-unpublished-require 

is a failure of `node/no-unpublished-require` rule. 
According to the [rule documentation](https://github.com/mysticatea/eslint-plugin-node/blob/master/docs/rules/no-unpublished-require.md#rule-details)
> If a source code file satisfies all of the following conditions, the file is *published*.
>
> - "files" field of package.json includes the file or "files" field of package.json does not exist.
> - .npmignore does not include the file.

npm-ignored files should not be linted against this rule. I'll try to figure it out.

By the way we also have few potentially useful errors for code located in the `lib/` and `tests/helpers/` directories.

**Comment by ro0gr** [comment]
I believe all the "no-extraneous-require" errors are false negative (https://github.com/mysticatea/eslint-plugin-node/issues/107)

**Comment by ro0gr** [comment]
@kellyselden @rwjblue I think it's ready to go!

**Comment by rwjblue** [comment]
Thank you @ro0gr!

**Pull request merged**
