### PR TITLE
[BETA] Remove templates/components folder from app blueprint

### PR DESCRIPTION
**Pull request by Panman82**
Not needed with component co-location since component templates are located in the components folder now.

### CODE REVIEW

**Comment by kellyselden** [comment]
makes sense. I think you'll want to target beta instead of master.

**Comment by Panman8201** [comment]
@kellyselden humm.... like that? Seems like there are extra commit messages showing up now, because 🤷‍♂

**Comment by rwjblue** [comment]
@Panman8201 - No worries, I rebased and fixed up the commits here in this branch.

**Comment by rwjblue** [comment]
Restarted CI job...

**Comment by rwjblue** [comment]
I'm sorry @Panman82, looks like we accidentally merged a similar PR into the beta branch in https://github.com/ember-cli/ember-cli/pull/8963. Sorry about that, and thank you for working on this!

**Pull request closed without merging**
