### PR TITLE
Replace deprecated `babel-eslint` with `@babel/eslint-parser`

### LINKED ISSUE #9307: Replace deprecated babel-eslint with new @babel/eslint-parser
This is mostly a tracking issue as I am not in a place to open a PR for this atm, but,

here in the app blueprint: https://github.com/ember-cli/ember-cli/blob/master/blueprints/app/files/package.json#L29
we're still using babel-eslint,
but, per, https://github.com/babel/babel-eslint, the eslint parser for babel has moved into their monorepo as https://github.com/babel/babel/tree/master/eslint/babel-eslint-parser

### PR DESCRIPTION
**Pull request by bmish**
Fixes #9307.

Old: https://www.npmjs.com/package/babel-eslint
New: https://www.npmjs.com/package/@babel/eslint-parser

Note: `@babel/eslint-parser requires @babel/core@>=7.2.0` (which is already a transitive dependency through ember-cli-babel among other dependencies)

### CODE REVIEW

**Comment by rwjblue** [comment]
I think we might need an RFC for this. It changes some fundamentals of how folks think about things, and would probably benefit from more 👀 of addon / app authors.

What do you think?

**Comment by bmish** [comment]
@rwjblue you're probably right. Not sure when I would have time to get around to that though.

**Comment by rwjblue** [comment]
Merged master to get an updated CI run going...

**Comment by rwwagner90** [comment]
@bmish I tried this in my addon and it seems to break imports https://github.com/shipshapecode/ember-flatpickr/pull/982 any ideas?

**Comment by rwwagner90** [comment]
I'm also getting a lot of stuff like:

```
          TypeError: Cannot read properties of undefined (reading 'extend')
                at Object.initialize (http://localhost:7357/assets/vendor.js:114708:62)
                at http://localhost:7357/assets/vendor.js:31772:21
                at Vertices.each (http://localhost:7357/assets/vendor.js:54254:9)
                at Vertices.walk (http://localhost:7357/assets/vendor.js:54168:12)
                at DAG.each (http://localhost:7357/assets/vendor.js:54098:22)
                at DAG.topsort (http://localhost:7357/assets/vendor.js:54106:12)
                at App._runInitializer (http://localhost:7357/assets/vendor.js:31799:13)
                at App.runInitializers (http://localhost:7357/assets/vendor.js:31770:12)
                at App._bootSync (http://localhost:7357/assets/vendor.js:29752:14)
                at App.boot (http://localhost:7357/assets/vendor.js:29719:14)
                ```
                
I have no idea what that is about though.

**Comment by bertdeblock** [comment]
Opened https://github.com/emberjs/rfcs/issues/817 to hopefully get the ball rolling on this one.

**Pull request closed without merging**
