### PR TITLE
Update "release" branch

### PR DESCRIPTION
**Pull request by Turbo87**
see https://github.com/ember-cli/ember-cli/pull/5867

/cc @rwjblue

### CODE REVIEW

**Comment by Turbo87** [comment]
Travis failure seems to be related to the Node 5 to 6 bump

**Comment by rwjblue** [comment]
Ya, I guess we should lock release branch down to `"5"` (instead of `"node"`).

**Comment by rwjblue** [comment]
Most likely https://github.com/ember-cli/ember-cli/pull/5855 is the issue (that was the main issue when we bumped to 6 in master).

**Comment by Turbo87** [comment]
@rwjblue @nathanhammond @stefanpenner can we get this merged and released? ember-data is currently somewhat broken with ember-cli@2.5.0

**Comment by rwjblue** [comment]
Can you cherry-pick the fix from #5855 and/or disable CI for node 6?  I'd rather not merge with failing CI...

**Comment by Turbo87** [comment]
@rwjblue done

**Pull request merged**
