### PR TITLE
Update "ember-cli-htmlbars"

### PR DESCRIPTION
**Pull request by stefanpenner**

### CODE REVIEW

**Comment by Turbo87** [comment]
@stefanpenner why is this targeted at `release`? what bug is it fixing?

**Comment by stefanpenner** [comment]
I believe it may address: https://github.com/emberjs/data/pull/4947 

I can target beta instead... would love your and @rwjblue's opinion.

**Comment by rwjblue** [comment]
Beta seems ok, but ultimately the ember data issue is resolved with an update in ember-data itself.

**Comment by stefanpenner** [comment]
updated to beta

**Comment by stefanpenner** [comment]
after chatting with @rwjblue we should do this a release, as addons testing blueprints will be affected.

**Comment by Turbo87** [comment]
@stefanpenner it's still not clear to me what problem this is solving. can you elaborate on that?

**Comment by stefanpenner** [comment]
@Turbo87 https://github.com/ember-cli/ember-cli-htmlbars/pull/110 causes issues for addons testing blueprints. Ember-data ran into it.

If we upgrade ^ this goes away, We may also want to revert that PR. I can't remember what @rwjblue and me decided.. maybe he can refresh my memory.

**Comment by stefanpenner** [comment]
@rwjblue apparently already reverted the ember-cli-htmlbars stuff. I'll switch this back to beta.

**Comment by Turbo87** [comment]
https://github.com/ember-cli/ember-cli-htmlbars/pull/110 is already included in v1.3.2 though, so not necessarily a need for the major bump 🤔

**Pull request merged**
