### PR TITLE
Addon#setupPreprocessorRegistry should be invoked after `addon.app` is set.

### PR DESCRIPTION
**Pull request by stefanpenner**
- [x] get feedback re: if this is reasonable (cc @rwjblue) 
- [x] tests (more comprehensive life-cycle tests)

### CODE REVIEW

**Comment by stefanpenner** [comment]
The more I look at this, the more reasonable it seems. For example, it is strange to add addons to the registry, that later are not even included.

**Comment by stefanpenner** [comment]
Ya, so this ordering is depended on -> https://github.com/ember-cli/ember-cli-htmlbars-inline-precompile/blob/master/index.js#L71

But I believe we can at-least make `app` available before we call setupRegistry rather then after.

**Comment by Turbo87** [comment]
@stefanpenner I'm not entirely following yet. what advantage does this create?

**Comment by stefanpenner** [comment]
@Turbo87 I'll write a test, that makes this more obvious but TL;DR `addon.setupPreprocessorRegistry` is invoked before `addon.app` is set, this means if you need access to `addon.app.config` for your registry setup your are out of luck today.

**Comment by stefanpenner** [comment]
fixed linting error.

**Comment by stefanpenner** [comment]
will change this to bugfix beta.

**Comment by rwjblue** [comment]
Updated to point to `beta`, and rebased.

**Comment by Turbo87** [comment]
thanks to https://github.com/simplabs/ember-test-selectors/issues/116 I finally understand what this PR is doing... LGTM 👍

**Comment by rwjblue** [comment]
Merging manually (changing targets makes @homu emo).

**Comment by Turbo87** [comment]
@stefanpenner it looks like the implementation here is somewhat flawed. for app builds this seems to work, but when building addons `setupPreprocessorRegistry()` is apparently called before the `EmberApp/Addon` class is even instantiated.

I'm trying to fix https://github.com/simplabs/ember-test-selectors/issues/345 but it seems almost impossible at this point. If you or @rwjblue have 30min to pair with me on this next week that would be awesome!

**Pull request merged**
