### PR TITLE
Do not default to development asset

### PR DESCRIPTION
**Pull request by martndemus**
I removed default to development asset, this is not consistent with `app.import(null)`.
See #3215

### CODE REVIEW

**Comment by stefanpenner** [comment]
this should like to and `in` check instead

**Comment by martndemus** [comment]
Rebases, will add suggested check.

**Comment by martndemus** [comment]
Added an update, which use in to check if current env is set.

(5 blueprint related tests fail, these also fail if I roll back to before my patches.)

**Comment by rwjblue** [comment]
@martndemus - Thank you!

**Comment by martndemus** [comment]
@rwjblue NP, this is way better than having to use an empty file.

**Pull request merged**
