### PR TITLE
Update bundled npm version.

### LINKED ISSUE #5720: Update "npm" to v2.15.1
It might make sense to update our bundled `npm` dependency to v2.15.1 after http://blog.npmjs.org/post/142036323955/fixing-a-bearer-token-vulnerability came out yesterday

### PR DESCRIPTION
**Pull request by nathanhammond**
Closes #5720. Untested, wait for Travis/AppVeyor.

### CODE REVIEW

**Comment by rwjblue** [comment]
I believe this is the same as https://github.com/ember-cli/ember-cli/pull/5677, and that @chadhietala was working on some of the failures there yesterday.

**Comment by rwjblue** [comment]
Derp. Never mind. This updates to latest 2.x, #5677 updates to 3.x.

**Comment by nathanhammond** [comment]
@rwjblue Yep, incremental because of upstream issues. Hopefully this plays nicely...

**Comment by nathanhammond** [comment]
AppVeyor has passed on 4.2, if I see it pass on 5 I'm invoking lottery rules.

**Comment by chadhietala** [comment]
:slot_machine:

**Comment by nathanhammond** [comment]
@homu r+

**Pull request merged**
