### PR TITLE
[FIXES #6927] [BUGFIX beta] ensure addon.css is always included

### LINKED ISSUE #6927: Failure to load vendor.css with Ember 2.13.0-beta
We attempted to upgrade the html-next/flexi addon to the 2.13 beta but the dummy app is no longer generating CSS. This issue does not occur in 2.12.

Chrome developer tools reports: `Failed to load resource: the server responded with a status of 404 (Not Found) vendor.css`

To reproduce the bug, checkout [the flexi repo](https://github.com/html-next/flexi) and attempt to visit the dummy site.

---

Output from `ember version --verbose && npm --version`:
```
ember-cli: 2.13.0-beta.2
http_parser: 2.7.0
node: 7.2.0
v8: 5.4.500.43
uv: 1.10.1
zlib: 1.2.8
ares: 1.10.1-DEV
modules: 51
openssl: 1.0.2j
icu: 58.1
unicode: 9.0
cldr: 30.0.2
tz: 2016g
os: darwin x64
3.10.9
```

### PR DESCRIPTION
**Pull request by stefanpenner**
- [x] manually confirmed
- [x] needs test

### CODE REVIEW

**Comment by rwjblue** [comment]
:+1:

**Comment by stefanpenner** [comment]
@rwjblue ready for your 👀

**Comment by rwjblue** [comment]
Changes look good, can you change this PR to target beta and rebase (we follow a different system here than in Ember)?

**Comment by stefanpenner** [comment]
@rwjblue done, pending CI.

**Comment by Turbo87** [comment]
@stefanpenner thanks!

**Pull request merged**
