### PR TITLE
Rebased https://github.com/ember-cli/ember-cli/pull/3344

### PR DESCRIPTION
**Pull request by tim-evans**
See https://github.com/ember-cli/ember-cli/pull/3344 for the thread on this.

### CODE REVIEW

**Comment by tim-evans** [comment]
Not sure why this error is happening:

```
  1) models/addon.js treeForStyles should move files in the root of the addons app/styles tree into the app/styles path:
     TypeError: Cannot read property '_watchmanInfo' of undefined
      at Class.Addon.treeGenerator (lib/models/addon.js:9:10263)
      at Class._treeFor (lib/models/addon.js:9:12263)
      at Class.treeFor (lib/models/addon.js:9:11025)
      at Context.<anonymous> (tests/unit/models/addon-test.js:580:44)
```

Any ideas?

**Comment by tim-evans** [comment]
Could I get some help on tracking this down, @rwjblue ?

**Comment by tim-evans** [comment]
Yay! This is fixed. Could we get this merged? Ping @rwjblue :)

**Comment by sandstrom** [comment]
@rwjblue @stefanpenner friendly ping :smile: 

*(this is a fix for [#3344](https://github.com/ember-cli/ember-cli/pull/3344), an issue around addon style trees, would be a dream to see it solved)*

**Comment by stefanpenner** [comment]
this looks good to me, I would love @rwjblue +1 as he has more context.

**Comment by stefanpenner** [comment]
@homu r+

**Comment by rwjblue** [comment]
WOOT

**Pull request merged**
