### PR TITLE
Headless chrome only in CI

### PR DESCRIPTION
**Pull request by sivakumar-kailasam**
Testem recently added the ability to support browser args specific to a testem mode. So we should've probably limited headless chrome only to CI mode. This PR addresses that.
//cc @Turbo87 & @rwjblue

### CODE REVIEW

**Comment by Turbo87** [comment]
I'm not a fan of this since in dev mode it will now be impossible to run headless Chrome. Without this change you can just run `ember test --serve --no-launch` (I aliased that to `ets`) instead and click on the link at the top to run in non-headless mode. If you're using `ember-exam` it will also open up several Chrome windows with this change, which can be a bit annoying and doesn't actually help with debugging at all.

tl;dr I vote NO

**Comment by sivakumar-kailasam** [comment]
In case others feel the same, I'll close this one in favor of a PR just updating testem.

**Comment by stefanpenner** [comment]
>  PR just updating testem.

In general upstreaming things to simplify stuff is a good idea.

**Comment by sivakumar-kailasam** [comment]
@stefanpenner didn't quite get that.

**Comment by Turbo87** [comment]
@sivakumar-kailasam I think he wanted to say that a PR that bumps testem will be valueable regardless of the status of this PR

**Comment by sivakumar-kailasam** [comment]
Got it. Raised #7167 for that.

**Comment by sivakumar-kailasam** [comment]
Rewritten commits on my branch to include only the testem config changes.

**Pull request closed without merging**
