### PR TITLE
doc folder

### PR DESCRIPTION
**Pull request by stefanpenner**

### CODE REVIEW

**Comment by Turbo87** [comment]
@stefanpenner the `CONTRIBUTING.md` file has special meaning on GitHub and is displayed as an infobar above the "create new pull request" page:

> Before you create a pull request, please review the guidelines for contributing to this repository.

**Comment by stefanpenner** [comment]
> @stefanpenner the CONTRIBUTING.md file has special meaning on GitHub and is displayed as an infobar above the "create new pull request" page:

ah good point

**Comment by rwjblue** [comment]
@stefanpenner - Needs a rebase and to move the `CONTRIBUTING.md` back to the root (since it has special meaning within the Github UI).

**Comment by Turbo87** [comment]
@stefanpenner friendly reminder 😉

**Comment by Turbo87** [comment]
Closing due to inactivity and conflicts

**Pull request closed without merging**
