### PR TITLE
move fixturify-project to devDeps

### PR DESCRIPTION
**Pull request by ef4**
I think fixturify-project is only used in the tests, so we don't need it in deps.

### CODE REVIEW

**Comment by ef4** [comment]
This revealed another bug. We were publishing `tests/helpers/*` to NPM.

**Comment by rwjblue** [comment]
That wasn't a bug, we intended to provide these helpers to consumers.

**Comment by ef4** [comment]
Oh, ok. TIL.

**Comment by rwjblue** [comment]
yeah 😕 sorry, we (Stef and I) have wanted to expose them as public API with a nice `require('ember-cli').testHelpers` kinda API for a while, just never got around to it 😭

**Pull request closed without merging**
