### PR TITLE
use broccoli-concat

### PR DESCRIPTION
**Pull request by stefanpenner**
The broccoli-sourcemap-concat fork has been merged back into the mainline

### CODE REVIEW

**Comment by rwjblue** [comment]
Will need to update https://github.com/ember-cli/ember-cli/blob/master/lib/broccoli/ember-app.js#L28 also

**Comment by stefanpenner** [comment]
apparently committing when sick is a bad idea :P

**Comment by stefanpenner** [comment]
apparently i also forgot to publish the lib...

**Comment by stefanpenner** [comment]
im not having good luck :P

**Comment by rwjblue** [comment]
@homu r+

**Comment by stefanpenner** [comment]
@homu retry

**Pull request merged**
