### PR TITLE
Add 🐹 as "ember" alias

### PR DESCRIPTION
**Pull request by Turbo87**
because... why not?

### CODE REVIEW

**Comment by kellyselden** [comment]
Windows still works SHIPIT

**Comment by twokul** [comment]
le jit

**Comment by lukemelia** [comment]
Improves developer happiness +1

**Comment by Turbo87** [comment]
@homu r+

**Comment by paschelino** [comment]
Are you people kidding?

**Comment by kellyselden** [comment]
Heaven forbid we have any fun on this volunteer run, open source project. No one has complained yet, but if it's causing people grief we can take it out.

Major breaking change v3.0 to take it out? Haha

**Comment by KernelPanicAUS** [comment]
It would be great to at least offer the ability to opt out.
Not everyone is fond of having emojis as executables on their path and there's nothing wrong with that.

**Comment by paschelino** [comment]
@kellyselden It's fine to have fun. I love fun. Most people do. That's not what my comment is about. It's about giving headaches to pleople seeing an emoji in their logs and trying to fix high prio issues and not knowing what to do about it.

**Comment by kellyselden** [comment]
Like I said, this is the first we've heard of it being a problem. No malice intended. Please open an issue, or better yet, file a PR removing, so the conversation can continue.

I think questioning our professionalism was the wrong approach. Locking before the conversation digresses further.

**Pull request merged**
