### PR TITLE
Update "cpr" to v1.0.0

### PR DESCRIPTION
**Pull request by Turbo87**
resolves part of https://github.com/ember-cli/ember-cli/pull/5548

### CODE REVIEW

**Comment by kellyselden** [comment]
@homu r+

**Comment by Turbo87** [comment]
that looks like a real failure. will investigate.

**Comment by Turbo87** [comment]
@kellyselden this seems to be solved too

**Comment by stefanpenner** [comment]
looks good

**Comment by Turbo87** [comment]
AppVeyor failure seems unrelated

@homu r+

**Pull request merged**
