### PR TITLE
Check if style file with project name exists

### PR DESCRIPTION
**Pull request by btecu**
Currently if a style sheet file named the same as the project exists will cause an exception when building. The error is not very obvious. This check prevents the build and displays an error.

### CODE REVIEW

**Comment by rwjblue** [comment]
Seems good to provide a nice warning here. It will only be checked on initial build (which seems OK to me).

@stefanpenner - r?

**Comment by stefanpenner** [comment]
@rwjblue should this be a silent error?

**Comment by rwjblue** [comment]
Yes, definitely (good catch!).  @btecu - Can you update to use `SilentError`?

**Comment by btecu** [comment]
Done.

**Comment by stefanpenner** [comment]
re-kicking app-veyor

**Pull request merged**
