### PR TITLE
Remove broccoli-static-compiler

### PR DESCRIPTION
**Pull request by btecu**
broccoli-static-compiler has been deprecated, so it has been replaced with broccoli-funnel which has more options and is maintained.

### CODE REVIEW

**Comment by stefanpenner** [comment]
Nice. Now we just need the tests to be green

**Comment by stefanpenner** [comment]
@btecu are you able to push this to completion?

**Comment by btecu** [comment]
I can try. Do you know how I can run just the failing tests locally?

**Comment by stefanpenner** [comment]
http://stackoverflow.com/questions/22936728/running-selective-test-cases-in-mocha-framework

**Comment by btecu** [comment]
@stefanpenner I wasn't sure if there was a different way to run individual tests, but I installed mocha and was able to run.

I'm not able to replicate the failing tests locally. I tried on a PC & Mac, both running `iojs 1.6.2`.

Notice that the tests failing are mentioned here: https://github.com/ember-cli/ember-cli/issues/3524, apparently on a fresh clone, which I don't think it's a coincidence.

**Comment by stefanpenner** [comment]
`npm run test-all` run the acceptance tests aswell. using `.only` to isolate may help you .

**Comment by btecu** [comment]
Yes, I tried that before. I just tried again now and I get:
```
870 passing (6m)
2 pending
```

**Comment by stefanpenner** [comment]
Strange. I will investigate :)

**Comment by stefanpenner** [comment]
windows failure was some dep failed to download: phantomjs (kicking it for another run)

**Comment by stefanpenner** [comment]
https://github.com/ember-cli/ember-cli/pull/3672

Merge via @joliss pr which caught Afew extra places

Thanks for your contribution though!

**Pull request closed without merging**
