### PR TITLE
bump broccoli-asset-rev to 2.1.2

### PR DESCRIPTION
**Pull request by kellyselden**
This should resolve #4607.

### CODE REVIEW

**Comment by stefanpenner** [comment]
hopefully, otherwise we have another thing to track down.

**Comment by stefanpenner** [comment]
@kellyselden I believe tests/acceptance/smoke-test-slow.js:104:31 needs to be updated to `80f2fe63fae0c44478fe0f8af73200a7` now

**Comment by stefanpenner** [comment]
something looks funky here: https://github.com/rickharrison/broccoli-asset-rev/blob/master/lib/fingerprint.js#L81

**Comment by rickharrison** [comment]
Which part doesn't look right to you?

**Comment by stefanpenner** [comment]
> Which part doesn't look right to you?

I think its all ok, just maybe misleading. Left me  thoughts https://github.com/rickharrison/broccoli-asset-rev/issues/70

**Comment by stefanpenner** [comment]
man the IO build is slow...

**Comment by stefanpenner** [comment]
looks like io.js run may have gone sideways:

```
Built project successfully. Stored in "/home/travis/build/ember-cli/ember-cli/tmp/some-cool-app/tmp/class-tests_dist-k8HziY7w.tmp".
not ok 1 Error
    ---
        message: >
            listen EADDRINUSE :::7357
    ...

```

**Comment by stefanpenner** [comment]
Yay

**Pull request merged**
