### PR TITLE
ENHANCEMENT - Added ember-cli-app-version to app blueprint - Close 2524

### PR DESCRIPTION
**Pull request by taras**
PR for #2524

### CODE REVIEW

**Comment by stefanpenner** [comment]
CI seems angry, can you investigate?

**Comment by stefanpenner** [comment]
@taras any luck/time on this one?

Seems like a great addition!

**Comment by taras** [comment]
I will fix it tonight

**Comment by taras** [comment]
@stefanpenner I need help understanding how to debug these tests. It looks like the tests are failing because `ember-cli-app-version` package is not in the *./common-tmp*. 

Is there a place in tests that tells what npm modules should be pulled down?

Is there any way to activate more detailed logging in tests to see whats happening?

**Comment by taras** [comment]
> Is there a place in tests that tells what npm modules should be pulled down?

I deleted ./node_modules-tmp and reran npm install which pulled down the ember-cli-app-version package. Rerunning the tests now.

**Comment by taras** [comment]
Found the problem, going to fix it now.

**Comment by taras** [comment]
IT PASSED!

**Comment by stefanpenner** [comment]
woohoo, thanks

**Pull request merged**
