### PR TITLE
Try some css reverts

### PR DESCRIPTION
**Pull request by stefanpenner**

### CODE REVIEW

**Comment by stefanpenner** [comment]
@twokul / @rwjblue this doesn't work yet. It is more me giving this path a try.

**Comment by rwjblue** [comment]
@twokul and do ember-cli's tests pass too?

**Comment by twokul** [comment]
@rwjblue haven’t gotten a chance to fix them (changed the method name, but I can fix that tonight)

**Comment by twokul** [comment]
waiting for the tests to pass https://github.com/ember-cli/ember-cli/pull/8033

**Comment by twokul** [comment]
fix released as a part of https://github.com/ember-cli/ember-cli/releases/tag/v3.4.2-beta.1

**Pull request closed without merging**
