### PR TITLE
Embed/include ember-try in ember-cli

### PR DESCRIPTION
**Pull request by kategengler**
Also:

- Remove ember-try from the addon package.json blueprints
- Update command set as the default test script for addons to `ember try:each` from `ember try:testall` (functionally equivalent).

### CODE REVIEW

**Comment by rwjblue** [comment]
LGTM

**Comment by chadhietala** [comment]
@homu r+

**Comment by Turbo87** [comment]
do I understand it correctly that `ember-try` can't be updated independent from `ember-cli` anymore now? in other words: if `ember-try` gains any new features you can't use them unless you update `ember-cli` too? does that have any negative implications for our users?

**Comment by kellyselden** [comment]
@Turbo87 semi true. Right now the hint will give us bugfixes, and once we 1.0 ember-try, which should be soon, then it will float until 2.0.
cc @kategengler

**Comment by kategengler** [comment]
@Turbo87 @kellyselden Yep, but on the upside, `ember-try` commands will now be in every `ember-cli` install.

**Comment by Turbo87** [comment]
since `ember-try` is now available for apps too, should we change the app blueprint Travis config to test with beta/canary like the addon blueprint does?

**Comment by kategengler** [comment]
The apps would also need a `config/ember-try.js` generated to do that. 

None of the apps I have worked on have used Travis (they have used other CI services). 

Apps might run their CI build after every commit, sometimes dozens of times a day; it might be wasteful to run both canary and beta on every build.

**Pull request merged**
