### PR TITLE
Fix style concatenation for MU

### PR DESCRIPTION
**Pull request by twokul**
fixes https://github.com/ember-cli/ember-cli/issues/7832

### CODE REVIEW

**Comment by twokul** [comment]
@NullVoxPopuli that's a legit bug then; I'll try to repro.

**Comment by twokul** [comment]
@NullVoxPopuli I wasn't able to reproduce; added a test that confirms tests are built as expected in MU; could you share reproduction steps?

**Comment by NullVoxPopuli** [comment]
@twokul yeah, here is a re-production:
```bash
git clone https://github.com/NullVoxPopuli/react-vs-ember
cd react-vs-ember/event-handling/ember
docker build . -t event-handling-ember
docker exec -it --rm event-handling-ember sh
yarn ember build
# build succeeds

# now lets delete tests
rm -rf tests
yarn ember build
# error!
```


output:

```
$ docker run -it --rm event-handling-ember sh
/app # ls
Dockerfile          config              node_modules        run                 tests               yarn-error.log
README.md           ember-cli-build.js  package.json        src                 tsconfig.json       yarn.lock

/app # yarn install
yarn install v1.5.1
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
Done in 0.73s.

/app # yarn ember build
yarn run v1.5.1
$ MODULE_UNIFICATION=true EMBER_CLI_MODULE_UNIFICATION=true node_modules/.bin/ember build
Could not start watchman
Visit https://ember-cli.com/user-guide/#watchman for more info.
cleaning up...
Built project successfully. Stored in "dist/".
Done in 9.84s.

/app # rm tests/ -rf

/app # yarn ember build
yarn run v1.5.1
$ MODULE_UNIFICATION=true EMBER_CLI_MODULE_UNIFICATION=true node_modules/.bin/ember build
Could not start watchman
Visit https://ember-cli.com/user-guide/#watchman for more info.
cleaning up...
Build failed.
Build Error (Funnel)

ENOENT: no such file or directory, lstat '/app/tmp/funnel-input_base_path-h1wx4DnN.tmp/tests/index.html'


Stack Trace and Error Report: /tmp/error.dump.1daf9217a0afb685afc5c8fd7d86167b.log
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: sh
Arguments: -c MODULE_UNIFICATION=true EMBER_CLI_MODULE_UNIFICATION=true node_modules/.bin/ember build
Directory: /app
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "/app/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by twokul** [comment]
@NullVoxPopuli ah - I wasn't aware you removed `tests` folder. while we can guard against that, not sure if that's something we want to do?

**Comment by NullVoxPopuli** [comment]
@twokul idk, for little demo apps, I think have juuuuuust enough code to run is ideal.

**Pull request merged**
