### PR TITLE
WIP Try to get Windows tests passing

### PR DESCRIPTION
**Pull request by mixonic**
We're blocked on AppVeyor tests not passing. Opening this PR to futz with it.

### CODE REVIEW

**Comment by stefanpenner** [comment]
ewut :P

**Comment by mixonic** [comment]
`result` doesn't seem to have an `output` or `errors` property in some cases.

ewut indeed. I just want to figure out why we can't get any green builds for ember-cli and unblock the 15+ PRs sitting in the backlog. I am very, very receptive to ideas about wtf is going on.

**Comment by kellyselden** [comment]
In case anyone was unaware, Mac/Linux devs can test Windows locally using https://github.com/ember-cli/ember-cli/tree/master/dev/windows

**Comment by mixonic** [comment]
@kellyselden great, thanks!

**Comment by dukex** [comment]
#3967 fixes some tests on windows

**Pull request closed without merging**
