### PR TITLE
[BUGFIX] Acceptance test helper fix.

### PR DESCRIPTION
**Pull request by nathanhammond**
Supersedes #6562.
Fixup for #6556.

Must pass tests on AppVeyor.

### CODE REVIEW

**Comment by nathanhammond** [comment]
[First AppVeyor build of this had an installation failure.](https://ci.appveyor.com/project/embercli/ember-cli/build/11003)

**Comment by nathanhammond** [comment]
Presumed separate Heimdall issue. @hjdivad is on it. Landing this as I assume it to be a complete fix since it passes on Node.js 6 + AppVeyor.

**Comment by nathanhammond** [comment]
@homu r+

**Comment by hjdivad** [comment]
see #6567

**Pull request merged**
