### PR TITLE
Add ability to lint templates.

### PR DESCRIPTION
**Pull request by rwjblue**
Allows tooling like ember-cli-template-lint to work.

### CODE REVIEW

**Comment by rwjblue** [comment]
Updated to add tests and remove `WIP` label.  This should be ready to go.

**Comment by rwjblue** [comment]
Node 0.12 and 5 passed in AppVeyor, the failures there seem random (I've restarted 3 times and a different node version fails each time :disappointed:).

**Comment by rwjblue** [comment]
@stefanpenner - any objections?

**Comment by rwjblue** [comment]
Chatted in slack about this with Stef, we need to do some benchmarks to make sure we don't introduce a perf regression...

**Comment by rwjblue** [comment]
Tests of master vs these changes in the ember-cli/stress-app (after updating it in https://github.com/ember-cli/stress-app/pull/13) are [here](https://usecanvas.com/rwjblue/stress-app-tests-for-ember-cli5561/6aK0wqjOWr2pgUFmHeukqE).

Basic gist:

Description | master (b88de69ba3) | #5561 |
-----|------|-----|
 Initial Boot - Cold | 171216ms | 172612ms |
 Initial Boot - Warm | 9329ms | 7931ms |
 Rebuild - js file | 2027ms | 1660ms |
 Rebuild - sass file | 1826ms | 1872ms |

**Comment by stefanpenner** [comment]
@rwjblue  :+1:  looks like nothing surprising snuck in re: perf, :ship:

**Comment by rwjblue** [comment]
Ya, but definitely better to be safe than sorry...

**Comment by rwjblue** [comment]
I'm doing a few more small checks locally with my addon (ember-cli-template-lint) to make sure all is well.  Will land it as soon as everything there checks out...

**Comment by rwjblue** [comment]
@homu r+

**Pull request merged**
