### PR TITLE
[Bugfix release]: pin ember-cli-dependency-checker

### PR DESCRIPTION
**Pull request by NullVoxPopuli**
`master` here: https://github.com/ember-cli/ember-cli/pull/9851

### CODE REVIEW

**Review by rwjblue — APPROVED** [review]
Working around https://github.com/quaertym/ember-cli-dependency-checker/issues/132 (`ember new foo` is broken ATM).

**Comment by NullVoxPopuli** [comment]
Failures are unrelated -- tangential problem reported here: https://discord.com/channels/480462759797063690/483601670685720591/963132593287606273

Probably a babel problem, yeah?

**Comment by Windvis** [comment]
Yea, it's this issue: https://github.com/ef4/babel-import-util/issues/5 which has been fixed in the 1.2.1 release. Simply restarting CI should resolve those errors.

**Comment by rwjblue** [comment]
Closing now that 3.3.1 is released

**Pull request closed without merging**
