### PR TITLE
[WIP] Propagates testem errors

### PR DESCRIPTION
**Pull request by chancancode**
Couldn't get the test to pass locally for some reason ¯\_(ツ)_/¯

TODOS:
- [ ] Make the test work
- [ ] Properly handle the testem timeout

```
Error: Timed out after 540s
    at null._onTimeout (/Users/godfrey/Code/ember.js/node_modules/testem/lib/app.js:309:21)
    at Timer.listOnTimeout (timers.js:89:15)
```

### CODE REVIEW

**Comment by stefanpenner** [comment]
I'll continue the ember-cli side of things.

@johanneswuerbach we should likely talk about how we should handle these timeouts (or prevent them from happening) Basically, it seems that during `ember test --server` we end up de-syncing some session that times out. Maybe @chancancode can share some more details, i'm a-bit hazy on the exact details, but it feels like something fishy is going on. Maybe it is how we continuously reinvoke testem, maybe leaking some intermediate result?

**Comment by stefanpenner** [comment]
So a quick look, suggests maybe testems  `stopCurrentRun` which is invoked by `triggerRun` which happens on restart of testem, should also cancel the same timeout cancelled by `exit` [here](https://github.com/testem/testem/blob/master/lib/app.js#L167-L170)

**Comment by johanneswuerbach** [comment]
Looks right, if you can implement that :+1: otherwise I should have time end of the weekend to fix it myself.

**Comment by stefanpenner** [comment]
@johanneswuerbach I will at the very least submit a PR today.

**Comment by stefanpenner** [comment]
superseded by: https://github.com/ember-cli/ember-cli/pull/5526

**Pull request closed without merging**
