### PR TITLE
WIP: http mock in tests

### PR DESCRIPTION
**Pull request by taras**
This is PR for #1763, it adds *./server* as middleware to testem. 

Do we need a way to disable this functionality? or should it be disabled by default?

### CODE REVIEW

**Comment by taras** [comment]
Damn, there is a commit that's intended for another PR.

**Comment by seawatts** [comment]
Looks good to me. Just need to fix the tests

**Comment by bjornstar** [comment]
Please revisit this, I'd really like to use http-mocks in our tests.

**Comment by chnn** [comment]
@taras Do you plan to continue with this? If not I'm happy to continue where you left off.

**Comment by DenizOkcu** [comment]
+1

**Comment by zyllorion** [comment]
+1

**Comment by pedrokost** [comment]
+1

**Comment by abuiles** [comment]
@taras ping ?

**Comment by aokon** [comment]
I think that `Ember CLI comes with an http-mock generator which is preferred to fixtures for development and testing`(http://www.ember-cli.com/#mocks-and-fixtures) is not working properly for test env (my acceptance tests are broken when I'm using http-mocks for my example app https://github.com/aokon/embe-cli-example-app) and I hope so that the work will be continued on this feature.

**Comment by abuiles** [comment]
I wonder if we should we remove the http-mock stuff at all in favor or https://github.com/samselikoff/ember-cli-mirage

**Comment by taras** [comment]
@abuiles yes, I think we should.

**Comment by abuiles** [comment]
cc @samselikoff

**Comment by samselikoff** [comment]
possibly one day, right now mirage can't handle proxies or other-origin requests. But I'm certainly open to any ideas. I'd also imagine there's quite a few people with complicated http mocks already written.

**Comment by stefanpenner** [comment]
> possibly one day, right now mirage can't handle proxies or other-origin requests. But I'm certainly open to any ideas. I'd also imagine there's quite a few people with complicated http mocks already written.

maybe there is a small server side component that works with mirage ?

**Comment by jayphelps** [comment]
:-1: for mirage as a replacement. It's _very_ cool, however since it is client side, there are cases which fall apart in complex apps. Having express (or koa, etc) allows devs to utilize existing tons of middleware for unique needs. Like batching requests, etc.

**Comment by stefanpenner** [comment]
> I do really wish http-mocks would run in tests

pr welcome :trollface:

**Comment by jayphelps** [comment]
trolololo

**Comment by dylanfoster** [comment]
Any movement on this @taras I'd be happy to give a leg up so we can get this in.

**Comment by eddflrs** [comment]
Is this still a WIP?

**Comment by jnfingerle** [comment]
It'd be great if this feature would land in the near future. I'm aware of client-side approaches, but they don't fit all needs; and, after all, this is code already written *and* it solves an existing divergence between different use cases.

**Comment by odarbelaeze** [comment]
:+1: Here is another leg

**Comment by stefanpenner** [comment]
This seems to have gone stale, we can revisit. But an idle PR is just noise on the tracker.

**Comment by jasonmit** [comment]
I've sent a PR to remove the language in the ember-cli docs suggesting mocks are run in testing, but would really like this feature.  Is there still interest in this @stefanpenner, if so I'd like to resurrect it and see what I can do to move it forward.

**Pull request closed without merging**
