### PR TITLE
remove exists-sync, use fs.existsSync

### PR DESCRIPTION
**Pull request by stefanpenner**
It was once deprecated, but that idea was rolled back

### CODE REVIEW

**Comment by rwjblue** [comment]
```
not ok 10 eslint should have no errors in lib
  Error: Code did not pass lint rules
  lib/utilities/is-yarn-project.js
     3:7   error  'path' is assigned a value but never used  no-unused-vars
    16:21  error  Unexpected string concatenation            prefer-template
  
  ✖ 2 problems (2 errors, 0 warnings)
    1 error, 0 warnings potentially fixable with the `--fix` option.
  
      at Context.<anonymous> (node_modules/mocha-eslint/index.js:36:15)
```

**Comment by stefanpenner** [comment]
Investigating additional issues.

**Comment by stefanpenner** [comment]
kick CI for a rebuild

**Comment by rwjblue** [comment]
Rebased to fix yarn.lock conflict

**Comment by Bartheleway** [comment]
I found that you might have forgotten that place [lib/tasks/server/middleware/tests-server/package.json](https://github.com/ember-cli/ember-cli/blob/master/lib/tasks/server/middleware/tests-server/package.json)

**Pull request merged**
