### PR TITLE
Added Node v5 to Appveyor

### PR DESCRIPTION
**Pull request by patocallaghan**

### CODE REVIEW

**Comment by stefanpenner** [comment]
:+1:

**Comment by stefanpenner** [comment]
kicking appveyor, ironically v5 was the only one that passed :P

**Comment by rwjblue** [comment]
LOL

**Comment by stefanpenner** [comment]
lots of windows things fixed, rebase and this might be good. If not we will have to deep dive.

**Comment by patocallaghan** [comment]
Just rebased

**Comment by patocallaghan** [comment]
Failed again for Windows. Most errors seem to be of the below variety.

```
 3) Acceptance: blueprint smoke tests "before each" hook for "generating an http-proxy installs packages to package.json":
     Error: EPERM: operation not permitted, unlink 'C:\projects\ember-cli\tmp\concat_with_maps-output_path-XjvyZ6jS.tmp\addons.js'
      at Error (native)
 ```

**Comment by kellyselden** [comment]
Probably a temporary failure, found in #5055.

**Comment by stefanpenner** [comment]
@kellyselden likely

**Comment by stefanpenner** [comment]
rebase please, potentially clear up windows issue

**Comment by patocallaghan** [comment]
Rebased and pushed..

**Comment by stefanpenner** [comment]
Thx

**Comment by chadhietala** [comment]
@homu r+

**Pull request merged**
