### PR TITLE
Adds disable-analytics option to all commands

### LINKED ISSUE #1835: Need to add/enable a `--disable-analytics` option for all commands.
Now that we have the ability to disable analytics via `.ember-cli` file, we should also be able to disable via `--disable-analytics` command line option to all commands.

/cc @twokul

### PR DESCRIPTION
**Pull request by twokul**
Fixes #1835

- [x] add `disableAnalytics` option to `models/command`
- [x] `models/command` tests
- [x] add tests for other commands
- [x] make sure to pass `disableAnalytics` option to tasks

### CODE REVIEW

**Comment by rwjblue** [comment]
agreed

**Comment by twokul** [comment]
@stefanpenner @rwjblue I'll update tonight

**Comment by stefanpenner** [comment]
danke her @twokul

**Comment by twokul** [comment]
closed in favour of https://github.com/ember-cli/ember-cli/pull/2923

**Pull request closed without merging**
