### PR TITLE
Merge master into detect-changes

### PR DESCRIPTION
**Pull request by aexmachina**
Updates the tests to use `expect()` rather than `assert()`.

### CODE REVIEW

**Comment by rwjblue** [comment]
This PR seems very wrong.  It includes more than 250 commits....

@aexmachina - Mind rebasing this down to just your changes?

**Comment by aexmachina** [comment]
Yes indeed it does, not sure why it didn't fast-forward, have rebased and pushed.

**Comment by aexmachina** [comment]
Actually, that makes perfect sense - I've merged in master, and this PR is into `detect-changes`, which is behind master. If you merge master into detect-changes you should see just 0xcfbdd7.

**Comment by stefanpenner** [comment]
200+ commits, this is clearly an mistake.  Closing for now, will gladly review something with a more correct number of commits to review.

**Comment by aexmachina** [comment]
No it's just because this merges master into Robert's branch.

**Comment by rwjblue** [comment]
@aexmachina - Ya, but when we are good with this branch, we can rebase and merge it into master (no need to merge master into it).

**Comment by aexmachina** [comment]
Sure, I was hoping that the problem had magically disappeared in master :smile: Anyway, there's a commit in here that updates the tests, but it pretty trivial. Really wish I could get this sorted out, we're using my branch whenever we do SASS work and it's SOOO much better. Buy yeah, I've got no idea why those slow tests are failing. Hopefully someone else can get it sorted out and in the meantime I'll keep using my branch when I need it.

**Pull request closed without merging**
