### PR TITLE
[BUGFIX] Ensure `package.json` `main` entry point is used for addon lookup.

### PR DESCRIPTION
**Pull request by rwjblue**

### CODE REVIEW

**Comment by stefanpenner** [comment]
```
  1) models/addon.js resolvePath allows lookup of non-`index.js` `main` entry points:
     TypeError: Cannot read property 'main' of undefined
      at Function.Addon.resolvePath (/home/travis/build/ember-cli/ember-cli/lib/models/addon.js:642:72)
      at Context.<anonymous> (/home/travis/build/ember-cli/ember-cli/tests/unit/models/addon-test.js:146:46)
      at callFn (/home/travis/build/ember-cli/ember-cli/node_modules/mocha/lib/runnable.js:250:21)
      at Test.Runnable.run (/home/travis/build/ember-cli/ember-cli/node_modules/mocha/lib/runnable.js:243:7)
      at Runner.runTest (/home/travis/build/ember-cli/ember-cli/node_modules/mocha/lib/runner.js:373:10)
      at /home/travis/build/ember-cli/ember-cli/node_modules/mocha/lib/runner.js:451:12
      at next (/home/travis/build/ember-cli/ember-cli/node_modules/mocha/lib/runner.js:298:14)
      at /home/travis/build/ember-cli/ember-cli/node_modules/mocha/lib/runner.js:308:7
      at next (/home/travis/build/ember-cli/ember-cli/node_modules/mocha/lib/runner.js:246:23)
      at Object._onImmediate (/home/travis/build/ember-cli/ember-cli/node_modules/mocha/lib/runner.js:275:5)
```

**Comment by rwjblue** [comment]
Updated to fix that error, but am now seeing acceptance test failures indicating that broccoli-asset-rev  didn't run properly.  Will dig into it in a bit...

**Comment by rwjblue** [comment]
Pull request fixing the issue in broccoli-asset-rev: https://github.com/rickharrison/broccoli-asset-rev/pull/37

**Comment by stefanpenner** [comment]
broccol-asset-rev pr has been merged.

**Comment by rwjblue** [comment]
Bumped version of broccoli-asset-rev to include fixes.

**Pull request merged**
