### PR TITLE
Use defaultLocationType for location resolution

### PR DESCRIPTION
**Pull request by chadhietala**
This probably needs to wait till wait till Ember 1.11.0 released. https://github.com/emberjs/ember.js/pull/10297

### CODE REVIEW

**Comment by rwjblue** [comment]
Can you explain more?  `defaultLocationType` isn't mentioned in https://github.com/emberjs/ember.js/pull/10297 (and https://github.com/emberjs/ember.js/pull/10297 isn't in 1.11).

**Comment by chadhietala** [comment]
Yea this isn't correct, but there is an issue resolving URLs in the canary.

**Comment by rwjblue** [comment]
Confirm, was just chatting with some folks in IRC about it.

**Comment by rwjblue** [comment]
Opened https://github.com/emberjs/ember.js/issues/10396 for this.

**Pull request closed without merging**
