### PR TITLE
some safe runCommand removals

### PR DESCRIPTION
**Pull request by kellyselden**
replacing with ember test helper

cc #4527

### CODE REVIEW

**Comment by stefanpenner** [comment]
nice, although CI doesn't agree yet.

**Comment by kellyselden** [comment]
I tested each individually using `.only`. Of course when run together they start failing... I will look into this tomorrow.

**Comment by stefanpenner** [comment]
if the run `npm` install internally, they are not safe.

**Comment by kellyselden** [comment]
I had to remove all the offenders, leaving only one removal. Still, shaves off time.

@stefanpenner the commands being run were `test` and `build`, which I don't believe involve npm.

**Comment by stefanpenner** [comment]
> @stefanpenner the commands being run were test and build, which I don't believe involve npm.
>  Hide all checks

crap :P

**Pull request merged**
