### PR TITLE
Simplify print-command utility

### PR DESCRIPTION
**Pull request by Turbo87**

### CODE REVIEW

**Comment by stefanpenner** [comment]
:+1:

**Comment by kellyselden** [comment]
@Turbo87 Why are you skipping homu?

**Comment by Turbo87** [comment]
@kellyselden because it was broken earlier today and I didn't notice it was working again (see https://github.com/ember-cli/ember-cli/pull/5654)

**Comment by kellyselden** [comment]
@Turbo87 Oh ok. I didn't know. Thanks.

**Pull request merged**
