### PR TITLE
Allow jquery to be escaped

### PR DESCRIPTION
**Pull request by kayakyakr**

### CODE REVIEW

**Comment by kayakyakr** [comment]
indeed. thanks. ignore the guy that can't read code.

**Comment by stefanpenner** [comment]
@kayakyakr sorry, that config object and `broccoli/ember-app` really needs better docs... That likely lead to your confusion.

**Comment by kayakyakr** [comment]
For the record, this is the code necessary:

```
new EmberApp(defaults, {
    vendorFiles: {
      "jquery.js": null
    }
  })
```

**Comment by stefanpenner** [comment]
Cc @cibernox I suspect your proposed blog post will make people happy here :)

**Comment by cibernox** [comment]
@stefanpenner I imagine so. I didn't want to publish it until the PR to ember-fetch is merged, because felt wrong to tell people to use a fork of a fork or a project. 

FWIW, https://gist.github.com/cibernox/137755f12985863335fac8226bc22f28

And some captures with `Good 3G + 5x throttle` (more or less equivalent to high end android in meh network" showing ~0.7s saving

With jQuery:
with-jquery

Without jQuery:
without-jquery

**Comment by stefanpenner** [comment]
@cibernox ya, big win. #cantWaitForIt :P

**Pull request closed without merging**
