### PR TITLE
Bump minimum Node version for addons.

### PR DESCRIPTION
**Pull request by rwjblue**
Node 4 is completely unsupported now, there is no reason to attempt to run it in CI still. Addons generated by ember-cli@3.2.0 should not try to use Node 4...

Note: targets beta branch...

TODO:

- [x] Fix `engines` support in `package.json` to drop Node 4 (and 7).
- [x] Update ember-cli's own `package.json` for supported Node engines.

### CODE REVIEW

**Comment by Turbo87** [comment]
I'm wondering if we should include a note somewhere that people should bump majors when doing this. Especially with ember-cli-update this is an easy to miss change.

**Comment by rwjblue** [comment]
OK, updated with the last TODO items.  Should be good to go (assuming everyone is still 👍 )...

**Comment by Turbo87** [comment]
@rwjblue looks like we also need to adjust the AppVeyor config 😉

**Comment by rwjblue** [comment]
Thank you @Turbo87!

**Pull request merged**
