### PR TITLE
Add doc section about how to build your own version of Ember

### PR DESCRIPTION
**Pull request by balinterdi**
I needed to build my own version of Ember (basically apply a hotfix on top of 1.11.3) and did not find any documentation on it.

This PR aims to fill that hole. Not 100% sure if that is *the* correct way but it works fine in our project.

### CODE REVIEW

**Comment by stefanpenner** [comment]
I think a better approach is using `bower link`

**Comment by balinterdi** [comment]
@stefanpenner I think you refer to that one: https://gist.github.com/rwjblue/9216101d3d15a9134bdd . Can the same method be followed in production, too? (I am quite a newb when it comes to bower and npm commands).

I think it would be nice to have a section on that in the Ember CLI guides and I'd be happy to rebase (not the git way ;) ) my PR to use @rwjblue 's gist.

**Comment by stefanpenner** [comment]
Assuming you build your production locally yes it works.

**Comment by balinterdi** [comment]
So it there value in me writing this up (modifying my current PR to suggest using `bower link` instead)?

**Comment by stefanpenner** [comment]
cc @leo

**Comment by leo** [comment]
@balinterdi Thank you for your help on improving the docs! But could you please re-target this PR to the [new repo][1] of our site? The old branch has been deleted. Thank you very much! :innocent:

[1]: https://github.com/ember-cli/ember-cli.github.io

**Pull request closed without merging**
