### PR TITLE
[BUGFIX beta] Update tiny-lr.

### PR DESCRIPTION
**Pull request by nathanhammond**
Can't land until there is a 1.0.3 release, but this will make us compatible with Node.js 0.12 again.

Note the target of `beta`, will land and then merge back to `master`. (AKA, leave this one for me to land so I'm paying attention.)

### CODE REVIEW

**Comment by elwayman02** [comment]
👍

**Comment by nathanhammond** [comment]
And, since I merged the `tiny-lr` update, this is me closing the loop.

@homu r+

**Comment by nathanhammond** [comment]
@homu retry

**Comment by nathanhammond** [comment]
@homu abort

**Comment by nathanhammond** [comment]
Hrngh, computers.

**Comment by nathanhammond** [comment]
@homu r-

**Comment by nathanhammond** [comment]
@homu r+

**Comment by nathanhammond** [comment]
Pretty sure that this exchange broke @homu. Moving to manual.

**Pull request merged**
