### PR TITLE
allow generated acceptance tests to be in directories

### PR DESCRIPTION
**Pull request by koriroys**
An example of what currently doesn't work:

    ember g acceptance-test projects/create

Opening this to start a discussion. Probably you guys know a better solution.

### CODE REVIEW

**Comment by stefanpenner** [comment]
sounds good, but you'll also need to update the tests

**Comment by koriroys** [comment]
@stefanpenner :heavy_check_mark:

**Comment by jakecraige** [comment]
Some other tests were just recently changed to be relative for issues with generating in addons - #3154 . This doesn't reverse any of those changes, but it seems like it may cause the same issues reported in #3143 I'd want to make sure this isn't the case before merging. Pretty much, acceptance test generation should work within an addon

**Comment by stefanpenner** [comment]
@jakecraige ok, this is waiting you +1 then. Merge when you feel good, or leave a comment detailing why not :)

**Comment by koriroys** [comment]
@jakecraige do/can addons generate acceptance tests? I admit I'm not familiar with addons or how they work yet.

**Comment by stefanpenner** [comment]
i rebased and made some formatting changes

**Pull request closed without merging**
