### PR TITLE
WIP: remove ember-cli-legacy-blueprints

### PR DESCRIPTION
**Pull request by kellyselden**
now that ember-source provides our blueprints

### CODE REVIEW

**Comment by Turbo87** [comment]
as mentioned on Slack: this would remove the blueprints for all users that are not using ember-source yet and I don't see a reason why we would need to do that any time soon. let's revisit that if we should ever release a v3.0.0.

**Comment by kellyselden** [comment]
I ran `ember h g` and saw that this addon was winning vs ember-source

**Comment by rwjblue** [comment]
yeah, that is definitely not right

**Comment by Turbo87** [comment]
> I ran ember h g and saw that this addon was winning vs ember-source

then we should debug this.

https://github.com/ember-cli/ember-cli-legacy-blueprints/blob/master/package.json#L57-L60 and https://github.com/emberjs/ember.js/blob/master/package.json#L92 look correct to me

**Comment by Turbo87** [comment]
I've opened #6751 to track this issue

**Pull request closed without merging**
