### PR TITLE
Extract unknown command

### PR DESCRIPTION
**Pull request by quaertym**

### CODE REVIEW

**Comment by stefanpenner** [comment]
:+1:

**Comment by quaertym** [comment]
@stefanpenner Appveyor is still problematic.

**Comment by stefanpenner** [comment]
actually its fine, appveyor is for some reason getting hijacked still by @jayphelps's fork. (I have no idea why)

https://ci.appveyor.com/project/embercli/ember-cli/build/2973

**Comment by jayphelps** [comment]
>:) all your tests are belong to me

**Comment by stefanpenner** [comment]
greedy greedy @jayphelps... Well if you paid for the fast appveyor boxes, you can have them. But yours keep timing out.

**Pull request merged**
