### PR TITLE
[ENHANCEMENT] implement Blueprint.prototype.addAddonToProject

### LINKED ISSUE #2863: Add `addAddonsToProject`/`addAddonToProject` to blueprint model
This is a note to self to add this. 

It should add the addon(s) and run their generators. Equivalent to the `install:addon` command

### PR DESCRIPTION
**Pull request by jakecraige**
also moved install addon logic into a task so that it's easy to reuse
closes #2863

### CODE REVIEW

**Comment by stefanpenner** [comment]
LGTM

**Comment by rwjblue** [comment]
:+1: - Kicking appveyor...

**Comment by jakecraige** [comment]
I get a different error every time I re-run appveyor.. none related to my stuff, ugh...

**Comment by jakecraige** [comment]
it finally passed, phew.

**Pull request merged**
