### PR TITLE
Cleanup unused deps

### PR DESCRIPTION
**Pull request by ro0gr**
Looks like these deps are incorporated to the `console-ui` package now

### CODE REVIEW

**Comment by Turbo87** [comment]
@ro0gr looks good, can you rebase once https://github.com/ember-cli/ember-cli/issues/6486 is resolved?

**Comment by ro0gr** [comment]
Sure

**Comment by Turbo87** [comment]
@ro0gr things on `master` should be resolved now. please rebase :)

**Comment by rwjblue** [comment]
@Turbo87 - I'm going to let homu confirm this one (doesn't have a merge conflict so it should be mergeable if it applies and passes against current master).

@homu r+

**Pull request merged**
