### PR TITLE
Upgraded ember-cli-app-version to 2.0.0

### PR DESCRIPTION
**Pull request by taras**
## ember-cli-app-version@2.0.0

[Compare v1.0.1 to v2.0.0](https://github.com/EmberSherpa/ember-cli-app-version/compare/v1.0.1...v2.0.0)

- Upgraded to git-repo-version@0.4.0
- Replaced app-version component with app-version helper

### CODE REVIEW

**Comment by stefanpenner** [comment]
> Replaced app-version component with app-version helper

is this a breaking change for ember-cli users?

**Comment by nathanhammond** [comment]
@stefanpenner Based upon my review of the changes it doesn't appear to be unless people are relying upon `app-version` being a component instead of a helper.

**Comment by stefanpenner** [comment]
I suspect this is good to ship, but want to double check with señor @taras  :)

**Comment by Turbo87** [comment]
@taras @stefanpenner any news here? can we merge this without breaking compat in unreasonable ways?

**Comment by taras** [comment]
Yes, I think it's good to go. the chances of this breaking something are very small but relative to the amount of code in this library - it's a big change :)

**Comment by stefanpenner** [comment]
@homu r+

**Pull request merged**
