### PR TITLE
Add .map to default fingerprinting extensions

### PR DESCRIPTION
**Pull request by max**
Extension defaults now includes `.map`: https://github.com/rickharrison/broccoli-asset-rev#options

### CODE REVIEW

**Comment by stefanpenner** [comment]
I don't believe this actually updates the inline sourceMap urls though

**Comment by max** [comment]
@stefanpenner Maybe I'm misunderstanding what you're saying but this is the end of a JS file when fingerprinting is turned on (`.map` included):

```
//# sourceMappingURL=my-example-8d2e3b6bbd616b34cd18ac794d148b2c.map
```

**Comment by stefanpenner** [comment]
@max ah, you are likely correct. I guess I'm unaware of broccoli-asset-rev's true power.

Let me double check to confirm

**Comment by max** [comment]
@stefanpenner Here's the commit that enables [replacing sourcemap URLs](https://github.com/rickharrison/broccoli-asset-rewrite/commit/cd7eafa6eb38f92e9ffeeb297e32a13a8a71576c).

**Comment by stefanpenner** [comment]
confirmed + thanks for the link to the commit :)

**Comment by stefanpenner** [comment]
thank you kindly sir.

**Pull request merged**
