### PR TITLE
Make sure addon transforms are available in app

### PR DESCRIPTION
**Pull request by rwwagner90**
I noticed when using ember-cli-cjs-transform in one of our addons, that when it was consumed in an app, the transform was flagged as unavailable. I believe this should fix the issue. Most of this idea was given to me by @rwjblue. Please let me know if it needs any tweaks!

### CODE REVIEW

**Comment by rwwagner90** [comment]
@Turbo87 I just moved it to the right place. There is a comment `// Methods without default implementation` and now this has a default implementation, so it should not be in that section. I still need help finding a way to use nested addons for these tests. The test here is not actually testing what I expected, as @rwjblue pointed out on Slack.

**Comment by rwwagner90** [comment]
@rwjblue @Turbo87 I still need help testing this. Any chance either of you have time to help unblock this?

**Comment by rwwagner90** [comment]
@rwjblue @Turbo87 do we want to not support this? If so, we can close it. Trying to clean up old PRs that are outstanding for the new year 😄

**Comment by Turbo87** [comment]
again, the shuffling around of the methods makes this quite hard to review. if you want to move the methods around it would be best to do that in a separate commit/PR.

**Comment by rwwagner90** [comment]
@rwjblue @Turbo87 this had been open over a year now. If we don't intend to support this, should we close it?

**Comment by Turbo87** [comment]
see https://github.com/ember-cli/ember-cli/pull/7703#issuecomment-451128575

**Comment by rwwagner90** [comment]
@Turbo87 I have explained this. See https://github.com/ember-cli/ember-cli/pull/7703#issuecomment-451141826

**Comment by rwwagner90** [comment]
@rwjblue @Turbo87 Just checking again, do we want to support this or close it?

**Comment by rwjblue** [comment]
@rwwagner90 - Ya, can you rebase so we get a fresh CI run?

**Comment by rwwagner90** [comment]
@rwjblue conflicts resolved!

**Comment by rwwagner90** [comment]
I never figured out how to write tests for this, so not sure if you guys have some insights there or not?

**Comment by rwwagner90** [comment]
Closing this. It's been open a long time, with little interest. If we want to ensure transforms used by addons are available in apps, we will need this, but someone can open another PR if we decide we want it.

**Pull request closed without merging**
