### PR TITLE
Travis multiple blank line cleanup and if block code consolidation

### PR DESCRIPTION
**Pull request by kellyselden**
I had Travis file cleanup in #7066 that was closed. This takes the good cleanup without the firefox stuff.

### CODE REVIEW

**Comment by Turbo87** [comment]
hmm... are those files not checked by any tests?

**Comment by stefanpenner** [comment]
Likely not a bad idea to load them via yml parser and ensure the internal state is as expected

**Comment by Turbo87** [comment]
> Likely not a bad idea to load them via yml parser and ensure the internal state is as expected

sounds nice in theory, but might be overkill for what we're doing here 🤔

**Comment by stefanpenner** [comment]
@Turbo87 future PR is fine

**Comment by kellyselden** [comment]
I though about fixtures to test these files too. I think I will add them. It's so easy to regress the formatting in these files that I think it will be worth it.

**Pull request merged**
