### PR TITLE
cherry-pick core-object upgrade to 2.6 beta.

### PR DESCRIPTION
**Pull request by nathanhammond**
@rwjblue @stefanpenner I'm not breaking anything if I do it this way?

### CODE REVIEW

**Comment by nathanhammond** [comment]
At least this will run tests. 😛

**Comment by rwjblue** [comment]
👍

**Comment by stefanpenner** [comment]
👍

**Comment by Turbo87** [comment]
for reference: this was originally https://github.com/ember-cli/ember-cli/pull/5737

**Pull request merged**
