### PR TITLE
[Enhancement] Architecture Diagram

### PR DESCRIPTION
**Pull request by visheshjoshi**
Added architecture diagram to ARCHITECTURE.md.

### CODE REVIEW

**Comment by stefanpenner** [comment]
awesome, maybe we should use omni graffle, and also commit the file. So its easy to maintain/update.

**Comment by visheshjoshi** [comment]
I used https://www.draw.io/ to draw this, which allows exporting to xml.
@stefanpenner Do you think committing the xml might work?
Also do you think putting it in an assets folder might be a good idea?

**Comment by stefanpenner** [comment]
> @stefanpenner Do you think committing the xml might work?

:+1:

**Comment by stefanpenner** [comment]
> Also do you think putting it in an assets folder might be a good idea?

:+1:

**Comment by stefanpenner** [comment]
@visheshjoshi got a chance to add the XML ?

**Comment by visheshjoshi** [comment]
@stefanpenner Just did.

**Comment by stefanpenner** [comment]
@visheshjoshi mind squashing the commits? Then we should be good to go.

**Comment by stefanpenner** [comment]
@trabus a diagram like this, might help people understand that boot process. And, likely some of the pod stuff we have planned.

**Comment by yvisheshjoshi** [comment]
@stefanpenner looks like the appveyor tests timed out. Mind restarting them?

**Comment by stefanpenner** [comment]
i have confidence these doc improvements didn't actually break windows CI. merging, thanks dude!

**Comment by stefanpenner** [comment]
@visheshjoshi although this is awesome, are you interested in updating the diagram to use: https://github.com/knsv/mermaid ?

**Comment by visheshjoshi** [comment]
@stefanpenner Will take a look at mermaid and update the diagram.

**Pull request merged**
