### PR TITLE
Original Solution for Multiple Meta Modules

### PR DESCRIPTION
**Pull request by nathanhammond**
Opening a new PR in parallel to #5233 to see if Travis is happy with the original solution. I don't want to lose the documentation in #5233 in case we haven't fixed the underlying bug.

### CODE REVIEW

**Comment by stefanpenner** [comment]
ya. lets see. @rwjblue fixed one particularly gnarly pieces of test leakage..

**Comment by nathanhammond** [comment]
This one reveals a bug (I believe) in ESLint:
* [Error.](https://travis-ci.org/ember-cli/ember-cli/jobs/114006236#L2462)
* [What it's referring to.](https://github.com/ember-cli/ember-cli/pull/5582/files#diff-daf5348a6a11b90c7ef3be8ef1888dc1R5)
* [Why it shouldn't be broken.](https://github.com/ember-cli/ember-cli/pull/5582/files#diff-daf5348a6a11b90c7ef3be8ef1888dc1R1)

Also, the error message is useless in Travis, trying to repro locally.

**Comment by nathanhammond** [comment]
Hey @rwjblue! Want to shave years off your life? Neither @stefanpenner nor I can figure out what is going on here. If we stop testing using `debugger` and then manually run tests on the application at that point the tests pass. It's something in our testing setup or Phantom or who knows what and I don't even know where to go from here...

**Comment by stefanpenner** [comment]
I suspect we should re-eval this now that @twokul identified those other issues.

**Comment by Turbo87** [comment]
@nathanhammond can you rebase this on master?

**Comment by nathanhammond** [comment]
Rebasing.

**Comment by nathanhammond** [comment]
Still fails in exactly the same way:
> Promise rejected before meta tag modules work: Could not find module `meta/tag/module` imported from `dummy/routes/application`

I don't know what to say about this test. The feature actually works, but our testing harness hates this one.

@Turbo87 would you like to lose many hours of your life inspecting this one?

**Comment by Turbo87** [comment]
@nathanhammond got a few other things on my todo list already 😉

**Comment by Turbo87** [comment]
closing due to inactivity

**Comment by SergeAstapov** [comment]
@Turbo87 Is there a newer PR with this feature implementation?

**Comment by Turbo87** [comment]
@SergeAstapov not that I'm aware of. feel free to revive this PR if you want to take over :)

**Pull request closed without merging**
