### PR TITLE
Add .eslintrc.js files to blueprints

### LINKED ISSUE #6864: Include ESLint default config files in app/addon blueprints
Instead of running the `ember-cli-eslint` blueprint on `ember new` we should instead just duplicate the empty ESLint config files so that e.g. they show up at https://github.com/ember-cli/ember-new-output and also work with the `--skip-npm` flag.

### PR DESCRIPTION
**Pull request by rwwagner90**
Fixes #6864

### CODE REVIEW

**Comment by rwjblue** [comment]
The node@4 job failed for flaky timeout reasons, restarted it...

**Comment by rwjblue** [comment]
@homu r+

**Comment by rwjblue** [comment]
grr, looks like homu merged master anyways 😢

**Comment by Turbo87** [comment]
@rwjblue yeah, homu doesn't work with changing the base branch of the PR after it has been opened

**Comment by Turbo87** [comment]
@rwjblue @rwwagner90 since ESLint got introduced in 2.12 I think it would make sense to pull this down to the `release` branch. agreed?

**Comment by rwjblue** [comment]
Sure, seems good to me.

**Pull request merged**
