### PR TITLE
WIP: Transpile async/await in tests via Babel

### PR DESCRIPTION
**Pull request by Turbo87**
It seems to work quite well. Do we want this?

### CODE REVIEW

**Comment by rwjblue** [comment]
I'm on the fence.  Based on the way you have it setup to prevent transpilation from leaking into `lib/` code during out test suite, I think this is probably OK. However, we have generally been opposed to any/all transpilation so it is a fairly large departure.

We should definitely discuss at the CLI core team call...

**Comment by stefanpenner** [comment]
> Based on the way you have it setup to prevent transpilation from leaking into lib/ code during out test suite, I think this is probably OK

^ is important, thanks.

---

Out of curiosity how much transpilation time does this add?

**Comment by Turbo87** [comment]
@stefanpenner the overhead on my machine is barely noticeable compared to the time that we spend in our testing code itself

**Comment by rwjblue** [comment]
I _think_ he meant the transpiled output (e.g. when stepping through the code during a debugging session). At least that is what I am also curious about 😜

**Comment by stefanpenner** [comment]
> I am also wondering how bad the transpiled output is (e.g. when stepping through the code during a debugging session).

I am an outlier, i actually usually prefer the giant switch statement over callbacks :P...

**Comment by Turbo87** [comment]
I've adjusted the PR to use https://github.com/babel/babel-preset-env now which has some up- and downsides:

- ➕ it only transpiles async/await if Node version is below 7.7.1 (or whatever introduced native async/await)
- ➖ it transpiles all other ESsomething features too unless we use a large blacklist
- ➖ it has a lot more dependencies (all potentially needed plugins)

please make sure to try out both approaches. it should also be possible to adjust the first approach (with fast-async) to only enable babel transpilation if Node is below a certain version.

**Comment by Turbo87** [comment]
@ember-cli/core has anyone tried this?

**Comment by stefanpenner** [comment]
@Turbo87 I have not, but can. Anything specific I should look at, or mostly just around debugging?

**Comment by Turbo87** [comment]
> Anything specific I should look at

just the normal development workflows that you have. whether anything is more complicated or actually easier then before using this approach.

and as mentioned in https://github.com/ember-cli/ember-cli/pull/6822#issuecomment-283804129 I'm no longer certain if we should use `babel-preset-env` or if we should just use the `fast-async` plugin and disable Babel transpilation completely if the local Node version supports native async/await.

**Comment by rwjblue** [comment]
Honestly, I'm happier with the `co` setup than with transpiling, so I think we should just close this...

Feel free to reopen if you disagree...

**Pull request closed without merging**
