### PR TITLE
Add .vscode debugging

### PR DESCRIPTION
**Pull request by oligriffiths**
This PR adds a .vscode launcher to enable vscode node debugging.

### CODE REVIEW

**Comment by Turbo87** [comment]
I tend to agree with @rwjblue. Otherwise I'd commit my IntelliJ files too :P

**Comment by kellyselden** [comment]
Fair enough :)

**Comment by oligriffiths** [comment]
In which case should this dircase from be git ignored?

**Comment by kellyselden** [comment]
From your system gitignore, yes.

**Pull request closed without merging**
