### PR TITLE
[Documentation] adding new ember new and ember addon diffs

### PR DESCRIPTION
**Pull request by kellyselden**
A continuation of #3559. Keeping up with the commit history.

### CODE REVIEW

**Comment by kellyselden** [comment]
Thanks @rwjblue.

**Comment by stefanpenner** [comment]
@kellyselden you are a scholar and a gentleman. 

we should likely include this in the release notes as well.

@kellyselden i'll give you the needed permissions to add this to the release notes.

**Comment by kellyselden** [comment]
Thank you @stefanpenner. I accepted the invite, but I don't see the Edit button on the release notes yet. Is [this](https://github.com/ember-cli/ember-cli/releases/tag/v0.2.1) the right place to do it?

**Comment by stefanpenner** [comment]
try now

**Comment by kellyselden** [comment]
Now I see it. Thanks.

**Comment by kellyselden** [comment]
@stefanpenner I added the commit diffs to the release notes back to 0.0.42.

**Pull request merged**
