### PR TITLE
Revert "Remove `ember update` mention in update-checker"

### PR DESCRIPTION
**Pull request by kellyselden**
Reverts ember-cli/ember-cli#4590

### CODE REVIEW

**Comment by kellyselden** [comment]
io.js keeps failing. This revert should be safe though, so I'm confused. Time for bed.

**Comment by stefanpenner** [comment]
Maybe 3.0 iojs and ember cli have some issues. I'll check in the Am.

**Comment by kellyselden** [comment]
Even though iojs is failing, I feel inclined to merge this so that we aren't broken anymore.

**Comment by stefanpenner** [comment]
I'll look into io once im at work today.

**Pull request merged**
