### PR TITLE
Release `1.13.13`

### PR DESCRIPTION
**Pull request by twokul**

### CODE REVIEW

**Comment by stefanpenner** [comment]
LGTM  - @rwjblue r?

**Comment by stefanpenner** [comment]
likely should bump ember-cli-sri

**Comment by twokul** [comment]
> likely should bump ember-cli-sri
I thought we were still waiting on it, will do

**Comment by rwjblue** [comment]
Need to mention the loader.js and ember-cli-sri changes in the changelog.

**Comment by rwjblue** [comment]
Sorry, meant the "users changes" section (above the listing)

**Comment by rwjblue** [comment]
r+ - :shipit:

**Comment by stefanpenner** [comment]
:shipit:

**Pull request merged**
