### PR TITLE
Use shorthand ES6 re-export for addon-imports as well, which landed in #3690

### PR DESCRIPTION
**Pull request by jayphelps**
Continues work from #3851

### CODE REVIEW

**Comment by stefanpenner** [comment]
thanks

**Comment by jayphelps** [comment]
appveyor on Windows seems to be having an aneurysm...

**Comment by stefanpenner** [comment]
ya, we need to rely on more async rimrafing...

**Comment by jayphelps** [comment]
@stefanpenner I've kicked appveyor again and still no dice. Any thoughts?

**Comment by stefanpenner** [comment]
The issue is likely unrelated as this seems to be failing regardless. I'll dig into the windows issue later today

**Pull request merged**
