### PR TITLE
[ENHANCEMENT] Make `EMBER_CLI_INJECT_LIVE_RELOAD_BASEURL` configurable

### PR DESCRIPTION
**Pull request by jbescoyez**
See: rwjblue/ember-cli-inject-live-reload#24

### CODE REVIEW

**Comment by jbescoyez** [comment]
Related to https://github.com/rwjblue/ember-cli-inject-live-reload/pull/24

**Comment by stefanpenner** [comment]
Seems ok, but needs a test

**Comment by jbescoyez** [comment]
@stefanpenner Test added

**Comment by stefanpenner** [comment]
LGTM

**Comment by stefanpenner** [comment]
oops sorry for letting this one linger..

@homu +r

**Comment by jbescoyez** [comment]
@stefanpenner What's the next step with this one?
Also, do you have merge rights to rwjblue/ember-cli-inject-live-reload#24 ?

**Comment by stefanpenner** [comment]
@homi r+

**Comment by rwjblue** [comment]
https://github.com/rwjblue/ember-cli-inject-live-reload/pull/24 has been merged and released as 1.4.0.

**Comment by rwjblue** [comment]
@jbescoyez - I'm not 100% sure why, but it seems that @homu is not running this for us.  Would you mind rebasing against master to force a re-run of the test suite?

**Comment by barosl** [comment]
That's indeed strange, [the queue](http://homu.io/q/ember-cli/ember-cli) indicates that this PR isn't approved yet. Maybe Homu failed to receive some webhook messages from GitHub? What does "recent deliveries" [in the repository settings](https://github.com/barosl/homu/settings/hooks) say?

**Comment by rwjblue** [comment]
@barosl - Thanks for chiming in! 

screenshot

I'm redelivering that errored hook now...

**Comment by rwjblue** [comment]
Redelivering results in the same error.

**Comment by rwjblue** [comment]
JSON Payload that is erroring is [here](https://gist.github.com/rwjblue/b0c0b5ab942f71f00d15) (in case you want to test further).  

---

Complete WAG: could it be related to the backticks in the PR title?

**Comment by barosl** [comment]
Hmm, it seems that the payload that caused 500 isn't the approval comment. Its body is

> @jbescoyez - I'm not 100% sure why, but it seems that @homu is not running this for us.  Would you mind rebasing against master to force a re-run of the test suite?

and I think this is a separate bug. Could you paste the payload delivered at 2015-12-08 02:54 UTC?

**Comment by rwjblue** [comment]
Looks like @stefanpenner typoed the comment initially (as `@homi`) and then must have corrected: https://gist.github.com/rwjblue/6097f8a6e743fd2a7a54

**Comment by barosl** [comment]
Ah, that should be the problem. GitHub sends webhook messages only for new comments, not for modified comments. It is a bit unfortunate that GitHub doesn't have such a "change" event.

**Comment by stefanpenner** [comment]
@homu r+

Ya that's a bummer that change events don't fire. Good to know

**Comment by barosl** [comment]
Also, the 500 error seems to have been caused by the word "force" in the original comment being parsed as a command. There's a Homu command named `force`, but it is only applicable to Buildbot-configured repositories. So it raised an exception on this travis-configured repository.

**Comment by jbescoyez** [comment]
I've rebased on master and fixed some tests. Any idea why AppVeyor tests are still failing?

**Comment by rwjblue** [comment]
@jbescoyez - It happens :smiling_imp:.  AppVeyor is passing for 4.2, which means that the other failures are almost certainly just AppVeyor weirdness.

**Comment by rwjblue** [comment]
@homu r+

**Comment by stefanpenner** [comment]
yay

@barosl we <3 @homu ! (my only wish is likely complicated, but to support both travis + appveyor: https://github.com/barosl/homu/issues/87)

**Pull request merged**
