### PR TITLE
Add ability to specify a build path for running tests

### PR DESCRIPTION
**Pull request by trentmwillis**
Addresses #4872. Adds the `--path` option to allow you to run the tests from a previous build of the application.

### CODE REVIEW

**Comment by stefanpenner** [comment]
I like where this is going. Instead of using run command, can you use the ember helper instead? It does its thing much faster. Let me know if you have questions

**Comment by kellyselden** [comment]
The ember test helper currently has a problem generating the artifacts after build, @trentmwillis by all means try using it on both your calls, but you might only get it working on the second instance, needing to leave runCommand on the first.

**Comment by stefanpenner** [comment]
Ah. We should figure out what and fix it

**Comment by trentmwillis** [comment]
@kellyselden seems to be working for me. Only issue is that the output string (`result.ui.output`) doesn't seem to contain any information from the test run so the assertions fail. I can see the tests ran in the console output though, thoughts?

**Comment by kellyselden** [comment]
@trentmwillis I don't have any ideas without a deeper dive.

**Comment by trentmwillis** [comment]
Okay, I'll keep looking into it. It seems that the testem/phantom output isn't written to the output stream that is fed into the UI.

**Comment by trentmwillis** [comment]
Updated to use the `ember` helper. Apparently the `MockUI` used under the hood for the `ember` command doesn't capture all writes to `stdout` which is why it wasn't working before. Left a todo note to fix it later.

**Comment by trentmwillis** [comment]
@stefanpenner @kellyselden I believe I got all the tests working for this but AppVeyor seems to be having a hard time. May need to be restarted.

**Comment by kellyselden** [comment]
restarted appveyor

**Comment by stefanpenner** [comment]
@chadhietala please use homu

**Pull request merged**
