### PR TITLE
BUGFIX: Clear project.configCache before starting the build

### LINKED ISSUE #8478: Changes in environment.js applied only on second save
I have properties defined in ```config/environment.js```, i.e. ```testProperty``` with value 1:
```
'use strict';
module.exports = function(environment) {
  let ENV = {
    testProperty: 1,  
    modulePrefix: 'testapp2',
    environment,
    rootURL: '/',
    locationType: 'auto',
...
```
To illustrate the problem I import ```ENV``` from config in application controller and show the current value of ```ENV.testProperty``` in the application template. 
Changing the value of ```testProperty``` from 1=>2 triggers a live reload, but the value shown in the browser is still "1" instead of "2" as expected. When changing the value from 2=>3, live reload is triggered again but not "3" as expected but "2" is shown (the value from the update before the last change).
Additional information: 
- when I add a ```console.log(ENV.testProperty')``` at the end of ```config/environment.js``` the console shows the (correct) current number twice before "Build successful".
- when I change any other file leading to a live reload, the current state of ```environment.js``` is still not reflected in the application. I have to trigger a second save on ```environment.js``` to get the correct content.
- restarting ```ember s``` always shows the current value correctly.

I noticed this with ember-cli@3.8.1 but checking with ember-cli@3.7.1 shows the same behaviour. It might be relevant that I'm working on **windows**.

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 3.8.1
http_parser: 2.7.0
node: 8.9.3
v8: 6.1.534.48
uv: 1.15.0
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.25.0
openssl: 1.0.2n
icu: 59.1
unicode: 9.0
cldr: 31.0.1
tz: 2017b
os: win32 x64
6.8.0
1.3.2
```

### PR DESCRIPTION
**Pull request by colenso**
Fixes #8478.
Fixess https://github.com/ember-cli/ember-cli/issues/8782.

The problem I noticed was that get-serve-url would access project.config after finalizeBuild and hence the config would get cached and would be used in the next build. Hence each build was using the previous build's config.
This PR simply clears the project.configCache before the build is started.

### CODE REVIEW

**Comment by colenso** [comment]
Can someone help me out with tests? @locks perhaps?

**Comment by sly7-7** [comment]
Since the time I use ember-cli, I just always assumed it was "normal" to have to `ember s` again when changing the environnment.js file.

**Comment by colenso** [comment]
Yes. But it always wasn't so. And I find it very handy to have it rebuild automatically when I change something in the environment.js file

**Comment by rwjblue** [comment]
I definitely agree that the behavior is important to fix, but we do need some tests.

I think you could add a test to this file, like this test:

https://github.com/ember-cli/ember-cli/blob/6252533f5cf9ba1e77528f7711fe311324901a29/tests/unit/broccoli/builder-test.js#L32

In your case, you don't need a special broccoli plugin (like that test I linked above). I think you mostly just want to ensure that the config content is correct per build.

**Comment by bertdeblock** [comment]
Going to close for now, due to inactivity.

**Pull request closed without merging**
