### PR TITLE
ensure at-least npm v3

### PR DESCRIPTION
**Pull request by stefanpenner**

### CODE REVIEW

**Comment by stefanpenner** [comment]
cc @Turbo87

**Comment by Turbo87** [comment]
@stefanpenner what's the reason for that?

**Comment by stefanpenner** [comment]
@Turbo87 node 0.10.x installs npm v1 by default, which is riddle with bugs. Which caused this failure: https://github.com/ember-cli/ember-cli/pull/5391

**Comment by kellyselden** [comment]
A couple questions from the uninformed:
Noticeable test time increase?
Included in the node_modules cache after first run?

**Comment by Turbo87** [comment]
@stefanpenner could you add a comment to that line explaining what it does? I'm sure I've forgotten about it two weeks from now :wink:

**Comment by stefanpenner** [comment]
> Included in the node_modules cache after first run?

yes

> Noticeable test time increase?

Yes, but I'm unsure if we have an option, as without this we are subject to npm 1.x issues in our tests. We are still going to support node 0.10.x (people like ghost, and my employer still need it).

**Comment by kellyselden** [comment]
@stefanpenner Looks like the bases are covered, so I'm a :+1: after a comment.

**Comment by stefanpenner** [comment]
the hit for older npm -> npm v3 appears to be about 1m. But that was without cache prime, futures runs should demonstrate this better.

**Comment by Turbo87** [comment]
@homu r+

**Pull request merged**
