### PR TITLE
ESLint: Use "chai-expect" plugin

### PR DESCRIPTION
**Pull request by Turbo87**
This PR adds the "chai-expect" plugin to ESLint that checks for `expect(...)` usage without any assertions. All resulting lint issues have be resolved, but let's see if Travis finds any tests that are broken now...

### CODE REVIEW

**Comment by Turbo87** [comment]
looks like we have 13 failing tests now:

1. Acceptance: ember generate adapter application cannot extend from --base-class=application:
2. Acceptance: ember generate adapter foo cannot extend from --base-class=foo:
3. Acceptance: ember new ember new without skip-git flag creates .git dir:
4. Acceptance: ember new ember new with --directory uses given directory name and has correct package name:
5. Acceptance: ember generate pod adapter application cannot extend from --base-class=application:
6. Acceptance: ember generate pod adapter foo cannot extend from --base-class=foo:
7. Unit: CLI ember &lt;invalid command&gt;:
8. Unit: CLI Global command options --verbose option parsing sets process.env.EMBER_VERBOSE_${NAME} for each space delimited option:
9. Unit: CLI Global command options --verbose option parsing ignores verbose options after --:
10. Unit: CLI Global command options --verbose option parsing ignores verbose options after -:
11. generate command rethrows errors from beforeRun:
12. test command _generateCustomConfigs when launch option is present, should be reflected in returned config
13. Acceptance: brocfile-smoke-test specifying partial `outputPaths` hash deep merges options correctly

**Comment by stefanpenner** [comment]
:+1:

**Comment by Turbo87** [comment]
Three failing tests left. I might be able to tackle the first two, but I fail to understand what the `brocfile-smoke-test` is supposed to check and/or why it's failing. Would love to get some help on that!

**Comment by stefanpenner** [comment]
I'll take a look in the morning, if I forget please feel free to ping me.

**Comment by Turbo87** [comment]
@stefanpenner ping :wink:

**Comment by Turbo87** [comment]
@stefanpenner should I `skip()` the failing test for now and open a separate issue for fixing that? The rest of the stuff is ready for merging.

**Comment by kellyselden** [comment]
@Turbo87 I'm :+1: for skip with a comment, since it was never working anyways.

**Comment by Turbo87** [comment]
@kellyselden done. feel free to r+

**Comment by stefanpenner** [comment]
r+

**Comment by stefanpenner** [comment]
@homu r+

**Comment by Turbo87** [comment]
oh come on...

@homu retry

**Comment by Turbo87** [comment]
:tada:

**Pull request merged**
