### PR TITLE
move help output tests from acceptance to unit

### PR DESCRIPTION
**Pull request by kellyselden**
This moves almost all help acceptance tests into the unit test category. This is only the first pass. I plan to get more fine grained to find more testing gaps and speed gains.

This should shave some time off of CI.

### CODE REVIEW

**Comment by stefanpenner** [comment]
Lvgtm

**Comment by kellyselden** [comment]
The coverage decrease should be fixed in my coming PRs. I vote for merging now so the next diff isn't as extreme, @stefanpenner ?

**Comment by stefanpenner** [comment]
> I vote for merging now so the next diff isn't as extreme, @stefanpenner ?

:+1:

**Comment by kellyselden** [comment]
:smile:

**Pull request merged**
