### PR TITLE
Testem v0.9.5

### PR DESCRIPTION
**Pull request by johanneswuerbach**
Changes:

* Node v4 support
* Parallel runs: Attribute logs and results to the correct browser
* Show Error Messages correctly in dev
* Allow to pass custom ids to launchers

### CODE REVIEW

**Comment by stefanpenner** [comment]
> Parallel runs: Attribute logs and results to the correct browser

Is there a guide we can provide to instruct ember-cli users to take advantage of this?

> Node v4 support

does this drop the native extensions or..

**Comment by johanneswuerbach** [comment]
> Parallel runs: Attribute logs and results to the correct browser

Is only a fix for the previously supported functionality of running multiple browser concurrently in CI mode (in dev this is the default). It can be tuned in your `testem.json` like ember is doing: https://github.com/emberjs/ember.js/blob/master/testem.dist.json#L5

All available options are listed here:
https://github.com/airportyh/testem/blob/master/docs/config_file.md

> does this drop the native extensions

Sadly not, we only test against v4 now and ignore the failing optional deps, so both patches (https://github.com/ember-cli/ember-cli/tree/v1.13.8/patches) are still required until socket.io is bumped (https://github.com/socketio/socket.io/issues/2245) or npm provides a nicer UX for failing optional deps.

Summary: This bump is only fixing some bugs

**Comment by stefanpenner** [comment]
@homu r+

**Comment by stefanpenner** [comment]
@homu r+

**Comment by stefanpenner** [comment]
rebase, master should now be green.

**Comment by ilkkao** [comment]
New socket.io 1.3.7 supports node 4 and installs cleanly. I tested with node 4.1.1.

**Comment by johanneswuerbach** [comment]
Rebased, a testem update is not required as it allows all socket.io 1.x releases.

**Comment by johanneswuerbach** [comment]
Rebased again and we are finally :green_heart:

**Comment by kellyselden** [comment]
@homu retry

**Comment by kellyselden** [comment]
@homu r+

**Pull request merged**
