### PR TITLE
Update to Ember 2.8.0.

### PR DESCRIPTION
**Pull request by rwjblue**
:tada:

### CODE REVIEW

**Comment by stefanpenner** [comment]
👍

**Comment by Turbo87** [comment]
@homu r+

**Comment by Turbo87** [comment]
since it is "only" the flaky `ember-fast-click` test failing I'd like to go ahead and merge this manually

**Comment by nathanhammond** [comment]
Hold please, I'll handle this during the release process! (As well as Ember Data.)

**Pull request closed without merging**
