### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by btecu**
Updated all dependencies that don't break any test. In general, most libraries have one documentation (not versioned) so it becomes useful to have an updated version.

The following libraries need manual intervention to be updated: `broccoli-clean-css`, `core-object`, `inquirer`, `lodash-node`, `markdown-it`, `markdown-it-terminal`, `nock`.

### CODE REVIEW

**Comment by stefanpenner** [comment]
Awesome thanks. Want to open an issue for those outstanding updates?

**Comment by btecu** [comment]
Once I figure what the new updates are breaking (maybe some deprecated api), I'll push..

**Comment by stefanpenner** [comment]
Ah. Sorry I meant. Let's open an issue tracking that those still need to be updated. So we don't forget, and as we update them we can check off that list.

I'll be home soon, I can open it if you want

**Comment by btecu** [comment]
Ah, yes, I can do that.

**Comment by rwjblue** [comment]
We need to revert the update to glob.

**Comment by stefanpenner** [comment]
Because of the symlink thing?

**Comment by rwjblue** [comment]
yes

**Comment by rwjblue** [comment]
We need to audit all of our broccoli based deps, and ensure they are using `{ follow: true }` option before we can unlock.

**Comment by stefanpenner** [comment]
> We need to audit all of our broccoli based deps, and ensure they are using { follow: true } option before we can unlock.

does the new version work with `{follow: true }` ? I have some fixes to glob, I am curious if i need to also backport them...

**Comment by rwjblue** [comment]
The new version should properly follow symlinks with the `{ follow: true }` option, but that option needs to be passed by every one of our dependencies that use `glob`.  We likely just need to audit to get a list of our deps that use glob and update to pass `{ follow: true }`.

**Comment by stefanpenner** [comment]
opened a new issue: https://github.com/ember-cli/ember-cli/issues/4137

**Pull request merged**
