### PR TITLE
[ENHANCEMENT] Name blueprint in generate and destroy output message

### LINKED ISSUE #4307: Improve ember generate/destroy output
Each time a blueprint is invoked from within a ember generate command the `installing` message is displayed. But it's not a useful information. What do you think to instead show what is the command being executed? Something like this:

```sh
~ ember g resource foo
version: 0.2.7
installing model
  create app/models/foo.js
installing model-test
  create tests/unit/models/foo-test.js
installing route
  create app/routes/foo.js
  create app/templates/foo.hbs
installing route-test
  create tests/unit/routes/foo-test.js
```

### PR DESCRIPTION
**Pull request by trabus**
resolves #4307 

I also added a line to denote when the router is being modified. New output looks like:
```
installing route
  create app/routes/foo.js
  create app/templates/foo.hbs
updating router
  add route foo
installing route-test
  create tests/unit/routes/foo-test.js
```
```
uninstalling route
  remove app/routes/foo.js
  remove app/templates/foo.hbs
updating router
  remove route foo
uninstalling route-test
  remove tests/unit/routes/foo-test.js
```

### CODE REVIEW

**Comment by stefanpenner** [comment]
LGTM

**Comment by marcioj** [comment]
:+1:

**Comment by marcioj** [comment]
Thank you @trabus !

**Comment by trabus** [comment]
@marcioj no problem! Thanks for the suggestion!

**Pull request merged**
