### PR TITLE
[BUGFIX] Replace marked with markdown-it

### LINKED ISSUE #3455: Handle Marked ReDoS Vulnerability
We recently introduced [marked](https://github.com/chjj/marked) for better help documentation. A ReDoS vulnerability has been reported on this project and we should either fix marked or remove the dependency on it before releasing 0.2.0. 

/cc @trabus 

https://nodesecurity.io/advisories/marked_redos

### PR DESCRIPTION
**Pull request by trabus**
Fixes #3455 by removing `marked` and `marked-terminal` as dependencies and replaces them with `markdown-it` and`markdown-it-terminal`.

This PR focuses on getting the vulnerable dependency out of ember-cli. I will be following up later and will eventually remove the color parsing from ember-cli and move it into markdown-it-terminal.

### CODE REVIEW

**Comment by trabus** [comment]
@stefanpenner @rwjblue ready for review!

**Comment by rwjblue** [comment]
Nice!

**Comment by chadhietala** [comment]
:heart: @trabus

**Comment by stefanpenner** [comment]
rad!

**Comment by trabus** [comment]
It had a nice side effect of forcing me to publish my first npm package ever. Never had any reason to do so before.

**Comment by rwjblue** [comment]
@trabus - NICE!

**Pull request merged**
