### PR TITLE
Fixing path issue in test for AppVeyor.

### PR DESCRIPTION
**Pull request by gmurphey**

### CODE REVIEW

**Comment by stefanpenner** [comment]
Ah. Lgtm

**Comment by rwjblue** [comment]
Will let AppVeyor run before approving with @homu.

**Comment by stefanpenner** [comment]
Hopefully soon homu will work with appveyor

**Comment by gmurphey** [comment]
Not sure if these AppVeyor failures are legit?

**Comment by rwjblue** [comment]
Looks like node 4.2 passed on AppVeyor (the others had timeouts), so I'm good to go on this. 

Thanks again for tracking down the source of the failure. 

@homu r+

**Pull request merged**
