### PR TITLE
changed --insecure-proxy to --secure-proxy in ember serve command

### PR DESCRIPTION
**Pull request by badazz91**
see #6034

based on current `beta` branch.

### CODE REVIEW

**Comment by nathanhammond** [comment]
@homu r+

**Comment by badazz91** [comment]
ouh this PR wants to merge into `master`. Do I need to make one that wants to merge into `beta`?

**Comment by nathanhammond** [comment]
I missed that, hold on.

**Comment by nathanhammond** [comment]
@homu r-

**Comment by Turbo87** [comment]
> ouh this PR wants to merge into master. Do I need to make one that wants to merge into beta?

yes, that would be the goal 😉

**Comment by nathanhammond** [comment]
Too many betas and masters and not enough sleep. 😛 Solved, doing our typical merge up approach now.

Thanks @badazz91 for bringing this across the finish line!

**Pull request closed without merging**
