### PR TITLE
Changed uninstalling and remove wording for delete

### PR DESCRIPTION
**Pull request by RecoX**
Changed uninstalling and remove wording for delete to maintain coherence with the command name

### CODE REVIEW

**Comment by rwjblue** [comment]
Hmm, I don't have a _particular_ preference here but I don't exactly see `remove` as "incorrect".

@RecoX - Mind helping me understand the rationale of why `delete` is better than `remove`?

**Comment by stefanpenner** [comment]
Deleting does sound/read better in this context

**Comment by RecoX** [comment]
> Hmm, I don't have a _particular_ preference here but I don't exactly see `remove` as "incorrect".
> 
> @RecoX - Mind helping me understand the rationale of why `delete` is better than `remove`?

Is to maintain the word along the whole process, the command to delete something in ember is

`ember d component name` or `ember delete route name`

so that's why i change it, to easily remember the commands

a lot of times i tried with `ember u` or `ember r` because of this

**Comment by kellyselden** [comment]
It might be useful to compare to how git does it, which also uses "remove":

```
C:\code\ember-awesome-macros>git clean -fdx
Removing .vscode/
Removing dist/
Removing node_modules/
Removing tmp/
```

**Comment by rwjblue** [comment]
> ember d component name or ember delete route name

FWIW, the `d` in `ember d` doesn't stand for "delete" it is "destroy".

**Comment by locks** [comment]
I renamed to destroy to match the command as @rwjblue mentioned. Let me know what is necessary to move this forward, whether it's reverting to delete, or even keeping the current status quo!

**Comment by Turbo87** [comment]
IMHO "destroy" sounds quite aggressive... 🤔

**Comment by locks** [comment]
Closing due to inactivity.

**Comment by RecoX** [comment]
@locks  Just merge it 🥇

**Comment by locks** [comment]
@RecoX I'm not on the CLI team so I can't make the call 😅 There wasn't concensus on the change.

**Pull request closed without merging**
