### PR TITLE
add jshint helper command for tests

### PR DESCRIPTION
**Pull request by gabrielgrant**

### CODE REVIEW

**Comment by stefanpenner** [comment]
+1

**Comment by gabrielgrant** [comment]
Looks like the build is failing because of [a timeout](https://ci.appveyor.com/project/embercli/ember-cli/build/5244/messages) (or maybe just expected behavior but needing to switch to another plan?). It's not totally clear to me from the logs why it's taking so long, but I don't *think* it has anything to do with me...

**Comment by gabrielgrant** [comment]
Ok, yea, downloading the full log seems to show that some of the later tests (`addon-smoke-test` etc.) just take a really long time to run.

**Comment by stefanpenner** [comment]
mind trying a rebase, we fixed up several windows issues in the last few weeks.

**Comment by gabrielgrant** [comment]
@stefanpenner sure, done :)

(it's a really minimal change, so there wasn't any conflict)

**Pull request merged**
