### PR TITLE
Revert "adding PerBundleAddonCache feature"

### PR DESCRIPTION
**Pull request by mansona**
This reverts commit 22b799b51410546d8e07685c9b621da8c11998d7 which is the merge commit for https://github.com/ember-cli/ember-cli/pull/9487

~This is a very naive revert. I'm not really sure what I am looking at when I was resolving the conflicts 🙈 I kinda just wanted to see if this will pass CI and open the discussion~

So it turns out there was a lot of follow-on work on this feature and I needed to do a bit more of an involved revert 😫 I have no idea what I'm looking at, I'm just trying to pull out the whole feature (which is unlikely what we actually want) and to see if I can get the tests to still pass

(hopefully) Fixes https://github.com/ember-cli/ember-cli/issues/9606

### CODE REVIEW

**Comment by mansona** [comment]
On the plus this does seem to fix the issue when running it locally 😂

**Comment by ef4** [comment]
I am in favor of this reversion. I am very skeptical about the whole proxy-based thing and if I had seen it while it was happening I would have advised against it.

It broke ember-engines (https://github.com/ember-engines/ember-engines/pull/769) and required changes there.

It broke embroider (https://github.com/embroider-build/embroider/pull/941) and required changes there.

I suspect we will find more fallout as people test more addons. If we're going to incur this much addon ecosystem breakage, we should **fix the underlying problem instead of patching over it** with proxies. The underlying problem is that it makes no sense to instantiate addons per-consumption rather than per on-disk copy. The vast majority of addons don't care either way and we can automatically detect that they don't care. We even already have code for that, in embroider, that could also be used directly by ember-cli.

**Comment by mansona** [comment]
Thanks for the comment @ef4 🎉 I appreciate more of the context but also I'm glad that I'm not going crazy suggesting something like this 😂 

The question is: how do we move forward from here? Do we need to get more consensus to get this merged? I'll see if I can get CI passing so at least we're not going to have that holding us back, but other than that I am struggling to know what to do to help this get merged. 

I'm also concerned about a protracted discussion about this topic when we know it is currently breaking a huge part of the ecosystem 🙈

**Comment by mansona** [comment]
Oh actually it looks like CI is failing on master in the same place 🤔 https://github.com/ember-cli/ember-cli/runs/3438949128#step:5:1964

Do we know if embroider is working against ember-cli master right now? is it a known issue?

**Comment by kategengler** [comment]
embroider is not currently working against master, see https://github.com/ember-cli/ember-cli/pull/9597

**Comment by kategengler** [comment]
pinging @rwjblue as a reviewer here

**Comment by bertdeblock** [comment]
Is this PR still needed since a fix for #9606 was merged and released?

**Comment by kategengler** [comment]
I agree this is no longer needed since #9606

**Pull request closed without merging**
