### PR TITLE
Enable long stack stitching

### PR DESCRIPTION
**Pull request by stefanpenner**
not just for RSVP, but all forms of async (even for those deep in our dependency graph)

### CODE REVIEW

**Comment by rwjblue** [comment]
For those interested, `longjohn` is here: https://github.com/mattinsler/longjohn

I'm 👍  on this, seems like a good addition.

**Comment by stefanpenner** [comment]
failure seems unrelated...

**Comment by stefanpenner** [comment]
@rwjblue we can configure the separator between the original and stitched stack. Current it is `--------------------------------` is that fine?

**Comment by Turbo87** [comment]
> While it is very helpful in development and testing environments, it is not recommended to use longjohn in production. The data collection puts a lot of strain on V8's garbage collector and can greatly slow down heavily-loaded applications.

are we sure we want to do this? or is this just meant for `canary`/`beta`?

**Comment by stefanpenner** [comment]
@Turbo87 test failures suggest not, but i have hope :P

**Comment by stefanpenner** [comment]
rebased, going to investigate the previous test failures next.

**Comment by stefanpenner** [comment]
This may be causing a hefty slow-down. (Which isn't surprising) we could enable this as a flag or env variable?


```js
DEBUG_LONG_STOCK=true
```

**Comment by Turbo87** [comment]
question is if we should add the dependency for the 1% of all people that actually discover that env var. iirc NPM has optional dependencies though, so maybe envvar + optional dep might be a good idea here.

**Comment by stefanpenner** [comment]
> question is if we should add the dependency for the 1% of all people that actually discover that env var. iirc NPM has optional dependencies though, so maybe envvar + optional dep might be a good idea here.

todays optionalDependencies are very noisy, and the weight of this dependency is low. So I believe either we include it by default \w flag, or we don't include it at all.

**Comment by nathanhammond** [comment]
This is a pretty small change. The people who are likely to need it will also likely be debugging something else. Can we collapse this under an existing flag?

**Comment by stefanpenner** [comment]
This likely needs API design. I don't really need this, I can easily add it as i require it. If someone wants this to be easier for non-power users a design for how to enable it should be provided and we can revive.

**Pull request closed without merging**
