### PR TITLE
Revert "[PERF] Speed up package info cache"

### PR DESCRIPTION
**Pull request by rwjblue**
When this was included in locally `npm pack`'ed versions (while testing before publishing ember-cli@3.4.0), we always receive a warning RE: `node-pre-gyp` (a bundled dependency of fsevents) not being found. The optimization being reverted tells the PIC that there is _no_ nested `node_modules` (`NodeModulesList.NULL`) and we therefore always get the warning:

```
$ ember -v
WARNING:
WARNING: /Users/rjackson/src/sandbox/test-3-4/node_modules/fsevents:
WARNING:    Missing dependency 'node-pre-gyp'
```

---

@stefanpenner - I am happy to spend some cycles trying to bring this back in the next beta series (3.5.0-beta.x), but I am reverting it now so we can get 3.4.x out the door...

### CODE REVIEW

**Comment by stefanpenner** [comment]
Works for me, I’ll address the issue later this week.

The fact that we see that warning at all seems like another issue (but shouldn’t block this release)

Also what is pulling in fsevents at all, we should have no native dependencies...

**Comment by twokul** [comment]
> Also what is pulling in fsevents at all, we should have no native dependencies...

```
$ npm ls fsevents
ember-cli@3.4.1 /Users/alex.navasardyan/code/oss/ember-cli
├─┬ ember-cli-broccoli-sane-watcher@2.1.1
│ └─┬ sane@2.5.2
│   └── fsevents@1.2.4  deduped
└─┬ sane@3.0.0
  └── fsevents@1.2.4
```

**Comment by twokul** [comment]
once it's 🍏 I can merge and release.

**Comment by rwjblue** [comment]
```
$ npm ls fsevents
ember-cli@3.4.0-beta.3 /Users/rjackson/src/open-source/ember-cli
├─┬ ember-cli-broccoli-sane-watcher@2.1.1
│ └─┬ sane@2.5.2
│   └── fsevents@1.2.4  deduped
└─┬ sane@3.0.0
  └── fsevents@1.2.4
```

**Comment by stefanpenner** [comment]
Thanks, I’ll poke at sane tomorrow.

**Comment by rwjblue** [comment]
https://github.com/amasad/sane/blob/49f251a95e6db118ad71223b1eca93c876d9aacc/package.json#L55

**Comment by stefanpenner** [comment]
Looks like I have already poked at sane for this: https://github.com/amasad/sane/pull/97#discussion_r119133169

**Comment by stefanpenner** [comment]
I’ll explore restoring this this week. I guess we may need tests or something to catch extra warnings like this.

**Comment by stefanpenner** [comment]
@rwjblue sorry for the extra hassle

**Comment by rwjblue** [comment]
Restarted one of the CI jobs

**Comment by twokul** [comment]
silly npm, I had to purge all caches on Travis for tests to pass

**Comment by dcombslinkedin** [comment]
@rwjblue  or @stefanpenner , the current package-info-cache code doesn't distinguish between optional and required dependencies (you probably already knew that). If you or somebody wants to add that as a feature, sounds like a good idea. I'm still trying to understand some details of @stefanpenner's optimization, so I may just stay out of the way entirely on this one, unless there's something you'd like me to do.

**Pull request merged**
