### PR TITLE
Split website docs

### LINKED ISSUE #3307: [META] Improve docs structure
The emberjs.com guides will start using Ember CLI examples in the rewrite that is starting now (meta-issue: emberjs/website#1994). Tracking the ember-cli.com part of this effort in this issue. 

The idea for the final situation is that emberjs.com contains all info relevant for Ember app developers and ember-cli.com will focus on Blueprint and Addon developers.

We've had plenty of docs issues (#2589, #2120) but I want to have a sitemap which clearly states what goes where first, then we can look at implementation (perhaps reopening #2589).

### About
- Rationale
- Overview
- Community (Tutorials, Stackoverflow, GH, IRC)
- Contributing

### Guide (will move to emberjs.com)
- Installing (getting started)
- Creating your app (getting started, scaffolding, naming, ember data)
- Configuration (environments)
- Tests
- Managing dependencies (asset compilation, using addons)
- Upgrading Ember CLI
- Common issues (Editors, common issues, deployment issues)

### Addons
- What is an Addon (core concepts, architecture)
- Client-only or integrated (If people are just redistributing a component we should minimize their exposure to CLI internals IMO)
- Hooks (link to API docs)

### Blueprints
- What is a blueprint (core concepts, architecture)
- Hooks (link to API docs)

### Other changes
- Remove changelog (point to GH)
- Compress Overview + Why into few sentences on home

## Process
- Figure out how to easily publish API docs

### PR DESCRIPTION
**Pull request by joostdevries**
fixes #3307

Preview: http://ember-cli.joostdvrs.com/

This splits the site into (currently) three categories: home, user-guide and extending. I'm hoping to get this branch tidy over the weekend so we can only apply content fixes from that point on.

The `User Guide` will eventually be merged into github.com/emberjs/guides

#### Layout/structure
- [x] Figure out a nice/clean way to separate pages into sections
- [x] Update the homepage so it only shows the buttons to the sections + short text (overview)
- [x] Check whether the current permalinks are okay (they don't work perfectly at the moment anyway)
- [x] Check all CSS/SCSS
- [x] Embed top-level navigation in the navbar/nav menu

#### Content
- [ ] Maybe make a dedicated "Common issues" or FAQ page to handle all that sort of content, now it gets in the way of a clean guide

@chnn @jonharmon fyi

### CODE REVIEW

**Comment by joostdevries** [comment]
Screencaps of the wip

image

image

**Comment by joostdevries** [comment]
@stefanpenner some questions/proposals:
- Do we need to keep the changelog on the site? Can't we just have it in the github repo only? (Just like emberjs.com)
- I'd like to split the blueprint docs into a section on using them for the user guide (probably at the very beginning) and a section on creating them in the "Extending" section
- I'd like to trim down the content for the User guide. Right now there's so much information in there that it's hard to do a quick walkthrough. I'm not entirely sure how this can best be achieved but I think splitting specific use-case questions (eg. emblem, stylus etc.) out into something like an FAQ would probably be the best way to go.

**Comment by stefanpenner** [comment]
> Do we need to keep the changelog on the site? Can't we just have it in the github repo only? (Just like emberjs.com)

:+1: 

> I'd like to split the blueprint docs into a section on using them for the user guide (probably at the very beginning) and a section on creating them in the "Extending" section

An independent section sounds correct


> I'd like to trim down the content for the User guide. Right now there's so much information in there that it's hard to do a quick walkthrough. I'm not entirely sure how this can best be achieved but I think splitting specific use-case questions (eg. emblem, stylus etc.) out into something like an FAQ would probably be the best way to go.

either remove it, or maybe we need to create an appendix ?

**Comment by stefanpenner** [comment]
* we should add `stackoverflow` to "Talk to us here:"

* installing node should likely reference http://stackoverflow.com/questions/16724259/npm-command-sudo-or-not

**Comment by stefanpenner** [comment]
@joostdevries this looks lovely

**Comment by stefanpenner** [comment]
> Maybe make a dedicated "Common issues" or FAQ page to handle all that sort of content, now it gets in the way of a clean guide

i wonder if we should try to curate the stackoverflow stuff or not...

**Comment by stefanpenner** [comment]
@joostdevries this seems to have gone stale (i know you are quite busy with your startup) should we close and revisit at some future point in time?

**Comment by joostdevries** [comment]
Was thinking about it this weekend.. Could you leave it open for two more weeks? I'm slowly finding small pockets of precious time ;-)

**Comment by stefanpenner** [comment]
> Was thinking about it this weekend.. Could you leave it open for two more weeks? I'm slowly finding small pockets of precious time ;-)

yup not a problem :)

**Comment by joostdevries** [comment]
@stefanpenner Done! I think this is a nice iteration for now. After this I'll focus on moving user-guide content over to emberjs.com. http://ember-cli.joostdvrs.com/

**Comment by joostdevries** [comment]
@stefanpenner friendly ping

**Comment by stefanpenner** [comment]
thanks for the ping, reviewing now.

**Comment by stefanpenner** [comment]
it seems like on a large monitor, scrolling from the initial page results in the orange/red gradient covering the content

**Comment by stefanpenner** [comment]
LGTM, some comments:

* it isn't obvious that overview exists from the landing screen
* in the overview emberaddons should likely be mentioned, and mentioned before (or replacement of) broccol-plugins
* should the changelog be its own less emphazied section?
* lets remove the variable version of the es6 format from http://ember-cli.joostdvrs.com/user-guide/#using-modules its not what the generators provide, the true name is the module path anyways, no reason in potentially confusing users in which name is the canonical one

**Comment by stefanpenner** [comment]
some addition notes, but can likely be following up once this PR lands:

* it isn't obvious that overview exists from the landing screen
* in the overview emberaddons should likely be mentioned, and mentioned before (or replacement of) broccol-plugins
* should the changelog be its own less emphazied section?
* lets remove the variable version of the es6 format from http://ember-cli.joostdvrs.com/user-guide/#using-modules its not what the generators provide, the true name is the module path anyways, no reason in potentially confusing users in which name is the canonical one

* the "Cyclic Dependencies" assertion should be removed.
* http://ember-cli.joostdvrs.com/user-guide/#module-directory-naming-structure should end with an explaination that adding your own directory "just works" for example, adding app/services/name.js allows service:name to be resolved
* http://ember-cli.joostdvrs.com/user-guide/#resolving-from-template-helpers should remove partial/view/render and instead only mention the component helper


* "A common pattern with helpers WAS to define a helper to use your views (e.g. for a custom text field view, MyTextField a helper my-text-field to use it). It is advised to leverage Components instead. More concretely, instead of:"
* "Using global variables or external scripts" should instead instruct people to just reference them via `window.` or `self.` this makes it easily searchable, and doesn't require adding additional hinting rules


* http://ember-cli.joostdvrs.com/user-guide/#naming-conventions doesn't need import Ember in the adapter example
  - likely doesn't need to exist the way it does currently at all, instead the examples can be reduce to a single one, users can use generators to discover the tes.
  lets:
    * describe the resolution naming convetions
    * provide a single example
    * direct users to generators


* environments section should say that today the environments are limited to prod/dev/staging. This is updated on master, but not in the branch.
* deployments should direct people to ember-cli-deploy
* Symlinks on Windows should instead reference the MS addon.

**Comment by stefanpenner** [comment]
should likely adapt https://github.com/ember-cli/ember-cli/pull/4295

**Comment by joostdevries** [comment]
@stefanpenner http://ember-cli.joostdvrs.com/
- Added changelog link
- Made button for home
- Fixed mobile nav
- Merged other changes

**Comment by stefanpenner** [comment]
overview likely wants to be a button on the left nav

**Comment by stefanpenner** [comment]
otherwise looks good :shipit:

**Comment by joostdevries** [comment]
@stefanpenner home is the same button :-)

**Comment by stefanpenner** [comment]
> @stefanpenner home is the same button

home goes back to the "preview splash", it is somewhat strange that it does not go back to overview. I suspect it should always jump to overview

**Comment by stefanpenner** [comment]
let me also check mobile

**Comment by stefanpenner** [comment]
looks good on mobile, with the exception of the GH star button appears to wrap funny.

**Comment by joostdevries** [comment]
cool, will fix in a sec.. struggling with some nav issues

**Comment by joostdevries** [comment]
- Fixed menu
- Replaced star button with code from https://buttons.github.io/

**Comment by joostdevries** [comment]
Only thing I haven't fixed is that the mobile nav doesn't show the sub items on home (overview, changelog etc) but I doubt that's a real issue right now.

**Comment by stefanpenner** [comment]
> Only thing I haven't fixed is that the mobile nav doesn't show the sub items on home (overview, changelog etc) but I doubt that's a real issue right now.

they appear when clicked (atleast on my phone)

:shipit: when you are ready :)

**Comment by stefanpenner** [comment]
:dancers:

**Comment by joostdevries** [comment]
:tada: next up: actually working on the content :-)

**Pull request merged**
