### PR TITLE
Use symlink-or-copy so acceptance slow tests don't fail on windows

### PR DESCRIPTION
**Pull request by chadhietala**
Hopefully this fixes the Appveyor failures.

### CODE REVIEW

**Comment by chadhietala** [comment]
@jakecraige want to review?

**Comment by stefanpenner** [comment]
@chadhietala seems like a good addition, except this means our windows builds will not benefit from the fast symlinking. It is likely worth seeing if we can enable the windows linking code on CI (like http://www.ember-cli.com/#symlinks-on-windows) Maybe the appveyor folks can point us in the right direction.

**Comment by stefanpenner** [comment]
this is :+1: from me, although ^^ would be awesome as time permits.

**Comment by rwjblue** [comment]
Symlink or copy does symlink if possible on windows

**Comment by stefanpenner** [comment]
@rwjblue ya, we need to see if we can enable that mode on appveyor, by pulling the correct windows levers.

**Pull request merged**
