### PR TITLE
[ENHANCEMENT] Open default browser to express app on serve

### PR DESCRIPTION
**Pull request by jayphelps**
While this would be helpful for me, I'm not sure if this is ideal for a majority of people's workflow or just annoying.

### CODE REVIEW

**Comment by jherdman** [comment]
It may be a tad annoying for me. The majority of my development is done on a headless VM. I connect my browsers to it from outside of the VM.

**Comment by kellyselden** [comment]
Ditto. I develop and run ember serve on a Linux VM, and connect to it from Windows host browser.

**Comment by kellyselden** [comment]
I could see it as an opt-in feature though.

**Comment by stefanpenner** [comment]
> I could see it as an opt-in feature though.

:+1: maybe `--open` ?

then for those who always want it, they can insert it into there `.emberrc` file

**Pull request closed without merging**
