### PR TITLE
re-point ember-cli-portfinder -> portfinder

### PR DESCRIPTION
**Pull request by eriktrom**
- the official repo has been released to npm, point to it

cc @stefanpenner (should just be an easy merge)

### CODE REVIEW

**Comment by stefanpenner** [comment]
@eriktrom 

```
{ [Error: Cannot find module 'ember-cli-portfinder'] code: 'MODULE_NOT_FOUND' }
```

**Comment by eriktrom** [comment]
doh

**Comment by eriktrom** [comment]
my bad, fixed

**Comment by Turbo87** [comment]
@homu r+

**Comment by stefanpenner** [comment]
amazing, thank you very much @eriktrom !!

**Pull request merged**
