### PR TITLE
Bring tests jshintrc closer to app jshintrc

### PR DESCRIPTION
**Pull request by ef4**
These are both code-quality settings that have no reason to vary between app and tests, so I'm updating the tests version to match the app version.

### CODE REVIEW

**Comment by stefanpenner** [comment]
I like the approach,tests are unhappy and it needs a rebase

**Comment by ef4** [comment]
Rebased and fixed failures. The remaining test failure is also failing on master, I don't think it is related to this PR.

**Comment by stefanpenner** [comment]
Hmm strange. I'll poke around when I get home.

**Comment by rwjblue** [comment]
Its a race condition with the new `ember-cli-build.js` file tests.  @chadhietala have a chance to review?

**Comment by chadhietala** [comment]
I actually think there may be a race condition in the NPM client. As the failing test on 740274a should have never passed without https://github.com/ember-cli/ember-cli/pull/4348.

**Comment by rwjblue** [comment]
Yes the NPM pack race condition is a constant troll.

**Pull request merged**
