### PR TITLE
Extend from `Service` in service blueprint

### PR DESCRIPTION
**Pull request by ohcibi**

### CODE REVIEW

**Comment by jgwhite** [comment]
This will need to wait until we’re shipping 1.10 by default.

**Comment by ohcibi** [comment]
Whats blocking this?

**Comment by knownasilya** [comment]
[this](https://github.com/ember-cli/ember-cli/blob/master/blueprints/app/files/bower.json#L6)

**Comment by stefanpenner** [comment]
@rwjblue assigned to rob, as he is helping push that effort

**Comment by ohcibi** [comment]
whoops. Forgot the tests. Will add them asap.

**Comment by kimroen** [comment]
This should probably be included with `v0.2.0`. Also, we should remove the initializer from this blueprint.

**Pull request merged**
