### PR TITLE
[BUGFIX release] Fix toTree with custom paths. Closes #8128

### LINKED ISSUE #8128: [3.5.0] app.toTree not outputting broccoli-funnel anymore?
Here are the steps:
New project: `ember new xxx`
In project:
`npm i broccoli-funnel --save-dev`
`npm i moment-timezone --save`
Edit ember-cli-build.js:
`const Funnel = require('broccoli-funnel');`
...
```
  const momentTimezone = new Funnel('node_modules/moment-timezone/builds', {
    srcDir: '/',
    include: ['moment-timezone-with-data.min.js'],
    destDir: 'assets'
  });

  return app.toTree([momentTimezone]);
```
Build:
`ember b -dev`
Check dist folder:
image

No `moment-timezone-with-data.min.js`

I tried with other resources (jpegs, css, etc.), same deal.

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 3.5.0
http_parser: 2.8.0
node: 10.11.0
v8: 6.8.275.32-node.28
uv: 1.23.0
zlib: 1.2.11
ares: 1.14.0
modules: 64
nghttp2: 1.33.0
napi: 3
openssl: 1.1.0i
icu: 62.1
unicode: 11.0
cldr: 33.1
tz: 2018e
os: darwin x64
6.4.1
1.10.1
```

### PR DESCRIPTION
**Pull request by wagenet**

### CODE REVIEW

**Comment by wagenet** [comment]
Investigating the failing test.

**Comment by wagenet** [comment]
It's not clear to me why the tests are failing. If someone wants to point me in the right direction I'll fix them.

**Comment by rwjblue** [comment]
Updated to target `release` branch, and rebased.

**Comment by rwjblue** [comment]
Thank you!

**Comment by wagenet** [comment]
@rwjblue thank you for giving the initial direction!

**Pull request merged**
