### PR TITLE
Guard against rawArgs being undefined

### PR DESCRIPTION
**Pull request by chadhietala**
I'm not sure if this is the right fix for #3142. I'm not even sure `rawArgs` is used for since I ran a bunch of generators to see what it what it's value was. It seemed to always be `undefined`. @rwjblue, @stefanpenner, or @bcardarella can you drop some knowledge bombs on this?

This makes the message go away but I'm not sure what is the root cause. Traced it all the way back to `_locals`.  It only effects bower.

### CODE REVIEW

**Comment by cibernox** [comment]
I faced this too. My main suspect what the `normalizeEntityName: function() {},` of a blueprints of an addon I was installing.

Does that makes any sense?

**Comment by trabus** [comment]
I think this is related to some work on `ember init` that I did a while back. To allow a glob pattern to be used to define which files to init, a `targetFiles` array is passed in, in addition to the `rawArgs` [here](https://github.com/ember-cli/ember-cli/blob/master/lib/commands/init.js#L68) so we can use it for the message you're seeing.

I'm not sure why an addon install is coming up with 0 files to process, but that would definitely be the reason the message comes up. Checking for the existence of `rawArgs` is probably the easiest path to fixing it, but I'd definitely like to understand why an addon install is behaving that way.

**Comment by stefanpenner** [comment]
cc @jgwhite

**Comment by jgwhite** [comment]
Pretty sure @trabus is right and this is the correct fix. Merging.

**Comment by trabus** [comment]
I just figured out why the blueprint was being processed with no files: [it didn't have any](https://github.com/johnotander/ember-cli-gravatar/tree/master/blueprints/ember-cli-gravatar) to process. The blueprint simply installed a bower package.

**Pull request merged**
