### PR TITLE
Add `blockchain` support

### PR DESCRIPTION
**Pull request by Turbo87**
😁

### CODE REVIEW

**Comment by kellyselden** [comment]
Is it April already? 😄

**Comment by stefanpenner** [comment]
We should plan for the ICO...

**Comment by Turbo87** [comment]
by the time this goes into a stable release it will be April :trollface:

**Comment by Turbo87** [comment]
this was inspired by https://github.com/diesel-rs/diesel/pull/1540 btw 😉

**Comment by quaertym** [comment]
When are smart contracts coming for ember?

**Comment by Alonski** [comment]
This is the best PR. 
Now I can finally convince my company to use Ember!

**Comment by kellyselden** [comment]
BRB while I add coinhive to our dependencies...

**Comment by Alonski** [comment]
How many millions of users use Ember every day? Tomster has to make a living somehow. Good idea @kellyselden

**Pull request merged**
