### PR TITLE
Fix "command-ui" typos

### PR DESCRIPTION
**Pull request by Turbo87**
see https://github.com/ember-cli/ember-cli/pull/6475#pullrequestreview-10392745

### CODE REVIEW

**Comment by nathanhammond** [comment]
@homu r+

**Comment by rwjblue** [comment]
@Turbo87 - Can you create an issue to track adding tests that could have prevented this?

**Comment by Turbo87** [comment]
@rwjblue https://github.com/ember-cli/ember-cli/issues/6478

**Pull request merged**
