### PR TITLE
Adds missing step to run ember app

### PR DESCRIPTION
**Pull request by ale7714**
After doing ```ember new my-app``` and ```cd my-app```, also you need to do ```npm install && bower install``` to be able to run ```ember server``` without problems.

### CODE REVIEW

**Comment by jimbeaudoin** [comment]
Someone can correct me if i'm wrong but I think you are referencing something outdated? Because I use `ember-cli version: 0.2.3` and I don't need to do this. Both command are run for me. Which version are you using?

**Comment by ale7714** [comment]
@jimbeaudoin I'm using 
ember-cli version: 0.2.3
node: 0.12.2

And follow the started guide, without running npm install && bower install and got this error:
```
alexandras-mbp:test-app ale$  ember server
version: 0.2.3
Cannot find module 'ember-cli/lib/broccoli/ember-app'
Error: Cannot find module 'ember-cli/lib/broccoli/ember-app'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/ale/Dev/test-app/Brocfile.js:3:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

And I solved by running both command. Maybe I might be missing something?

**Comment by jimbeaudoin** [comment]
This is really strange and I don't know why you have this problem because both command are supposed to be executed for you by ember-cli. I will let someone more experienced than me help you because I really don't know why you have this problem. :( Sorry... For me both command are run by ember-cli when I execute the command `ember new myapp` but I'm not running Mac OS X. I'm on Ubuntu. But I think it should be the same thing. I have the same node & ember-cli version as you. Did you try removing ember-cli `npm uninstall -g ember-cli`, doing a `npm cache clean` reinstall `npm install -g ember-cli` ember-cli and retry? Maybe this could help. Sometimes things get messy with npm ... ;)

**Comment by ale7714** [comment]
I tried and nothing. I just thought the commands were missing on the guide, but maybe is something else.

**Comment by stefanpenner** [comment]
you wont need to doit after `ember new asdf` you will need to doit if you check out someone elses project.

**Pull request merged**
