### PR TITLE
Remove Ember Data from the addon blueprints

### PR DESCRIPTION
**Pull request by xcambar**
Following up on https://github.com/ember-cli/ember-cli/issues/4633,
this PR offers to remove Ember Data from the addon blueprints.

### CODE REVIEW

**Comment by stefanpenner** [comment]
LGTM

**Comment by rwjblue** [comment]
Looks like some test failures from this.  My best guess, is that some of the addon test fixtures (like [this one](https://github.com/ember-cli/ember-cli/blob/2e2b7f1946d516775bbd7dab87aaf5265ebdbc2a/tests/fixtures/addon/simple/bower.json)) are still specifying `ember-data` in `bower.json`, but it isn't installed because it isn't included in the default addon setup.

**Comment by xcambar** [comment]
All errors follow this pattern ([first occurrence in Travis](https://travis-ci.org/ember-cli/ember-cli/jobs/79190612#L2150-L2166)):

```
Missing bower packages: 
Package: ember-data
  * Specified: 2.0.0
  * Installed: (not installed)

Run `bower install` to install missing dependencies.

Missing npm packages: 
Package: ember-data
  * Specified: 2.0.0
  * Installed: (not installed)

Run `npm install` to install missing dependencies.
```

I'm unable to reproduce locally, but as I'm having trouble running the test suite (master and this PR), I guess it's not much of a surprise. Can you run tests locally?

As an example, `npm test tests/acceptance/blueprint-test-slow.js` passes locally but fails on Travis.

Note that if I inspect the `./common-tmp` folder during the tests, both `bower.json` and `package.json` are locally free of reference to Ember Data.

**Comment by xcambar** [comment]
I've generated an app and an addon with this PR and it did the job:

* ember-data __not__ available in addons
* ember-data available in apps

`ember build`, `ember test`, `ember serve` execute as expected as well.

I'm thinking of incriminating the tooling for the tests...

**Comment by xcambar** [comment]
That was harder than expected, but worth it.

__Shot version__: Reusing the apps' file structure from test to test was OK as long as the deps for an app were the same as the deps for an addon... and this PR changed just that with Ember Data.

__Long version__: in the code or on demand :smile: 

Why does AppVeyor fail? No idea, the log seems incomplete...

**Comment by xcambar** [comment]
> Your test run exceeded 120 minutes. 

@rwjblue @stefanpenner What could be the right approach for this?

**Comment by xcambar** [comment]
Reviving with a much smaller impact on the performance of the tests.

AppVeyor fails again, could this be related to https://github.com/ember-cli/ember-cli/pull/4807/files#diff-08b2003fcde5cdea29ec6e303e8f1522R140 ?

**Comment by rwjblue** [comment]
I restarted appveyor.

**Comment by xcambar** [comment]
Grrr... :angry: 

@raytiley maybe?

**Comment by xcambar** [comment]
From AppVeyor:

> Build execution time has reached the maximum allowed time for your plan (40 minutes).

**Comment by xcambar** [comment]
Closing for now. I will reopen with a clean (and most of all working :laughing: ) PR

**Pull request closed without merging**
