### PR TITLE
[WIP] adding --json to help

### PR DESCRIPTION
**Pull request by kellyselden**
ember-cli/rfcs#12

### CODE REVIEW

**Comment by stefanpenner** [comment]
cc @felixrieseberg

**Comment by felixrieseberg** [comment]
That will indeed make development of integrations a lot easier :+1:

**Comment by kellyselden** [comment]
@stefanpenner @felixrieseberg @lazybensch @kimroen This is at a point where it could use some eyes on it. Also if you could tag additional people vested in this, I would appreciate it.

**Comment by felixrieseberg** [comment]
Looks fantastic to me. From an integration point of view, being able to ask the CLI what commands are available will make a whole bunch of things a lot easier.

@stefanpenner and I have put it off a bit, but we're probably getting together next month or so to hack out a Visual Studio integration - and we should totally use this. On that note... want to join (virtually)?

**Comment by kellyselden** [comment]
@felixrieseberg Yeah sounds like fun.

**Comment by stefanpenner** [comment]
> @stefanpenner and I have put it off a bit, but we're probably getting together next month or so to hack out a Visual Studio integration

I'll be in SF tomorrow, wanna hack?

**Comment by felixrieseberg** [comment]
I'm in Seattle right now :/

**Comment by stefanpenner** [comment]
@felixrieseberg ah, another time then.

**Comment by thomassnielsen** [comment]
Very cool! Thanks a lot @kellyselden. :+1:

**Pull request merged**
