### PR TITLE
Add exclusion example for broccoli-funnel

### PR DESCRIPTION
**Pull request by ismay**
For clarity, as the current example only deals with file inclusion. See #4009 for related issue. A quick sketch, so let me know if there's anything that needs improvement.

### CODE REVIEW

**Comment by stefanpenner** [comment]
nice, should likely also include a link to the broccoli-funnel docs

**Comment by ismay** [comment]
Thanks! Did you still want that link to the docs btw? Because below my example there's already a link to the repo:

> Note: broccoli-static-compiler is deprecated. Use broccoli-funnel instead.

Which links to the docs as well, but could be changed to something more explicit like: "docs for broccoli".

**Comment by stefanpenner** [comment]
@ismay only if you think it will improve the doc story. If not, im fine without it.

**Comment by ismay** [comment]
Ok cool. Well I think it's fine, there is a link to the docs at the top and at the bottom and the examples cover both use cases now.

**Pull request merged**
