### PR TITLE
use native `Object.assign`

### PR DESCRIPTION
**Pull request by bekzod**

### CODE REVIEW

**Comment by bekzod** [comment]
needs restart

**Comment by kellyselden** [comment]
This should probably have an accompanying removal from ember-cli-lodash-subset

**Comment by bekzod** [comment]
> This should probably have an accompanying removal from ember-cli-lodash-subset
wanted to create issue once #7099 #7100 merged

**Comment by stefanpenner** [comment]
CI seems unhappy

**Comment by bekzod** [comment]
just needs restart

**Comment by stefanpenner** [comment]
restarting

**Comment by Turbo87** [comment]
@homu r+

thanks @bekzod!

**Pull request merged**
