### PR TITLE
Makes sure dependecies are loaded on demand

### PR DESCRIPTION
**Pull request by twokul**
results: https://gist.github.com/twokul/54542ed6783e20bbfd2f62bd9dfb89c7

before:

```
Total require(): 1375
Total time: 1.1s
```

after:

```
Total require(): 995
Total time: 832ms
```

depends on https://github.com/ember-cli/ember-cli/pull/6071
related to https://github.com/ember-cli/ember-cli/issues/6009

### CODE REVIEW

**Comment by nathanhammond** [comment]
LGTM assuming all tests pass. Has the tradeoff of making it a bit less clear which dependencies are pulled into any particular "module."

Do you have any benchmarks to be able to calculate the performance difference with this approach?

**Comment by Turbo87** [comment]
@homu r+

**Comment by Turbo87** [comment]
@twokul could I get you to use branches in a personal fork for PRs instead of branches in this repo? all the PR branches will get cloned too when someone forks this repo which looks a bit unclean and also makes Travis run the tests twice. @stefanpenner is an exception here because of the repo redirection rules that apply as long as he doesn't fork this repo again.

**Comment by rwjblue** [comment]
@twokul - What command were you running for the benchmark times? I see in the gist that you include the output, but not the command you were executing. I'm guessing it was `ember version`?

**Comment by twokul** [comment]
@Turbo87 sure thing, man. my bad

@rwjblue it is `ember v`

**Comment by twokul** [comment]
@Turbo87 should we cherry pick this commit into minor release, `2.6.3`, along with https://github.com/ember-cli/ember-cli/pull/6068?

**Comment by nathanhammond** [comment]
@twokul If you're doing a release with the event emitter, go ahead.

**Pull request merged**
