### PR TITLE
[WIP] Refactor livereload server

### PR DESCRIPTION
**Pull request by kolybasov**
PR for #6913.

- [ ] Refactor LiveReloadServer to LiveReloadAddon(middleware)
- [ ] Refactor tests for LiveReloadServer
- [ ] Update docs about live-reload port and host

I don't know how to refactor tests, they are a bit complicated for me.
Also I don't know how to test local version of ember-cli on real project.

Also live-reload port and live-reload-host will be redundant so we need to inform users about it. 

Any suggestions?

### CODE REVIEW

**Comment by stefanpenner** [comment]
@kolybasov very nice, I have been wanted to do this for ages but haven't been able to make the time, I am very happy you are able to help make it a reality!

> Also I don't know how to test local version of ember-cli on real project.

`npm link` should do the trick

1. in ember-cli type `npm link`
2. in your test app write `npm link ember-cli`

> Also live-reload port and live-reload-host will be redundant so we need to inform users about it.

👍 

> I don't know how to refactor tests, they are a bit complicated for me.

Ya understandable, they have grown a bit gnarly. Let me recommend:

1. remove (or update) tests related to the old way of doing live-reload
2. create new tests tuned specifically to how it works now.

If you run into issues, feel free to ask!

**Comment by kolybasov** [comment]
@stefanpenner thanks for the great tips! I am able now to test it locally. And found issue. `tiny-lr` overrides [listen](https://github.com/mklabs/tiny-lr/blob/master/lib/server.js#L66-L79) method on server and it never called by ember-cli. So I now trying to figure out how make it work and then will write tests.

Also I made changes to `ember-cli-inject-live-reload` to be able handle app host and port instead of live-reload and will submit PR later.

**Comment by Turbo87** [comment]
@stefanpenner @kolybasov any updates on this? is this blocked on something?

**Comment by kolybasov** [comment]
@turbo87 hi, sorry in vacation now, will continue on the weekend. Actually there is some blocker because tiny-lr tries to override listen method of the server and ember-cli will never call it so livereload stops working if use it ad middleware. But I will try to figure out something.

**Comment by kolybasov** [comment]
Took so long for me to help with this. Sorry 🙂 Closing in favor of #7508

**Pull request closed without merging**
