### PR TITLE
Replace builtin minification with ember-cli-uglify

### PR DESCRIPTION
**Pull request by jkarsrud**
This replaces the builtin broccoli-uglify-sourcemap minification with
ember-cli-uglify. This allows for other addons to run before the
minification step, which was not possible earlier.

This is the result of a discussion in #3103 about when to run certain types of addons.

### CODE REVIEW

**Comment by jkarsrud** [comment]
Hmm, I'm not sure if this has done something to fingerprinting or not, but that test seems to fail... Any ideas?

**Comment by rwjblue** [comment]
@jkarsrud - fingerprinting needs to be done after minification (it is happening too early and the fingerprint does not match the files hash).  I opened an issue upstream with more details: https://github.com/jkarsrud/ember-cli-uglify/issues/1.

**Comment by jkarsrud** [comment]
@rwjblue Thanks for the feedback! I've updated the package and all tests are good locally, so just need CI to confirm :)

**Comment by rwjblue** [comment]
Looks great!  I'm going to wait to land this until after 0.1.10 is shipped (hopefully later tonight), then pull it in.

**Comment by rwjblue** [comment]
Nevermind, gonna pull this into 0.1.10 after all.

**Comment by eljusto** [comment]
How to perform minification in my app?
Before update I've just built my project with `-e production` but now it doesn't work.
So what should I do to use ember-cli-uglify?

**Comment by rwjblue** [comment]
@eljusto - All you need to do is add `ember-cli-uglify` to your project.  `npm install --save-dev ember-cli-uglify` should do the trick.

**Comment by eljusto** [comment]
Oh, thanks a lot. 
I've read the changelog and thought that `ember-cli-uglify` has been installed with`ember init` command.

**Comment by rwjblue** [comment]
@eljusto - Only if you accepted that change when reviewing the diffs (it is really easy to miss).

**Pull request merged**
