### PR TITLE
Cache `bower_components` in CI

### PR DESCRIPTION
**Pull request by seanpdoyle**
Enable directory caching of `bower_components`

### CODE REVIEW

**Comment by rwjblue** [comment]
:+1:

**Comment by stefanpenner** [comment]
kicking travis-ci

**Comment by seanpdoyle** [comment]
@rwjblue @stefanpenner this actually might be a bad idea, given the issues we've had on other repos.

**Comment by rwjblue** [comment]
Nearly all of the issues we have seen are related to NPM (unless I am remembering incorrectly).

Also, some large % of CI builds in a normal app or addon, will not be changing NPM/Bower deps and therefore would benefit from this caching...

**Pull request closed without merging**
