### PR TITLE
Tweak Error Message

### PR DESCRIPTION
**Pull request by stefanpenner**

### CODE REVIEW

**Comment by stefanpenner** [comment]
@mike-north I think this further aides on the "who is telling me this error" q. Thoughts?

**Comment by mike-north** [comment]
LGTM

**Comment by stefanpenner** [comment]
I have some larger ideas in this space. I'll update once they settle.

**Comment by rwjblue** [comment]
@stefanpenner - Any updates?

**Comment by stefanpenner** [comment]
I’m back from vacation now, I’ll work on this shortly.

**Comment by locks** [comment]
@stefanpenner hey :) is this still relevant?

**Comment by stefanpenner** [comment]
@locks most likely

**Comment by locks** [comment]
I have rebased to solve the conflict. Merging when green, though I'm curious about the larger ideas mentioned above!

**Pull request merged**
