### PR TITLE
Fix perf-guide to have correct file names for build visualization

### PR DESCRIPTION
**Pull request by kratiahuja**
I think this was renamed with the instrumentation API.

cc: @stefanpenner @rwjblue @hjdivad

### CODE REVIEW

**Comment by rwjblue** [comment]
Hmm. Looks like there are conflicts, can you rebase?

**Comment by kratiahuja** [comment]
@stefanpenner Thank you for fixing the merge conflicts!

**Comment by rwjblue** [comment]
@homu r+

**Comment by hjdivad** [comment]
thanks @kratiahuja!

**Pull request merged**
