### PR TITLE
remove pre-mature process.exit when existing `ember test —server`

### PR DESCRIPTION
**Pull request by stefanpenner**
This should prevent the tmp files from leaking in this scenario

### CODE REVIEW

**Comment by rwjblue** [comment]
The process.exit was added there to prevent an extra 10-12 second delay after quitting testem. Can you confirm that has not resurfaced with this change?

**Comment by stefanpenner** [comment]
> Can you confirm that has not resurfaced with this change?

its still present.

waiting to tests to exist > gigs of tmp dir leaks

**Comment by rwjblue** [comment]
> waiting to tests to exist > gigs of tmp dir leaks

LOL, we could always just tell the builder to cleanup directly (`builder.cleanup()`) and still exit...

Hopefully, we do not reintroduce that delay (many people will report the bug if we do)...

**Comment by stefanpenner** [comment]
> Hopefully, we do not reintroduce that delay (many people will report the bug if we do)...

then we will fix it

**Pull request merged**
