### PR TITLE
[BUGFIX] Add missing bind when server already in use

### PR DESCRIPTION
**Pull request by bdvholmes**
See 43a8a6d4dbf82a72ca574e4d53b49edca602d888

### CODE REVIEW

**Comment by bdvholmes** [comment]
Fixes #3519

**Comment by rwjblue** [comment]
ugh, thank you! Why didn't our tests catch this?

**Comment by rwjblue** [comment]
I thought https://github.com/ember-cli/ember-cli/blob/master/tests/unit/tasks/server/express-server-test.js#L122-L139 was testing this directly...

**Comment by bartocc** [comment]
I just stumbled on this on as well.
+1 for the missing bind

**Pull request merged**
