### PR TITLE
Update `ember-cli-preprocess-registry`

### PR DESCRIPTION
**Pull request by btecu**
This will get rid of the warning:

`warning ember-cli > ember-cli-preprocess-registry > broccoli-funnel > exists-sync@0.0.4: Please replace with usage of fs.existsSync`

Thanks @Turbo87!

### CODE REVIEW

**Comment by btecu** [comment]
Depends on a new release of `ember-cli-preprocess-registry` , however, it would be good to get this in for `3.8.0` release.

**Comment by stefanpenner** [comment]
CI seems unhappy

**Comment by btecu** [comment]
@stefanpenner Can you release a new version of `ember-cli-preprocess-registry`? Version `3.2.0` had an issue. I'll update this pull request afterwards.

**Comment by stefanpenner** [comment]
just cut ember-cli-preprocess-registry@4.0.0 as it dropped support for old node versions. let me know if there are any issues.

**Comment by Turbo87** [comment]
@stefanpenner AFAIK @rwjblue had a blocking reason for not releasing 4.0.0 yet...

**Comment by stefanpenner** [comment]
@Turbo87 that sounds unfortunate, is there an issue/note in-regards to this?

**Comment by stefanpenner** [comment]
@Turbo87 should we yank?
cc @rwjblue I'm not sure if the release was appropriate or not? I'll need your input.

**Comment by stefanpenner** [comment]
Since it seems it may have been a mistake ive unpublished:

```
npm unpublish ember-cli-preprocess-registry@4.0.0
- ember-cli-preprocess-registry@4.0.0
```

**Comment by Turbo87** [comment]
unfortunately, I don't know the specifics, I just remember that he mentioned something like that on Discord a few days ago.

my plan was to release v3.2.x in a working state first, and then worry about the future 4.x releases.

**Comment by Turbo87** [comment]
please see https://github.com/ember-cli/ember-cli/issues/8457 on details why this is problematic

**Pull request closed without merging**
