### PR TITLE
ENHANCEMENT - don't compress responses with the x-no-compression response header

### PR DESCRIPTION
**Pull request by akatov**
I'm using an http-proxy to proxy to an endpoint intended for long polling. Now this endpoint writes a newline to the HTTP connection in regular intervals to make sure the connection stays alive.

The compression middleware however buffers the output produced by the endpoint (and the http-proxy) waiting for it to complete so it can compress it. This leads to the initiator closing the connection after not receiving back any data.

Having the proposed change in place lets me circumvent this problem by setting a header on the response object like this:
```js
// server/proxies/long-poll.js
module.exports = function(app) {
  app.use('/long-poll', function(req, res) {
    res.setHeader('x-no-compression', 'true');
    require('http-proxy').createProxyServer().web(req, res, {
      target: 'http://long-polling.service.lvh.me:1234'
    });
  });
};
```

### CODE REVIEW

**Comment by stefanpenner** [comment]
I was going to say, maybe expressjs/compression supports this already, but apparently there readme suggests your approach https://github.com/expressjs/compression#filter-1!

I am fine with this change, but it likely needs a unit test. Or it may regress overtime.

**Comment by stefanpenner** [comment]
Also looks like your tests are failing due to an eslint issue:

```
not ok 10 eslint should have no errors in lib
  Error: Code did not pass lint rules
  lib/tasks/server/express-server.js
    204:8  error  Missing trailing comma  comma-dangle
  
  ✖ 1 problem (1 error, 0 warnings)
  
      at Context.<anonymous> (node_modules/mocha-eslint/index.js:36:15)
```

locally, you can run `npm run lint` to check linting rules without having to run the full tests.

**Comment by akatov** [comment]
I fixed the eslint issue.
I'd also be grateful if you could point me to most fitting existing unit test to use as a blueprint for this feature?

**Comment by akatov** [comment]
OK, added a unit test. Not really sure how to check whether the actual body is compressed, so I'm just checking for the correct response headers...

**Comment by akatov** [comment]
rebased on v2.15.1

**Comment by rwjblue** [comment]
Thanks for working on this!

**Pull request merged**
