### PR TITLE
Switch PhantomJS to Firefox

### PR DESCRIPTION
**Pull request by kellyselden**
This is the implementation of https://github.com/ember-cli/rfcs/pull/86.

~~I'd like #7064 to be resolved first.~~

### CODE REVIEW

**Comment by stefanpenner** [comment]
nice!

**Comment by stefanpenner** [comment]
thoughts:

* CI times seems slightly slower.
* should appveyor get similar treatment?

**Comment by kellyselden** [comment]
Ready for review now.

**Comment by kellyselden** [comment]
> CI times seems slightly slower.

That was brought up in the RFC https://github.com/ember-cli/rfcs/pull/86/files#r97205765. I guess the tradeoff is worth it to get a real browser?

> should appveyor get similar treatment?

How so? We don't send down any appveyor assets to apps and addons. The reasoning I've always thought is "We test Windows so you don't have to."

cc @stefanpenner

**Comment by stefanpenner** [comment]
> How so? We don't send down any appveyor assets to apps and addons. The reasoning I've always thought is "We test Windows so you don't have to."

Isn't one of the goals to eventually drop phantomjs altogether? If so, weening our appveyor.yml off it may also make sense?

**Comment by kellyselden** [comment]
That makes sense. We can make the switch in our CI files too.

**Comment by rwwagner90** [comment]
Should we perhaps use Chrome instead? I generally add this to my travis.yml:

```yml
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
```

**Comment by kellyselden** [comment]
@rwwagner90 There were some concerns brought up with Chrome in the RFC.

**Comment by rwwagner90** [comment]
@kellyselden I took a look at the RFC, was the concern you are referring to that `sudo: required` does not use container based infrastructure?

All the concerns in the text of the RFC itself, I believe, are not a problem. 

You can run it without installing it, if you just use the following:

```yml
sudo: required
dist: trusty
...
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
```

**Comment by kellyselden** [comment]
@rwwagner90 Some things I can think of: open source issues from RFC, need sudo, need trusty, using chromium instead of chrome.

**Comment by rwwagner90** [comment]
@kellyselden needing those things has not hindered me at all, but just my two cents. FF is okay with me, just wanted to ensure everyone was on the same page and realized Chrome was available without installing any addons or anything.

I don't know a lot about Travis, so if sudo and trusty cause issues, just please go ahead and disregard this suggestions 😄

**Comment by rwjblue** [comment]
As an aside, if you are using `--headless` you don't use `  - sh -e /etc/init.d/xvfb start`. Using the virtual frame buffer approach is much slower than phantomjs, whereas using the new `--headless` flag to chrome should be faster...

**Comment by rwwagner90** [comment]
@rwjblue I don't believe I am using `--headless`. I was not aware of it. Where does that go?

**Comment by Turbo87** [comment]
@kellyselden since Chrome headless is available on Travis now we should use that directly instead of using `xvfb`

Example at https://github.com/rust-lang/crates.io/pull/813

**Comment by rwwagner90** [comment]
@Turbo87  I tried out the headless stuff in an ember addon, and it worked as well, if you would like an ember example https://github.com/shipshapecode/ember-flatpickr/blob/master/testem.js and https://github.com/shipshapecode/ember-flatpickr/blob/master/.travis.yml

**Comment by rwjblue** [comment]
Agreed with @turbo87. We should use the new --headless stuff...

**Comment by rwwagner90** [comment]
Would a PR to do Chrome instead of Firefox be accepted? I'm happy to throw one together.

**Comment by Turbo87** [comment]
see #7148 😉

**Comment by rwwagner90** [comment]
Ahh, beat me to it!

**Comment by stefanpenner** [comment]
I believe (now that chrome has `--headless` that this may no longer be needed.

@kellyselden c/d?

**Comment by kellyselden** [comment]
Although I like rooting for the underdog, no need to run xvfb if we don't have to...

**Comment by jrowlingson** [comment]
@kellyselden this may be worth revisiting now that Firefox (56.0) supports [headless mode](https://developer.mozilla.org/en-US/Firefox/Headless_mode) via the [`-headless`](https://developer.mozilla.org/en-US/Firefox/Releases/56) flag on all platforms? After running the latest version (57.0) against our large-ish test suite I am seeing the performance now seems to be on par with Chrome. Travis `firefox: latest` is resolving to 55.0 currently but this is okay since this was when Linux support was added for the headless flag. I can submit a PR if there is interest.

**Pull request closed without merging**
