### PR TITLE
[bugfix release] remove MODEL_FACTORY_INJECTIONS

### PR DESCRIPTION
**Pull request by kellyselden**
This is still giving deprecations in new 2.14 apps. We should promote this to release hotfix.

### CODE REVIEW

**Comment by rtablada** [comment]
@kellyselden good idea on releasing a hotfix release.

From an optics and training standpoint it is confusing to new developers to start new applications with a deprecation warning.

**Comment by rtablada** [comment]
@kellyselden or @Turbo87 any update on cutting a new version now that this blueprint update has been made?

**Comment by kellyselden** [comment]
No blockers that I know of, @ember-cli/core ?

**Comment by Turbo87** [comment]
would like to solve a few other issues too, but we can always do another release :)

**Pull request merged**
