### PR TITLE
Pass baseUrl to the router's rootUrl, resolves redirect issues

### PR DESCRIPTION
**Pull request by knownasilya**
Fixes issues with plugins like ember-simple-auth when they want to reload the page.

:warning: Needs tests still.

### CODE REVIEW

**Comment by rwjblue** [comment]
I am under the impression that this is only valid for certain location types.  We need to confirm all combinations of `history` and `hash` location type both with a baseUrl and without before merging...

**Comment by knownasilya** [comment]
@rwjblue are there tests related to this here or in the ember repo?

**Comment by rwjblue** [comment]
We should add tests here for this. 

Ember's tests are completely browser based and testing history location and reloading is not very simple in that context.

**Comment by stefanpenner** [comment]
can you add a more detailed commit message ? Ideally the motivation. A commit message containing exactly what the diff contains, isn't very valuable.

**Comment by runspired** [comment]
Cordova refreshing is pretty frustrating.

Refresh to the same location
```
window.location.href = window.location.toString();
```

Refresh to the base location
```
window.location.href = window.location.toString().substr(0, window.location.toString().indexOf('#'));
```

**Comment by jayphelps** [comment]
Just chiming in to mention [I think I understand his need and agree](https://github.com/emberjs/ember.js/issues/9501#issuecomment-61883135) though I'm not sure this will impact this PR, both https://github.com/emberjs/ember.js/issues/9501 and https://github.com/emberjs/ember.js/issues/5334 are outstanding issues related to how `baseURL` is sometimes used incorrectly in ember.

**Comment by knownasilya** [comment]
@stefanpenner I'm not even sure how to describe this change. Would something like the title of this PR work?

**Comment by jayphelps** [comment]
Remember folks, rootURL !== baseURL in embers internals.

**Comment by knownasilya** [comment]
So if you have `baseURL: '/dashboard/` in the config, this `rootURL` helps with the redirecting, but it adds a duplicate entry to the url, e.g. `/dashboard/dashboard/`

**Comment by knownasilya** [comment]
We need another solution to this issue..

**Comment by eddflrs** [comment]
@knownasilya any other ideas on how to resolve this issue? I'm also seeing the `/dashboard/dashboard/` issue that you mentioned.

**Comment by knownasilya** [comment]
Well for simple-auth, I added the following action in my application route:

```js
  sessionInvalidationSucceeded() {
      if (!Ember.testing) {
        window.location.replace('/dashboard');
      }
    }
```

Without setting that attribute in the router.

**Comment by knownasilya** [comment]
@stefanpenner thoughts on this? Should I just close it, seems like there is uncertainty about what each option does..

**Comment by stefanpenner** [comment]
@knownasilya haven't had time to look into this one yet, at some point i will dig into the baseURL rootUrl base href crap.

**Comment by stefanpenner** [comment]
this seems to have gone stale, i plan to revisit base/url stuff soon

**Pull request closed without merging**
