### PR TITLE
Run all tests again

### PR DESCRIPTION
**Pull request by marcioj**
Sorry, I forgot this `only` here :neutral_face:

### CODE REVIEW

**Comment by stefanpenner** [comment]
crap, how did i miss it.

**Comment by stefanpenner** [comment]
re-triggering appveyor.

@raytiley the output looks gnarly, is this to do with ps vs cmd ?

**Comment by raytiley** [comment]
@stefanpenner the output is likely messed up because of: http://help.appveyor.com/discussions/problems/1105-utf-8-characters-in-powershell-log

Not sure if this affects the tests or not.

**Comment by stefanpenner** [comment]
> @stefanpenner the output is likely messed up because of: http://help.appveyor.com/discussions/problems/1105-utf-8-characters-in-powershell-log

ah nice find.

> Not sure if this affects the tests or not.
>  Hide all checks

likely not, lets see :)

**Pull request merged**
