### PR TITLE
Use shorthand ES6 syntax for addon -> app re-exports

### PR DESCRIPTION
**Pull request by jayphelps**
Duplicate of #3739 but GitHub [won't allow you to reopen](https://github.com/isaacs/github/issues/361) PRs which have been force pushed.

### CODE REVIEW

**Comment by stefanpenner** [comment]
LGTM

**Comment by stefanpenner** [comment]
@jayphelps is this the only occurance of this pattern in the blueprints?

**Comment by jayphelps** [comment]
@stefanpenner nope, I didn't see the recently merged #3690, updating this PR to reflect. Will ping when green.

**Comment by jayphelps** [comment]
@stefanpenner ...wasn't done hehe was updating with #3690 changes.

**Pull request merged**
