### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by btecu**
Updated the dependencies for a new ember app (blueprint).

### CODE REVIEW

**Comment by stefanpenner** [comment]
Lvgtm

**Comment by btecu** [comment]
I've rebased. The test failing it's not related to this commit but possibly to the recent QUnit update.

**Comment by stefanpenner** [comment]
Strange. The qunit update was green when merged

**Comment by stefanpenner** [comment]
mind a rebase?

**Comment by btecu** [comment]
I had previously deleted the branch... :disappointed: 
See #4630.

**Pull request closed without merging**
