### PR TITLE
Addons: Replace most of .npmignore with a `files` key in the package.json file

### PR DESCRIPTION
**Pull request by Turbo87**
This should hopefully help with things like https://github.com/ember-cli/ember-cli/issues/6149 in the future.

/cc @stefanpenner @rwjblue @locks

### CODE REVIEW

**Comment by Turbo87** [comment]
Where I'm not sure about is the `config` folder. I've had a look at a few plugins listed at EmberObserver but haven't found any plugin that would need its `config` folder in a user project so I left it out.

**Comment by stefanpenner** [comment]
> Where I'm not sure about is the config folder. I've had a look at a few plugins listed at EmberObserver but haven't found any plugin that would need its config folder in a user project so I left it out.

yes this sounds correct.

**Comment by stefanpenner** [comment]
> This should hopefully help with things like #6149 in the future.

👍

**Comment by rwjblue** [comment]
> Where I'm not sure about is the config folder. I've had a look at a few plugins listed at EmberObserver but haven't found any plugin that would need its config folder in a user project so I left it out.

The [default implementation](https://github.com/ember-cli/ember-cli/blob/v2.8.0/lib/models/addon.js#L896-L904) uses `config/` folder.

**Comment by stefanpenner** [comment]
> The default implementation of the config hook in addons uses config/ folder.
> Add your review

how is this merged with the host app?

**Comment by rwjblue** [comment]
> how is this merged with the host app?

Done here: https://github.com/ember-cli/ember-cli/blob/v2.8.0/lib/models/project.js#L217-L229

**Comment by stefanpenner** [comment]
@rwjblue so for all addons (including nested) they are recursively merged or..

**Comment by kellyselden** [comment]
I love where this is going. Would like to see it rebased on #6272 (once that's merged) since I believe they share a lot of changes.

- [ ] rebase on #6272

**Comment by Turbo87** [comment]
Yeah, I'll rebase on whatever gets merged first :wink:

**Comment by nathanhammond** [comment]
@rwjblue is correct, `config` needs to be present.

@stefanpenner `this.addons` is already a flattened list of all of the addons in the application at the point of the `reduce`/`merge` operation.

**Comment by Turbo87** [comment]
okay. I've rebased, added the `config` folder, kept `/config/ember-try.js` in `.npmignore` and adjusted the expected test output.

**Comment by rwjblue** [comment]
> I've rebased, added the config folder, kept /config/ember-try.js in .npmignore 

Hmm. I was under the impression that `files` completely overrides `.npmignore`. Can you confirm via an `npm pack` of a generated addon with these updates, and confirm the files included in the tarball are correct?

**Comment by Turbo87** [comment]
https://docs.npmjs.com/files/package.json#files states: 

> You can also provide a ".npmignore" file in the root of your package or in subdirectories, which will keep files from being included, even if they would be picked up by the files array.

I've just tried it though and the `.npmignore` file doesn't seems to have any effect. Maybe I'm doing something wrong or my NPM is broken, but it doesn't seem to work according to its documentation... Investigating...

**Comment by Turbo87** [comment]
https://github.com/npm/npm/issues/7435

Conclusion: NPM has been broken since the dawn of time and we can't use this approach. The Module Unification RFC will unfortunately make things even worse when `*-test.js` files are included in the `src` folder.

**Comment by nathanhammond** [comment]
`ember publish` coming soon to an addon near you.

**Pull request closed without merging**
