### PR TITLE
Intent to replace terser with esbuild

### PR DESCRIPTION
**Pull request by NullVoxPopuli**
Draft PR to test things out.

Todos:

- [ ] acquire better package name from @alexlafroscia <3
  - [ ] (or rename to ember-cli-esbuild-minification, since this effort is minification focused to improve the build speed of production builds)
  - [ ] (or merge with @alexlafroscia's package, and only use a newly added minification api / addition)
- [ ] find & replace `@nullvoxpopuli/ember-cli-esbuild` with whatever that new package is
- [ ] see if expected source map behaviors are defined anywhere and ensure they still work
- [ ] ember-cli to drop support for node 12? EOL is 2022-04-30... so... I wonder what it would take for ember-cli-esbuild to support node 12 :thinking: 

Related PRs:
 - https://github.com/embroider-build/embroider/pull/1006
 - https://github.com/ef4/ember-auto-import/pull/467
 
 Stats from a pretty-large™ app internally:
 
 Instead of looking at total build time, I remembered that it'd be better to look at _total time spent minifying_.
 These stats came from the results of:

 ```bash
 DEBUG="*terser*" ember build --environment=production # in the terser / default branch
 DEBUG="*esbuild*" ember build --environment=production # in the esbuild branch
 ```

Stats Collection: https://docs.google.com/spreadsheets/d/1Q1Lhkt_N8LjfRFkrH06AXN3mxn5L2CGh4SW8tNSy720/edit#gid=0

- `assets/chunk.some-chunk.js` (~382KB) 
  - 92% faster (took 8% of the time terser did)
  - final size 373.25 KB vs terser's 372.52 KB 
- `assets/app-name.js` (~1078KB) 
  - 90% faster (took 10% of the time terser did)
  - final size 681.8KB vs terser's 656.72KB
- `assets/vendor.js` (~18MB) 
  - 95% faster (took 5% of the time terser did)
  - final size 9.39MB vs terser's 9.08MB 

_using esbuild@0.13.12_
[minification benchmark comparison between tools](https://github.com/privatenumber/minification-benchmarks/tree/cd3e5acb8d38da5f86426d44ac95974812559683#readme)

NOTE: `final size` is not gzipped or brotli'd. _just_ post-minification

### CODE REVIEW

**Comment by alexlafroscia** [comment]
I'm happy to donate the package name or something, if you can find a way to make it useful 😬 I never got around the fact that decorators would need Babel still, so `esbuild` was unable to _replace_ Babel, which was my original goal.

If you can find some other useful thing that `esbuild` can do for the community, I'm happy to let you take the package name and run with it 🤷‍♂️

**Comment by NullVoxPopuli** [comment]
looks like they've recentlyish added support for decorators? https://github.com/evanw/esbuild/issues/104

_but_, we have a bunch of other custom plugins, like, debug macros. But maybe if we can do all our custom stuff in babel, which is pretty light on cpu, compared to what's happening today), we'll still get some good perf gains?

**Comment by NullVoxPopuli** [comment]
More Stats

gzip numbers: `npx gzip-cli *.js`
brotli numbers: `npx brotli-cli compress --glob *.js`

Sizes read (in bytes) via: ` stat -c "%s %n" * | column -t -s' '`


## Small App (super tiny, where asset sizes really matter)

Uses the classic build, rather than embroider, so that `@nullvoxpopuli/ember-cli-esbuild` works. Embroider needs different work done, and isn't compat with logging from `DEBUG="*terser*"` or `DEBUG="*esbuild*"`. (which is fine, just makes getting these numbers trickier)

**Terser**
```
real	0m14.386s
user	0m30.152s
sys	0m1.505s

[finished]: assets/chunk.143.0c090a744ee05ae48f6d.js 2.385KB in 107ms
[finished]: assets/chunk.178.335ca8c243f46f651b47.js 1.559KB in 117ms
[finished]: assets/liquidity-pools-35d5f0cce0ac2be6567e44a2745cfdcf.js 25.328KB in 393ms
[finished]: assets/chunk.916.d4024ebad76bb031a0ac.js 77.966KB in 1081ms
[finished]: assets/chunk.177.c5a2711a46ed3ac52e04.js 206.276KB in 1626ms
[finished]: assets/vendor-e1d27526500d6415478654038a892a61.js 1783.469KB in 4366ms
```
```
2385     chunk.143.0c090a744ee05ae48f6d.js
972      chunk.143.0c090a744ee05ae48f6d.js.br
1073     chunk.143.0c090a744ee05ae48f6d.js.gz
206276   chunk.177.c5a2711a46ed3ac52e04.js
51197    chunk.177.c5a2711a46ed3ac52e04.js.br
58495    chunk.177.c5a2711a46ed3ac52e04.js.gz
808      chunk.177.c5a2711a46ed3ac52e04.js.LICENSE.txt
1559     chunk.178.335ca8c243f46f651b47.js
761      chunk.178.335ca8c243f46f651b47.js.br
816      chunk.178.335ca8c243f46f651b47.js.gz
77974    chunk.916.d4024ebad76bb031a0ac.js
22727    chunk.916.d4024ebad76bb031a0ac.js.br
25539    chunk.916.d4024ebad76bb031a0ac.js.gz
169      chunk.916.d4024ebad76bb031a0ac.js.LICENSE.txt
25328    liquidity-pools-35d5f0cce0ac2be6567e44a2745cfdcf.js
5200     liquidity-pools-35d5f0cce0ac2be6567e44a2745cfdcf.js.br
5965     liquidity-pools-35d5f0cce0ac2be6567e44a2745cfdcf.js.gz
1783471  vendor-e1d27526500d6415478654038a892a61.js
489393   vendor-e1d27526500d6415478654038a892a61.js.br
593623   vendor-e1d27526500d6415478654038a892a61.js.gz
```

then
```
yarn remove ember-cli-terser
yarn add --dev @nullvoxpopuli/ember-cli-esbuild
```

**ESBuild**
```
real	0m9.575s
user	0m16.905s
sys	0m1.195s

[finished]: assets/liquidity-pools-35d5f0cce0ac2be6567e44a2745cfdcf.js 27.026KB in 50ms
[finished]: assets/chunk.143.86bcba2a8b1a36db66ab.js 2.37KB in 43ms
[finished]: assets/chunk.916.d4024ebad76bb031a0ac.js 78.149KB in 67ms
[finished]: assets/chunk.178.24ed7d52fc741fb46632.js 1.55KB in 29ms
[finished]: assets/chunk.177.c5a2711a46ed3ac52e04.js 206.63KB in 65ms
[finished]: assets/vendor-e1d27526500d6415478654038a892a61.js 1813.821KB in 210ms
```

```
2370     chunk.143.86bcba2a8b1a36db66ab.js
969      chunk.143.86bcba2a8b1a36db66ab.js.br
1078     chunk.143.86bcba2a8b1a36db66ab.js.gz
206630   chunk.177.c5a2711a46ed3ac52e04.js
53584    chunk.177.c5a2711a46ed3ac52e04.js.br
60925    chunk.177.c5a2711a46ed3ac52e04.js.gz
808      chunk.177.c5a2711a46ed3ac52e04.js.LICENSE.txt
1550     chunk.178.24ed7d52fc741fb46632.js
744      chunk.178.24ed7d52fc741fb46632.js.br
819      chunk.178.24ed7d52fc741fb46632.js.gz
78149    chunk.916.d4024ebad76bb031a0ac.js
23414    chunk.916.d4024ebad76bb031a0ac.js.br
26343    chunk.916.d4024ebad76bb031a0ac.js.gz
169      chunk.916.d4024ebad76bb031a0ac.js.LICENSE.txt
27026    liquidity-pools-35d5f0cce0ac2be6567e44a2745cfdcf.js
5457     liquidity-pools-35d5f0cce0ac2be6567e44a2745cfdcf.js.br
6326     liquidity-pools-35d5f0cce0ac2be6567e44a2745cfdcf.js.gz
1813821  vendor-e1d27526500d6415478654038a892a61.js
508046   vendor-e1d27526500d6415478654038a892a61.js.br
613874   vendor-e1d27526500d6415478654038a892a61.js.gz
```

Gonna copy this all into a spreadsheet now and get some comparisons

**Comment by NullVoxPopuli** [comment]
TODO:
see what happens when you run terser on the esbuild output :upside_down_face:

**Comment by NullVoxPopuli** [comment]
More stats

```
┌────────────────────────────────┬────────────┬───────────┬───────────┬─────────────┬──────────────┬────────────────┬──────────────┬────────────────┬────────────┬─────────────┬──────────────┬────────────────┬──────────────┬────────────────┐
│            (index)             │    time    │    Δt     │ app  .js │ app   Δ.js │ app  .js.br │ app   Δ.js.br │ app  .js.gz │ app   Δ.js.gz │ vendor.js  │ vendor Δ.js │ vendor.js.br │ vendor Δ.js.br │ vendor.js.gz │ vendor Δ.js.gz │
├────────────────────────────────┼────────────┼───────────┼───────────┼─────────────┼──────────────┼────────────────┼──────────────┼────────────────┼────────────┼─────────────┼──────────────┼────────────────┼──────────────┼────────────────┤
│         Default Terser         │ '5m 7.9s'  │ '+87.12%' │ '2.13 MB' │    '+0%'    │ '148.81 kB'  │     '+0%'      │ '214.77 kB'  │     '+0%'      │ '13.11 MB' │    '+0%'    │  '1.71 MB'   │     '+0%'      │  '2.37 MB'   │     '+0%'      │
│ Terser w/ sequences/semicolons │ '4m 35.4s' │ '+67.36%' │ '2.13 MB' │    '+0%'    │ '148.81 kB'  │     '+0%'      │ '214.77 kB'  │     '+0%'      │ '13.11 MB' │    '+0%'    │  '1.71 MB'   │     '+0%'      │  '2.37 MB'   │     '+0%'      │
│        Default ESBuild         │ '2m 44.5s' │   '+0%'   │ '2.16 MB' │  '+1.41%'   │ '150.82 kB'  │    '+1.35%'    │ '220.99 kB'  │    '+2.9%'     │ '13.61 MB' │  '+3.85%'   │  '1.81 MB'   │    '+6.14%'    │  '2.54 MB'   │    '+6.95%'    │
│          Default SWC           │ '3m 56.9s' │  '+44%'   │ '2.25 MB' │  '+5.52%'   │  '150.3 kB'  │     '+1%'      │ '218.29 kB'  │    '+1.64%'    │ '13.24 MB' │  '+1.06%'   │  '1.78 MB'   │    '+4.19%'    │  '2.44 MB'   │    '+2.95%'    │
└────────────────────────────────┴────────────┴───────────┴───────────┴─────────────┴──────────────┴────────────────┴──────────────┴────────────────┴────────────┴─────────────┴──────────────┴────────────────┴──────────────┴────────────────┘
```

New tools:
 - https://github.com/NullVoxPopuli/ember-build-scenario-tester
 
Yet another new minifier: 
 - https://github.com/NullVoxPopuli/ember-cli-swc-minifier/

**Comment by patocallaghan** [comment]
@NullVoxPopuli what's the status on this prototype? are you using it anywhere?

**Comment by NullVoxPopuli** [comment]
yeah, I don't think it makes sense to replace terser with esbuild at this time as the tradeoffs aren't so easy to make, and will vary depending on your app's needs.
Like, my company's many many apps are all using this, but we're favoring speed over minification -- if you're favoring minification, terser is hard to beat -- only SWC would be an option, I think -- there are some perf benefits with SWC used for the same purpose, and that's demonstrated here: https://github.com/NullVoxPopuli/ember-cli-swc-minifier
But, it's slower than ESBuild for minification (because ESBuild does _less_) -- I _think_ this is kinda shown by the benchmarking done earlier -- but I haven't re-ran any of that since both SWC and ESBuild have been so actively developed -- would be interested to re-run the benches.


I think it _may_ make sense to provide a minifier as an option to folks -- and all of these libraries can be used today -- folks need only be informed of the tradeoffs they're making.

**Comment by patocallaghan** [comment]
Interesting, thanks for the response. I might give this a run over our app, curious to see how it holds up. We're trying to improve deploy times and the production build is a major bottleneck. Be interesting to see the difference in payload size between ESBuild and Terser for us.

**Comment by bertdeblock** [comment]
Closing for now if that's okay!

**Pull request closed without merging**
