### PR TITLE
Replace "pleasant-progress" with "ora"

### PR DESCRIPTION
**Pull request by Turbo87**
bildschirmfoto 2016-03-15 um 12 48 45

see https://github.com/sindresorhus/ora

/cc @miguelcobain

### CODE REVIEW

**Comment by miguelcobain** [comment]
Delivered. :bow:

**Comment by Turbo87** [comment]
animated preview

**Comment by kellyselden** [comment]
I didn't find any mention of Windows in that linked repo. Does it work well in Windows?

**Comment by Turbo87** [comment]
ora-windows

/cc @kellyselden :wink: 

it degrades automatically on windows (see https://github.com/sindresorhus/ora/blob/master/index.js#L25)

**Comment by kellyselden** [comment]
@Turbo87 Awesome. Thank you.

**Comment by stefanpenner** [comment]
ooo i like it

**Comment by Turbo87** [comment]
@homu r+

**Comment by Turbo87** [comment]
@homu retry

**Pull request merged**
