### PR TITLE
Upgraded ember-ajax to 0.7.1

### PR DESCRIPTION
**Pull request by taras**
https://github.com/ember-cli/ember-ajax/compare/v0.6.3...v0.7.1

### CODE REVIEW

**Comment by stefanpenner** [comment]
@taras if you have time, could you open an issue on ember-Ajax outlining goals to get to 1.0?

**Comment by taras** [comment]
@stefanpenner will do. I spoke to @tomdale yesterday and he's going to look at the library and discuss it with Ember Data team and I'll add his feedback afterwards.

**Comment by stefanpenner** [comment]
can you rebase, we have had several fixes. Likely cleaning up the appveyor issue.

**Comment by stefanpenner** [comment]
@homu +r

**Comment by stefanpenner** [comment]
rebased again

**Comment by rwjblue** [comment]
@homu r+

**Pull request merged**
