### PR TITLE
Improve `ember-cli` entry file

### PR DESCRIPTION
**Pull request by Turbo87**
see commit messages

### CODE REVIEW

**Comment by kellyselden** [comment]
Did you verify this still boots an ember app using node 0.12?

**Comment by rwjblue** [comment]
@kellyselden - No, you cannot install current ember-cli globally on Node 0.12 at anyways. I used Node 6 for testing 2.9.0+ and Node 4 for testing 2.0.0 through 2.8.0 (based on our [node support](https://github.com/ember-cli/ember-cli/blob/master/docs/node-support.md) doc).

**Comment by rwjblue** [comment]
Kicking off a new / fresh CI run...

**Comment by Turbo87** [comment]
@rwjblue finally 🍏

**Pull request merged**
