### PR TITLE
Update "isbinaryfile" to v3.0.0

### PR DESCRIPTION
**Pull request by Turbo87**
resolves part of https://github.com/ember-cli/ember-cli/pull/5548

### CODE REVIEW

**Comment by stefanpenner** [comment]
seems like a legit issue:

```
Error creating new application. Removing generated directory `./my-addon`
path must be a string
TypeError: path must be a string
    at TypeError (native)
    at Object.fs.stat (fs.js:830:11)
    at module.exports (/home/travis/build/ember-cli/ember-cli/node_modules/isbinaryfile/index.js:11:8)
    at /home/travis/build/ember-cli/ember-cli/lib/models/file-info.js:9:4478
    at lib$rsvp$$internal$$tryCatch (/home/travis/build/ember-cli/ember-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/home/travis/build/ember-cli/ember-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (/home/travis/build/ember-cli/ember-cli/node_modules/rsvp/dist/rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (/home/travis/build/ember-cli/ember-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
  1) dummy component x-foo

```

**Comment by Turbo87** [comment]
yes, I'll look into it

**Comment by Turbo87** [comment]
@stefanpenner problem resolved

**Comment by stefanpenner** [comment]
@homu r+

**Pull request merged**
