### PR TITLE
Prepares Ember CLI for new version of ember-welcome-page

### PR DESCRIPTION
**Pull request by locks**
- Update ember-welcome-page dependency
-  Re-introduce application.hbs template to include the new
welcome-page component

- [x] Release new `ember-welcome-page` version

### CODE REVIEW

**Comment by nathanhammond** [comment]
@ember-cli/core Thoughts on having Ember CLI run the default blueprint of any addon present after `ember new` or `ember addon`? This would avoid us having to hardcode what amount to blueprint-level changes into our `app`/`addon` blueprints.

I'm hesitant to enshrine what feel like blueprint related tasks into the blueprints. If y'all feel like that's a good feature I'll build it today (so that welcome-page may adopt it).

**Comment by Turbo87** [comment]
@nathanhammond 💯 👍  (see #6269)

**Comment by kellyselden** [comment]
Sounds good to me. `ember init` will probably want this feature too.

**Comment by nathanhammond** [comment]
I'm less sure about `ember init` as it's intended to be run in projects that are already set up.

**Comment by locks** [comment]
> I'm less sure about ember init as it's intended to be run in projects that are already set up.

We should have this as a different thing 🤔

**Comment by kellyselden** [comment]
> I'm less sure about ember init as it's intended to be run in projects that are already set up.

What about the scenario, you're doing an ember-cli upgrade via `ember init`. The default blueprint for package.json updated `ember-cli-eslint` from ^1.0.0 to ^2.0.0. There was a big default blueprint change in `ember-cli-eslint` that you need to run.

Isn't that the same problem as with `new` and `addon`?

**Comment by nathanhammond** [comment]
@kellyselden You make a good point. But unfortunately that implies that default blueprints must be idempotent/safe to rerun which is not something that we require at this time since they're only ever invoked once. This is a larger problem than I was thinking and I no longer want to block this PR on that effort.

**Comment by kellyselden** [comment]
Good point as well, I wasn't thinking of the blowing away of previous custom changes to blueprint. Carry on, no changes to `ember init`.

**Comment by nathanhammond** [comment]
Hokay, so, @locks, this is not blocked by CLI people's opinions. Just tests passing once the new version is released.

**Comment by nathanhammond** [comment]
@homu r+

**Comment by nathanhammond** [comment]
@locks Thank you for your tireless efforts on this!

**Pull request merged**
