### PR TITLE
Make project.config() public

### PR DESCRIPTION
**Pull request by simonihmig**
There are use cases like the one discussed in #6637 that require access to `project.config()`. Should it be made public therefore?

### CODE REVIEW

**Comment by rwjblue** [comment]
IMO, this is already at the very least an intimate API and we should make it public.

**Comment by rwjblue** [comment]
> Wouldn't that also imply that the returned configuration object should be "public"? In the sense that its structure should be documented and be part of the semver "contract", i.e. stick to this structure and not introduce BC (unless new major version of course).

No, I don't think so.  I think we should be able to specific specific keys in that object that are definitely public from ember-cli's perspective (e.g. `rootURL`), but we definitely do not need to make the entire config structure public.  The vast majority of things that end up in config (from my experience) are used and controlled by the app and are not generated/used by ember-cli.

**Comment by simonihmig** [comment]
@rwjblue Yes sure. Probably was not very precise, but meant basically the same: document the config keys that are used by ember-cli and that everybody using that API should be able to rely on.

**Comment by Turbo87** [comment]
this is essentially what comes out of `config/environment.js`, right?

**Comment by rwjblue** [comment]
> this is essentially what comes out of config/environment.js, right?

confirm

**Comment by Turbo87** [comment]
> ☔️ The latest upstream changes (presumably #6644) made this pull request unmergeable. Please resolve the merge conflicts.

whoops...

> > this is essentially what comes out of config/environment.js, right?
> confirm

seems fine to make this method public then, as long as we communicate clearly that the structure itself is not public/stable

**Comment by nathanhammond** [comment]
Calling this good with three 🚢. @homu r+

**Pull request merged**
