### PR TITLE
[fixes #4205] allow null addonTemplates.

### LINKED ISSUE #4205: Components in PODS with templates are broken in Ember CLI 0.2.6
Steps to reproduce:

1. ember addon new-addon
2. cd new-addon
3. ember generate component --pod my-component
4. ember s

Get error:

Addon templates were detected, but there are no template compilers registered for `new-addon`. Please make sure your template precompiler (commonly `ember-cli-htmlbars`) is listed in `dependencies` (NOT `devDependencies`) in `new-addon`'s `package.json`.

5. Edit package.json, moving "ember-cli-htmlbars" from dev-dependencies to dependencies
6. ember s

Get errors:

```
[Deprecated] this.pickFiles is deprecated, please use broccoli-funnel directly instead  [addon: new-addon]
Livereload server on port 35729
Serving on http://localhost:4200/
Cannot read property 'rebuild' of undefined
TypeError: Cannot read property 'rebuild' of undefined
    at Builder.wrapIfNecessary (/Users/gmunjal/code/new-addon/node_modules/ember-cli/node_modules/broccoli/lib/builder.js:136:18)
    at readAndReturnNodeFor (/Users/gmunjal/code/new-addon/node_modules/ember-cli/node_modules/broccoli/lib/builder.js:44:17)
    at RSVP.resolve.then.then.finally.readTreeRunning (/Users/gmunjal/code/new-addon/node_modules/ember-cli/node_modules/broccoli/lib/builder.js:92:24)
    at lib$rsvp$$internal$$tryCatch (/Users/gmunjal/code/new-addon/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/gmunjal/code/new-addon/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:501:17)
    at /Users/gmunjal/code/new-addon/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1095:13
    at Object.lib$rsvp$asap$$flush [as _onImmediate] (/Users/gmunjal/code/new-addon/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1290:9)
    at processImmediate [as _immediateCallback] (timers.js:354:15)
```

This breaks addon ember-cli-jquery-ui

### PR DESCRIPTION
**Pull request by stefanpenner**

### CODE REVIEW

**Comment by rwjblue** [comment]
We should probably have a test for this to help prevent future regressions.

**Comment by stefanpenner** [comment]
> We should probably have a test for this to help prevent future regressions.

ya, working on that as we speak.

**Comment by stefanpenner** [comment]
tests added

**Comment by rwjblue** [comment]
LGTM, thank you

**Pull request merged**
