### PR TITLE
Addon discovery and isolation

### PR DESCRIPTION
**Pull request by lukemelia**
The goal of this PR is to address #2714 by moving to a model where addons are more isolated, and addons that have addons don't pollute the project with the dependent addons.

Feedback welcome.

- [x] extract discovery of addons from Project to it's own AddonDiscovery object
- [x] extract initialization of addons from Project to it's own AddonsFactory object
- [x] give each addon it's own AddonDiscovery instance, to look for child addons
- [x] give each addon it's own AddonsFactory instance, to instantiate any child addons
- [x] add acceptance test verifying addon isolation
- [x] add new addon hook: `setupPreprocessorRegistry(type, registry)`
- [x] move `registry` to `models/`
- [x] add more acceptance tests exercising nested plugins
- [x] implement support for nested addons contributing to built output, and handling for addons appearing more than once in the graph, including two different versions of the same addon (*keeping current semantics of one addon per build output, and last added "wins"*)
- [x] unit tests for `setupPreprocessorRegistry` hook
- [x] unit tests for AddonsDiscovery
- [ ] unit tests for AddonsFactory
- [x] inline docs for `setupPreprocessorRegistry` hook
- [x] inline docs for AddonsDiscovery
- [ ] inline docs for AddonsFactory
- [x] verify with addon that has HTMLBars templates in the addon (requires ember-cli-htmlbars 0.7.4 or above): [Demo App](https://github.com/rwjblue/templates-in-nested-addons/)
- [ ] document changes necessary to addons to take advantage of this.
- [x] Update to Ember 1.10 by default.

### CODE REVIEW

**Comment by rwjblue** [comment]
This is looking very good.

**Comment by jayphelps** [comment]
you're my hero

**Comment by lukemelia** [comment]
I believe this is now feature complete. Still needs tests and docs, as I've added to the checklist, but it would be a great time to provide any feedback on the implementation.

**Comment by jayphelps** [comment]
RAD. Will test tomorrow. I've got a bunch of projects and addons working around this that I can test against.

**Comment by lukemelia** [comment]
@jayphelps note that this is a breaking change. Addons may need to be updated to implement `setupPreprocessorRegistry` appropriately.

**Comment by rwjblue** [comment]
Verified that ember-cli-htmlbars@0.7.1 works properly with this branch when compiling addons with templates in the `addon/` tree.  Sample app: https://github.com/rwjblue/templates-in-nested-addons/

**Comment by lukemelia** [comment]
Sweet!

**Comment by rwjblue** [comment]
Removed WIP label.

@ember-cli/owners - Speak now or forever hold your peace... :trollface:

**Comment by twokul** [comment]
@lukemelia big OS :heart: from me to you, Sir.

**Comment by chadhietala** [comment]
:shipit:

**Comment by trabus** [comment]
Awesome work @lukemelia! :+1:

**Comment by lukemelia** [comment]
This was a team effort. @rwjblue provided great guidance and took it over the finish line. Also, props to @chrislopresto for helping me with some testing and thinking on this, and to @gshackles at @ololabs for funding the early work on this. Glad to see it landing!

**Comment by joostdevries** [comment]
@lukemelia this is intensely awesome, a very important iteration on the whole addon concept. 

How do you define the division of labour between `AddonDiscovery` and `AddonFactory`, wouldn't a single class make more sense?

**Comment by rwjblue** [comment]
Added unit tests for `AddonDiscovery` model.

**Comment by lukemelia** [comment]
@joostdevries I could go either way on the separation of AddonDiscovery and AddonsFactory. Conceptually, it seems to me that discovering dependent addons is a separate thing from instantiating a set of addons in DAG-powered order. Regarding registering addonPackages on the Project... yes I think we ultimately should have the encapsulation be complete. I was trying to take as small a step here as I could with respect to number of APIs we were breaking.

**Comment by stefanpenner** [comment]
This looks awesome. I am going to set some time aside tonight to thoroughly review this.

**Comment by rwjblue** [comment]
@stefanpenner - I'd like to land this and release 0.2.0-beta.1 soon (once Travis passes), that way folks have some time to provide feedback on the beta (and allows others to help out easier since it wouldn't be blocked in this PR any longer).

**Comment by joostdevries** [comment]
> I was trying to take as small a step here as I could with respect to number of APIs we were breaking.
@lukemelia I'm with you on that. Again, this looks amazing.

**Comment by jayphelps** [comment]
LETS PARTY!!

**Comment by cibernox** [comment]
Is that the end of the painful manual package.json upgrade review?

**Comment by rwjblue** [comment]
@cibernox - Not sure, you will still need to review `package.json` and `bower.json` updates, but they at least will not require you to manually remove `broccoli-ember-hbs-template-compiler` and change the Ember version from 1.8.0.

**Comment by cibernox** [comment]
I thought that core stuff like `broccoli-asset-rev` or `ember-cli-6to5` would be nested in ember-cli itself, and therefore I won't need to take care of resolving conflicts on them.

**Comment by rwjblue** [comment]
@cibernox - Nope, that is not being done in this PR.  Those addons will continue living in your apps `package.json`, because it needs to be trivially possible to opt out of them.

**Comment by cibernox** [comment]
Undestood

**Comment by slindberg** [comment]
Huge thanks @lukemelia, @rwjblue, and everyone else involved! :clap:

**Pull request merged**
