### PR TITLE
Cleanup unused utilities

### PR DESCRIPTION
**Pull request by Turbo87**
This PR removes unused utilities that were previously extracted into separate NPM packages.

### CODE REVIEW

**Comment by Turbo87** [comment]
@stefanpenner @kellyselden @trabus r?

**Comment by stefanpenner** [comment]
@homu r+

**Comment by kellyselden** [comment]
Only thing to watch out for is addons reaching in and using these utils. Not much of a concern for me though.

**Comment by Turbo87** [comment]
we could deprecate it but I'm not sure it's worth it... should be mentioned in the release notes though

**Pull request merged**
