### PR TITLE
Explain Azure Deployment

### PR DESCRIPTION
**Pull request by felixrieseberg**
This commit adds a short explanation of `ember-cli-azure-deploy`, a small Node module we at Microsoft's open source team wrote to make it dramatically easier for Ember Cli users to deploy their apps to Azure Websites. It essentially enables automated builds in the cloud, allowing Azure to recompile every single
time a commit is pushed to the project’s repo. 

We at Microsoft :heart: Ember & Ember-Cli, using it for a bunch of stuff internally. Thanks for everything!

### CODE REVIEW

**Comment by rwjblue** [comment]
Awesome!!

**Comment by trek** [comment]
@felixrieseberg  We should get the Logo on the list of users!

**Comment by stefanpenner** [comment]
I would love to sync up with some Microsoft employees so we can make ember-cli even better on windows

**Comment by felixrieseberg** [comment]
Hey @stefanpenner, I'm an [Open Source Dev](http://felixrieseberg.com/open-source-engineer-microsoft/) for Microsoft, doing exactly stuff like that. Would you mind shooting me a mail at felix.rieseberg@microsoft.com? I'd love to just jump on a phone and chat about what me or my team could do.

**Comment by stefanpenner** [comment]
Rad. Will do!

**Pull request merged**
