### PR TITLE
[fixes #4467] ensure commands that fail do to being run in the wrong …

### LINKED ISSUE #4467: "ember build" fails with exit code 0
Seems like https://github.com/ember-cli/ember-cli/issues/1486 has returned.

```
▶ ember build
version: 1.13.1
You have to be inside an ember-cli project in order to use the build command.
                                                                                                                                                                                                                                           
▶ echo $?
0
```

This was causing some problems with my Ansible automation, as the build would fail, but Ansible believed it to have passed.

### PR DESCRIPTION
**Pull request by stefanpenner**
…context exit with the correct status code

- [x] test
- [ ] make appveyor happy.

### CODE REVIEW

**Comment by stefanpenner** [comment]
@hjdivad crap, we gotta make appveyor happy again :(

**Comment by hjdivad** [comment]
@stefanpenner ah i take it we broke things for windows?

Well maybe we need to go with the unloading approach or figure out what the state problem is within `npm`.

At least it'll be way easier now that we know how to consistently reproduce the problem in a "somewhat" short amount of time.

**Comment by stefanpenner** [comment]
> Well maybe we need to go with the unloading approach or figure out what the state problem is within npm.

ya :P

**Comment by jeffshaver** [comment]
@stefanpenner does this mean we can get a release soon?

**Comment by stefanpenner** [comment]
Yup

**Pull request merged**
