### PR TITLE
Remove jQuery integration scenario from ember-try

### PR DESCRIPTION
**Pull request by NullVoxPopuli**
The release version of: https://github.com/ember-cli/ember-cli/pull/9736

### CODE REVIEW

**Comment by rwjblue** [comment]
Restarted CI

**Comment by SergeAstapov** [comment]
Fixes #9701

**Comment by bertdeblock** [comment]
Mind also removing this scenario from the addon CI file?
https://github.com/ember-cli/ember-cli/blob/master/blueprints/addon/files/.github/workflows/ci.yml#L63

**Comment by NullVoxPopuli** [comment]
done

**Comment by NullVoxPopuli** [comment]
@rwjblue thoughts?

**Comment by kategengler** [comment]
I kicked CI a couple of times today. Not sure at all about the failures.

**Pull request merged**
