### PR TITLE
[dx] Detail app / addon creation messages

### PR DESCRIPTION
**Pull request by dcyriller**
**Description**
Creating an app (or an addon) will take a little time. This PR aims at improving the messaging displayed to the developer while the creation is ongoing.

I'm not a native speaker, so do not hesitate to correct / improve the messages' wording.

**Emoji support**
This PR uses a few emojis. By default, they won't be displayed in PowerShell and in non-TTY environments. This PR also introduces a `--no-emoji` flag that does what it tells (usefull to turn emojis off in CI if the user'd like to do so)!

**Manual Testing**
```sh
npx github:dcyriller/ember-cli#improve-create-new-app new ember-app
```

**Preview**
AFTER (timings and colors are not 100% faithful):
render1555194608097

BEFORE:
render1555194219536

### CODE REVIEW

**Comment by kellyselden** [comment]
These look really nice! Do you happen to know how those images show up in Windows shells?

**Comment by dcyriller** [comment]
I've run these commands in Windows' Powershell!... And the emoji are not properly rendered (colors are fine though). But so does `yarn` emojis', so... 🤷‍♂️

**Comment by dcyriller** [comment]
PowerShell don't support

**Comment by dcyriller** [comment]
@kellyselden you may be interested by the 2nd commit I've added (I've updated the PR description) 😉

**Comment by rwjblue** [comment]
Nice! I like it!!

**Comment by dcyriller** [comment]
Travis seems happy. But AppVeyor for node 10 is not. If anyone has an idea on how to fix that, I'm open to suggestions.

**Comment by dcyriller** [comment]
CI is green now.

I've run into the `process already captured` random error (affecting both Travis and AppVeyor at the moment).

**Comment by dcyriller** [comment]
Is anything blocking this?

**Comment by stefanpenner** [comment]
@dcyriller this looks really nice!

**Comment by stefanpenner** [comment]
(pairing with @rwjblue on the merge)

**Comment by rwjblue** [comment]
Thank you @dcyriller!

**Pull request merged**
