### PR TITLE
[DOCS] contentFor only receives type and config

### PR DESCRIPTION
**Pull request by chadhietala**
Writing an addon... verifying docs along the way.

### CODE REVIEW

**Comment by rwjblue** [comment]
:+1: - Merge or wait and add more as you go, up to you.

**Comment by chadhietala** [comment]
I'll keep it open for now just in case. Will merge in an hour or 2.

**Comment by joostdevries** [comment]
Lgtm. The doc probably copied the signature from EmberApp.

**Comment by joostdevries** [comment]
If you could add a jsdoc block in https://github.com/ember-cli/ember-cli/blob/master/lib/models/addon.js too that'd be completely awesome by the way

**Pull request merged**
