### PR TITLE
Add a verification step to fail the build when tests are filtered with .only

### PR DESCRIPTION
**Pull request by marcioj**
Previously I sent a PR with a missing `.only` in the tests, this made the whole build just run tests of one file. To prevent this problem I added a verification step as requested by @stefanpenner.

### CODE REVIEW

**Comment by marcioj** [comment]
Tests passed in my machine not sure what is happening here. Maybe this error is something related to travis.
Can someone please purge the cache and restart the build?
Thanks

**Comment by marcioj** [comment]
When I changed `addFiles(mocha, '/**/*-test.js'); addFiles(mocha, '/**/*-slow.js');` to a single call like `addFiles(mocha, '/**/*{-test.js,-slow.js}');`. I noticed that some tests failed, so I reverted the changes.
Is there some known issue with tests ordering?
Anyway the travis tests are passing now.

**Comment by marcioj** [comment]
Friendly ping

**Comment by stefanpenner** [comment]
> Friendly ping

sorry, i must have missed this one.

**Comment by stefanpenner** [comment]
> Is there some known issue with tests ordering?

not that i know of :S, maybe some issue do exist?

Is this ready to go?

**Comment by marcioj** [comment]
> sorry, i must have missed this one.

No problem :)

> not that i know of :S, maybe some issue do exist?
> Is this ready to go?

I remember when I changed the glob expression to `/**/*{-test.js,-slow.js}` some tests failed, the first thing that comes to my mind was the test ordering, because it was the only difference I noticed.

Anyway the changes related to `.only` in tests are ready to go.

**Comment by marcioj** [comment]
Wait a second, I'm unsure why I added package.json and bower.json in the addon blueprint. Let me see what happens if I remove them.

**Comment by marcioj** [comment]
@stefanpenner now it's ready to go

**Comment by stefanpenner** [comment]
thank you kindly sir :)

**Pull request merged**
