### PR TITLE
remove trailing comma

### PR DESCRIPTION
**Pull request by kellyselden**
Accidentally targeted master on the last one.

### CODE REVIEW

**Comment by twokul** [comment]
https://github.com/ember-cli/ember-cli/pull/7747

**Comment by kellyselden** [comment]
It's probably the same issue, but the release branch. beta branch might suffer as well.

**Comment by Turbo87** [comment]
was this already published with the trailing comma? I'm not sure it's worth the churn to fix it unless we enable the trailing comma rule of ESLint by default.

**Comment by kellyselden** [comment]
> was this already published with the trailing comma?

yes.

> I'm not sure it's worth the churn to fix

I don't think churn is as much of a concern now that we have ember-cli-update. Also, I think it is worth it because projects that have a trailing-comma rule (all of mine) now get eslint errors with this version. I don't think it's worth putting in an exclusion everywhere for a file that accidentally violated a convention.

**Pull request merged**
