### PR TITLE
[ENHANCEMENT] Allow specifying no CI provider

### PR DESCRIPTION
**Pull request by deanylev**
Fixes https://github.com/ember-cli/ember-cli/issues/10442

### CODE REVIEW

**Comment by kategengler** [comment]
@deanylev This has some test failures

**Comment by deanylev** [comment]
@kategengler apologies, should be fixed now

**Comment by Windvis** [comment]
@deanylev Could you rebase this on the lastest master changes?  I think this is good to go otherwise :tada:

**Comment by deanylev** [comment]
@Windvis done!

**Review by NullVoxPopuli — APPROVED** [review]

**Pull request merged**
