### PR TITLE
EmberApp: Use "src/ui/styles" over "app/styles" if it exists

### PR DESCRIPTION
**Pull request by Turbo87**
This should be seen as a short-term enhancement, but that whole part of the code is in desperate need of a cleanup... 😟 

Resolves https://github.com/ember-cli/ember-cli/issues/6819

/cc @mixonic

### CODE REVIEW

**Comment by mixonic** [comment]
this is sufficient for my immediate needs. 👍  if @rwjblue or someone on ember-cli is also in agreement it is a good path for now.

**Comment by stefanpenner** [comment]
I believe all the `modules` RFC stuff should behind an ember-cli feature flag.

**Comment by rwjblue** [comment]
I think the only blocker is @stefanpenner's comment RE: flagging...

**Comment by Turbo87** [comment]
@stefanpenner @rwjblue updated the code to use a feature flag. I've also adjusted the code introduced in https://github.com/ember-cli/ember-cli/issues/6825 to only be enabled via the same feature flag.

**Comment by Turbo87** [comment]
@homu r+

**Pull request merged**
