### PR TITLE
[FEATURE] adding self-closing tags to index.html

### PR DESCRIPTION
**Pull request by williamsbdev**

### CODE REVIEW

**Comment by stefanpenner** [comment]
kicking appveyor

**Comment by rwjblue** [comment]
I'm not opposed, but I don't see the point either. meta and link are void tags, and do not require closing.

What am I missing?

**Comment by stefanpenner** [comment]
I am also trying to figure it out, someone reported an issue. But didn't elaborate

**Comment by stefanpenner** [comment]
issue: 
https://github.com/ember-cli/ember-cli/issues/4277

apparently some IE issues?

**Comment by stefanpenner** [comment]
I also believe this is now not valid HTML5.  investigating

**Comment by stefanpenner** [comment]
it appears this is spec'd as non-closing -> http://www.w3.org/TR/html5/document-metadata.html#meta

**Comment by stefanpenner** [comment]
https://github.com/ember-cli/ember-cli/issues/4277

**Comment by williamsbdev** [comment]
I was unaware this is a limitation in the template language we are using at work. I will do more due diligence in the future to make sure that my PRs are according to spec. Thanks for the link to the spec! I appreciate you guidance.

**Comment by stefanpenner** [comment]
@williamsbdev not a problem. I didn't know for sure either, so I had to dig in.

Unfortunately, I don't think we should deviate from the HTML5 spec here. I suspect as a solution you can just adjust your tags post generation.

**Comment by williamsbdev** [comment]
@stefanpenner Absolutely. We are already doing that today and will continue forward with that. Thanks again!

**Pull request closed without merging**
