### PR TITLE
Drop Ember 3.8 and add Ember 3.16 scenarios in default `config/ember-try.js`.

### PR DESCRIPTION
**Pull request by kellyselden**
Post Octane release, master will be on 3.17. I'm getting this PR ready now so I don't forget again.

### CODE REVIEW

**Comment by auvipy** [comment]
so ember.js 3.16 will be te default octane?

**Comment by kellyselden** [comment]
@auvipy This PR doesn't really have anything to do with Octane.

**Comment by kellyselden** [comment]
@rwjblue Isn't this merge preemptive? Master is still what 3.16 will become.

**Comment by rwjblue** [comment]
🤦‍♂ya, I'll fix before releasing

**Pull request merged**
