### PR TITLE
Improved chai/expect assertion usage

### PR DESCRIPTION
**Pull request by Turbo87**

### CODE REVIEW

**Comment by nathanhammond** [comment]
Strongly in favor, appears to have issues in 0.X Node for unidentified reasons.

**Comment by Turbo87** [comment]
@nathanhammond looks like the "encoding" property on the `fs.readFileSync()` call was missing which caused `expected` to be a raw buffer instead of a string.

**Comment by Turbo87** [comment]
@stefanpenner @nathanhammond @rwjblue r?

**Comment by Turbo87** [comment]
merging due to the initial feedback and no objections

@homu r+

**Pull request merged**
