### PR TITLE
Add "Discover Ember" to list of tutorials

### PR DESCRIPTION
**Pull request by t4t5**
Not sure if these tutorials are arranged in any special order, so I just added it to the bottom.

This course has been my side project for the last few months, and now that it's released, it would be great to have it featured on the page so that more new users can get started easily! :+1:

### CODE REVIEW

**Comment by stefanpenner** [comment]
> Not sure if these tutorials are arranged in any special order, so I just added it to the bottom.

alphabetical

**Comment by chadhietala** [comment]
@stefanpenner after scanning over the free material I would :+1: to adding it.

**Comment by kellyselden** [comment]
The link is broken. Double https://https://

**Comment by stefanpenner** [comment]
Good catch, mind submitting a fix?

**Comment by kellyselden** [comment]
Sure

**Comment by t4t5** [comment]
Fixed it. Pull request #4610. Sorry for screwing up the link. :P

**Pull request merged**
