### PR TITLE
Rebased "Prevent Termination Confirmation on Windows"

### PR DESCRIPTION
**Pull request by Turbo87**
This is essentially https://github.com/ember-cli/ember-cli/pull/5238 rebased and with a few small test improvements. I've tested this with inquirer and didn't notice any problems.

/cc @felixrieseberg @stefanpenner @kellyselden

### CODE REVIEW

**Comment by felixrieseberg** [comment]
Thanks for staying on top of this 👍

**Comment by Turbo87** [comment]
AppVeyor tests seem mostly green except for the usual suspects :shipit:

**Comment by stefanpenner** [comment]
So this seems to trap for `builder` related stuff, but should this actually be more general? Allowing for this behavior in all scenarios instead of just during builds?

**Comment by Turbo87** [comment]
@stefanpenner I tend to agree, having this everywhere would probably make sense.

**Comment by stefanpenner** [comment]
I have tested it, and it works fine during the build-phase, but it is strange that other phases (even just before build, or just after, but before the process exists) that the prompt still appears.

So this is a good step in the right direction, as the build phases are longest, but it feels like it should be a more all covering.

**Comment by Turbo87** [comment]
@stefanpenner IMHO we should merge this as a first step and then we can try to apply it more genetically in a later PR

**Comment by stefanpenner** [comment]
> we can try to apply it more genetically

where you thinking of using https://en.wikipedia.org/wiki/Needleman%E2%80%93Wunsch_algorithm ?

:trollface: 

----



> @stefanpenner IMHO we should merge this as a first step

👍

**Comment by Turbo87** [comment]
:joy: that should've said generically... damn phone keyboard

**Comment by Turbo87** [comment]
@homu r+

**Pull request merged**
