### PR TITLE
Introduce `moduleForAcceptance`

### PR DESCRIPTION
**Pull request by seanpdoyle**
Closes [switchfly/ember-test-helpers#94][94] and
[rwjblue/ember-qunit#71][71].

[94]: https://github.com/switchfly/ember-test-helpers/issues/94
[71]: https://github.com/rwjblue/ember-qunit/pull/71

### CODE REVIEW

**Comment by stefanpenner** [comment]
nice – but tests don't appear happy

**Comment by seanpdoyle** [comment]
@stefanpenner we're green on `iojs` and `v0.10`, any ideas why we'd be failing on `v0.12.0`?

https://travis-ci.org/ember-cli/ember-cli/builds/77424983

**Comment by stefanpenner** [comment]
nice!

do the beforeEach/afterEach merge, or will user once stomp on internal ones?

> @stefanpenner we're green on iojs and v0.10, any ideas why we'd be failing on v0.12.0?

unsure let me take a look

---

also r? @rwjblue

**Comment by stefanpenner** [comment]
needs rebase

**Comment by seanpdoyle** [comment]
@stefanpenner this is passing everywhere but AppVeyor... any advice?

**Comment by stefanpenner** [comment]
@seanpdoyle I suspect its unrelated, will investigate later.

@homu r+

**Comment by seanpdoyle** [comment]
:clap:

**Comment by stefanpenner** [comment]
@seanpdoyle thanks bor :)

**Comment by rwwagner90** [comment]
Is moduleForAcceptance supposed to remove DOM or are we supposed to only have one test per module?

**Comment by rwjblue** [comment]
Yes, each test should be cleaning up after itself. Having multiple tests in each file is perfectly fine.

**Comment by danielspaniel** [comment]
Is there a version of moduleForAcceptance for ember-mocha?

**Pull request merged**
