### PR TITLE
Fix existing yuidoc comment issues

### PR DESCRIPTION
**Pull request by Turbo87**
This PR fixes several `yuidoc` warnings about incorrect doc comments.

### CODE REVIEW

**Comment by stefanpenner** [comment]
is it possible to add "validation of YUIDoc" to our tests?

**Comment by Turbo87** [comment]
@stefanpenner I'm aiming for that, but we're not quite there yet

**Comment by Turbo87** [comment]
@stefanpenner this seems to be blocked on https://github.com/yui/yuidoc/issues/403 ... 😞

**Comment by stefanpenner** [comment]
ah... should i revert?

**Comment by Turbo87** [comment]
@stefanpenner noooo, I meant the linting stuff as test criteria 😉

**Comment by stefanpenner** [comment]
@Turbo87 sorry, misunderstood ;)

**Pull request merged**
