### PR TITLE
WIP: testem v1.10.0

### PR DESCRIPTION
**Pull request by johanneswuerbach**
This is the first rc for the new testem v1.10.0, which should fix all regressioning leading to the rollback of v1.9.0

@rwjblue @alexgraul @hemp would really appreciate if you could test this rc in your apps and check whether the issue has been resolved.

### CODE REVIEW

**Comment by stefanpenner** [comment]
@johanneswuerbach awesome, mind also linking to the changelog?

**Comment by johanneswuerbach** [comment]
Haven't prepared that yet (sorry, quite late here), but it's basically https://github.com/testem/testem/releases/tag/v1.9.0 without the regressions.

**Comment by johanneswuerbach** [comment]
Yes, one test is doing some assertions against the testem output, will look into it, but quite busy this week :-( Maybe @tjni?

**Comment by Turbo87** [comment]
ah indeed. it seems that https://github.com/ember-cli/ember-cli/blob/e29e6c153aa8e03dc6f117e912413aeaf3b843df/tests/acceptance/smoke-test-slow.js#L414 is failing. did you remove the test run summary from the testem output?

**Comment by tjni** [comment]
I can look into this tonight (PDT).

**Comment by johanneswuerbach** [comment]
Thanks a lot @tjni, bumped and re-running.

**Comment by Turbo87** [comment]
@johanneswuerbach @tjni seems to work fine now, great work!

**Comment by hemp** [comment]
@johanneswuerbach I tried out `"testem": "https://github.com/testem/testem#v1.10.0-1"` with one of our CI builds (`ember test ci --reporter=xunit`) and it generates the xunit report correctly.  Thanks for this!

**Comment by johanneswuerbach** [comment]
Thanks everybody, just published testem `v1.10.0`. 👍

**Pull request closed without merging**
