### PR TITLE
use npm@4 on appveyor

### PR DESCRIPTION
**Pull request by ro0gr**
I've noticed regular [npm errors](https://ci.appveyor.com/project/embercli/ember-cli/build/13347/job/js8qgobkplwo0qki#L534) on appveyor.

From my experience npm@4 is much more stable. Can we use it on CI?

### CODE REVIEW

**Comment by rwjblue** [comment]
Lets merge once appveyer run is green...

**Comment by ro0gr** [comment]
Some observations:

While the build is green npm errors are [still there](https://ci.appveyor.com/project/embercli/ember-cli/build/13348/job/1wxxo4klkb0w2fg2#L569). 
All the errors are related to `ee-first` package.

Also build become a little bit slower:
before: https://ci.appveyor.com/project/embercli/ember-cli/build/13347
after: https://ci.appveyor.com/project/embercli/ember-cli/build/13348

**Comment by ro0gr** [comment]
I still think it's good change. But seems like the reason of failures might be not in npm itself.

**Comment by ro0gr** [comment]
add npm-cache dir to `appveyor.yml`. just to check if it affects anything

**Comment by ro0gr** [comment]
After some reading of cryptic appveyor logs I think the actual reason of failures might be in a mixed usage of yarn in `createTestTarget` and `npm` in blueprints on `ember g`. As far as I understand we should not use `yarn` and `npm`  in the same test run and I think we currently do it.

I'm closing this pr for now. Seems like `yarn` vs `npm` issue should be investigated first. 
I'll try to dig into it soon.

**Pull request closed without merging**
