### PR TITLE
Removing view blueprint

### PR DESCRIPTION
**Pull request by jasonmit**
Since ember-cli now targets 2.x, which doesn't expose `Ember.View`, we should likely remove it and instead move the blueprint to the `ember-legacy-views` addon.

Related: http://discuss.emberjs.com/t/can-not-generate-a-view-for-the-index-route/10131

### CODE REVIEW

**Comment by rwjblue** [comment]
Agreed.

**Comment by stefanpenner** [comment]
@homu r+

**Comment by jasonmit** [comment]
@stefanpenner tests should now be passing

**Comment by kellyselden** [comment]
@homu r+

**Comment by mike-north** [comment]
In the future  we may wish to at least leave the de-generator intact for this kind of thing. `ember d view-test my-view` continues to be of value as people are upgrading to ember 2.5.

**Comment by jasonmit** [comment]
The blueprints were moved into the legacy view addon but it looks like that was never versioned.

/cc @rwjblue @stefanpenner

**Comment by nathanhammond** [comment]
If we do a new release of ember-legacy-views then a new `npm install` would give you the ability to `destroy`. It's not too late. Can we bump that version to 0.2.1?

**Comment by toranb** [comment]
@stefanpenner @jasonmit ...so is ember-cli 2.4.x not ember 1.13 friendly anymore ? What is the last version ember 1.13 devs can use w/out conflict ?

**Comment by jasonmit** [comment]
In lock step with Ember, but I see no reason why it wouldn't work with 1.13.  If you need the blueprints you can continue to pull them in through the legacy view addon (assuming that was versioned).

**Comment by rwjblue** [comment]
Or just make the files by hand...

**Comment by toranb** [comment]
@rwjblue @jasonmit awesome! just wanted to make sure this was (overall) ember 1.13/2.x friendly :)

**Pull request merged**
