### PR TITLE
Remove native bundled dependencies

### PR DESCRIPTION
**Pull request by patocallaghan**
Re: https://github.com/ember-cli/ember-cli/issues/5028#issuecomment-153405634

@stefanpenner this is more a placeholder for discussion rather than a finished PR. Would appreciate you chiming in with your thoughts whether this is even on the right track or not.

## ws.js
It seems the issue of failing native dependencies has been fixed in npm 3.3.12

* Optional dependencies causing an install to fail was fixed in https://github.com/npm/npm/commit/2289234e11b30c878585aebee68d4a3a5bd63cce See https://github.com/npm/npm/issues/9643 for the related issue
* running `--no-optional` should not try to install bundled dependencies in deps of deps

This means we don't need the patch for `ws.js` as `bufferutil` and `utf8-validation` will not be installed.

## patch-engine-io-client.js
it appears the reference to the `tgz` [has been removed](https://github.com/socketio/engine.io-client/pull/401/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L38) but it hasn't shipped in a release yet . Not entirely sure what we can do here though besides pushing for a release or making our own fork.

### BUT

there's a bug with the 3.3.12 version of NPM which prevents `./bin/prepare-release` from finishing. If you try to `npm uninstall` or `npm unlink` a `npm link`'d global module, the build fails. This means `prepare-release` fails at the second last step when uninstalling the global `ember-cli`.  See here for more on the issue https://github.com/npm/npm/issues/9980.

We could possibly do a `which ember`, work out where the global ember is installed, and manually `rm -rf` it?

### CODE REVIEW

**Comment by stefanpenner** [comment]
> It seems the issue of failing native dependencies has been fixed in npm 3.3.12

yes but we want to even attempting to compile these native deps them entirely because:

* they are slow
* they are un-needed
* when they fail, they produce confusing output suggesting to the user the world has ended

Given that, should this restore the WS patching?

> t appears the reference to the tgz has been removed but it hasn't shipped in a release yet . Not entirely sure what we can do here though besides pushing for a release or making our own fork.

ah so this will get better with the next release



> there's a bug with the 3.3.12 version of NPM which prevents ./bin/prepare-release from finishing. If you try to npm uninstall or npm unlink a npm link'd global module, the build fails. This means prepare-release fails at the second last step when uninstalling the global ember-cli. See here for more on the issue npm/npm#9980.

upgrading npm here seems ok, but i don't think this actually changes the root problem. `npm install -g ember-cli` is the offender not `ember install`



> running --no-optional should not try to install bundled dependencies in deps of deps

the goal of the patching was to make it so users do not need to know about --no-optional.

**Comment by patocallaghan** [comment]
Thanks, I'm understanding the problem a bit more now. :skull: to native deps entirely. I've done a dig around seeing if there's in anything that can be set in the `package.json` to always run in `no-optional` mode but couldn't really find anything.

With the outstanding issues in npm3, your forking idea could possibly be the most robust. How exactly where you expecting this to work? Would this mean forking each of testem, socket.io, ws, engine.io-client? It could be a bit of a nightmare to maintain.

**Comment by twokul** [comment]
@patocallaghan @stefanpenner what are the native dependencies? `ws`? seems like `engine.io-client` relies on it. Maintaining a separate js version of the packages can be painful :confused:

**Comment by stefanpenner** [comment]
forking would be most robust, maybe we can get away with patching in v3 still? Someone should investigate...

**Comment by patocallaghan** [comment]
@stefanpenner I can take a look at that.

Re:why we are resolving this in the first place. Just to clarify, the patching is currently working for 1.13.8? But it stops working when someones uses npm3 to install ember-cli or when we upgrade ember-cli to use v3 internally?

**Comment by patocallaghan** [comment]
Also @stefanpenner should [the patching of engine-io-client](https://github.com/ember-cli/ember-cli/blob/master/patches/patch-engine-io-client.js#L16) not be:

```
pkg.dependencies.xmlhttprequest = '*';
```
instead of

```
pkg.dependencies.xmlhttprequest === '*';
```

**Comment by stefanpenner** [comment]
@patocallaghan lol oops!

**Comment by patocallaghan** [comment]
Just doing some testing:

With node 4.2.2 and npm 2.14.7, I ran `./bin/prepare-release`, generated a `.tgz` and the two `package.json` files have been patched correctly (using a fix for above ^).
Installed with `npm install -g ember-cli-*.tgz` and no optional dependencies there, so :+1: 

Will test with npm 3 next

**Comment by stefanpenner** [comment]
> Will test with npm 3 next

thank you sir :)

**Comment by patocallaghan** [comment]
So did some testing with npm3. Running `./bin/prepare-release` with npm 3 is currently busted for two reasons:

1. npm/npm#9980 means the script fails because you can't unlink or uninstall a global package. It needs to be manually nuked
2. The `patches/patch-engine-io-client.js` patch script doesn't work as is because npm 3 now puts all packages in `node_modules` in a flat structure rather than a nested structure. We'd need to update the script to accommodate this.

As for whether you can install `ember-cli` with the patched `.tgz` using npm3? Nope, it doesn't work. Even though we have the patched package.json's inside the `tgz` it still manages to install the optional dependencies :disappointed:

**Comment by stefanpenner** [comment]
> it doesn't work. Even though we have the patched package.json's inside the tgz it still manages to install the optional dependencies

This should likely be opened as a bug on NPM, bundledDependencies package.json should be their source of truth, not those of `npm`.

**Comment by patocallaghan** [comment]
Sure, I'll open an issue later tonight.

With regards forking the offending libs, does this mean we have to fork the tree of dependencies, from testem down?

```
                                 /  engine.io -> ws
testem -> socket.io / 
                               \
                                 \ socket.io-client -> engine.io-client
```

Meaning 6 packages forked? Or is there a better way?

**Comment by patocallaghan** [comment]
I've opened an issue on NPM https://github.com/npm/npm/issues/10283

**Comment by patocallaghan** [comment]
So I've gone ahead and forked the following packages under my account and linked them up so we no longer install those native optional dependencies. This feels kind of nasty having to fork all of these libs and link them up, but not sure if there's a better way of doing it. Any ideas?

-- testem@0.9.8 - [diff](https://github.com/airportyh/testem/compare/390a068...patocallaghan:0.9.8-pure)
&nbsp;&nbsp;-- socket.io@1.3.7 - [diff](https://github.com/socketio/socket.io/compare/e2ebd43...patocallaghan:1.3.7-pure)
&nbsp;&nbsp;&nbsp;&nbsp;-- engine.io@1.5.4 - [diff](https://github.com/socketio/engine.io/compare/6032a13...patocallaghan:1.5.4-pure)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-- ws@0.8.0 - [diff](https://github.com/websockets/ws/compare/0.8.0...patocallaghan:0.8.0-pure)
&nbsp;&nbsp;&nbsp;&nbsp;-- socket.io-client@1.3.7 - [diff](https://github.com/socketio/socket.io-client/compare/3fe5c2a...patocallaghan:1.3.7-pure)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-- engine.io-client@1.5.4 - [diff](https://github.com/socketio/engine.io-client/compare/aede981...patocallaghan:1.5.4-pure)

**Comment by stefanpenner** [comment]
@johanneswuerbach would testem be interested in using the pure variants? (that would remove atleast 1 lib we must fork)

**Comment by johanneswuerbach** [comment]
Technically yes, but I won't have time to maintain any of those forks :-( PR welcome!

**Comment by patocallaghan** [comment]
I'd be happy to keep those forks up to date for as long as we need them. @johanneswuerbach I'll open a PR against testem

**Comment by stefanpenner** [comment]
> I'd be happy to keep those forks up to date for as long as we need them. @johanneswuerbach I'll open a PR against testem

feel free to add me to the corresponding REPO, i'll aide and help maintain them.

**Comment by stefanpenner** [comment]
llooks like maybe some legit windows failures (Rerunning just in-case) but stack was:

```

object is not a function
 
TypeError: object is not a function
    at C:\projects\ember-cli\node_modules\testem\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\lib\transports\polling.js:23:13
    at Object.<anonymous> (C:\projects\ember-cli\node_modules\testem\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\lib\transports\polling.js:25:3)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\projects\ember-cli\node_modules\testem\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\lib\transports\polling-xhr.js:6:15)
    at Module._compile (module.js:460:26)
```

**Comment by patocallaghan** [comment]
Oh yeah there would have bee. I sorted it and kicked the Travis side. Once the PR gets merged on the testem side and we get a new release, I can finalize this PR..

**Comment by johanneswuerbach** [comment]
@patocallaghan you change is included in `0.9.9` :-)

**Comment by patocallaghan** [comment]
Thanks @johanneswuerbach!!! Much appreciated. 

@stefanpenner I've updated the PR with the new testem so once it's all :green_heart: we should be good to go

**Comment by stefanpenner** [comment]
> @stefanpenner I've updated the PR with the new testem so once it's all  we should be good to go
>  Hide all checks

woohoo, just in-time for this weekends release.

**Comment by patocallaghan** [comment]
:tada:

**Comment by chadhietala** [comment]
@humu r+

**Comment by chadhietala** [comment]
@homu r+

**Comment by tim-evans** [comment]
ember-cli is now failing to install due to `engine.io-client-pure` not being an available package. It seem that https://github.com/socketio/socket.io-client/blob/master/package.json#L15 now references `automattic/engine.io-client#ea5b5f` rather than `socketio/engine.io-client#ea5b5f`.

Any ideas on how to resolve this?

**Comment by tim-evans** [comment]
Gosh. Lemme clarify.

`engine.io-client-pure` doesn't exist on [npm](https://www.npmjs.com/package/engine.io-client-pure).

This module is required through the following chain

```
testem
└─ patocallaghan/socket.io#1.3.7-pure
  └─ socket.io-client-pure
      └─ engine.io-client-pure
```

**Comment by tim-evans** [comment]
NEVERMIND. Ignore me. I see you guys are working on it. :+1: :shipit:

**Pull request merged**
