### PR TITLE
Upgrade broccoli-merge-trees

### PR DESCRIPTION
**Pull request by joliss**
broccoli-merge-trees 0.2.2 uses the broccoli-plugin base class.

### CODE REVIEW

**Comment by stefanpenner** [comment]
maybe a legit failure (or likely something funky in our tests)


```
  1) broccoli/ember-app addons addonTreesFor addonTreesFor is called properly styles calls addonTreesFor and merges with overwrite:
     TypeError: Cannot read property '0' of undefined
      at Context.<anonymous> (tests/unit/broccoli/ember-app-test.js:353:40)

```

**Comment by stefanpenner** [comment]
ya something brittle and likely poking around private api https://github.com/ember-cli/ember-cli/blob/master/tests/unit/broccoli/ember-app-test.js#L353

**Comment by rwjblue** [comment]
egads!

**Comment by stefanpenner** [comment]
depended on by https://github.com/ember-cli/ember-cli/pull/4621

will take a look shortly.

**Comment by stefanpenner** [comment]
rebase + fixed brittle test: https://github.com/ember-cli/ember-cli/pull/4622

**Pull request closed without merging**
