### PR TITLE
Updated testem / phantomjs 2.0 support

### PR DESCRIPTION
**Pull request by johanneswuerbach**
All changes: https://github.com/airportyh/testem/compare/v0.6.31...v0.6.37

### CODE REVIEW

**Comment by stefanpenner** [comment]
Wow cool. Is phantom 2.0 ready? When can we enable it be default. I am eager to bid phantom 1.x good bye

**Comment by johanneswuerbach** [comment]
Yep, http://phantomjs.org/release-2.0.html
Testem was using some deprecated phantom 1.x controls, but now supports both versions. Travis has only 1.9 preinstalled, but I 2.0 works locally for me.

**Comment by stefanpenner** [comment]
Omg how have I missed this!  Let's but the folks at travis

**Comment by johanneswuerbach** [comment]
The homebrew release was only 3 days ago https://github.com/Homebrew/homebrew/commit/0f79de11e2ed0368f03073bc950f65d1ef59a16b, so you aren't totally outdated :laughing:

**Comment by stefanpenner** [comment]
Is it wonderful and amazing?

**Comment by johanneswuerbach** [comment]
Isn't everything new wonderful and amazing? I didn't really use the new version yet, so yes, it is still amazing :wink:

**Comment by kenips** [comment]
felt into the trap of always running `brew upgrade` here too. Thanks! Hopefully 0.1.13 soon :)!

**Pull request merged**
