### PR TITLE
Bump ember to 1.13.12

### PR DESCRIPTION
**Pull request by san650**

### CODE REVIEW

**Comment by stefanpenner** [comment]
LGTM

**Comment by rwjblue** [comment]
@homu r+

**Comment by kellyselden** [comment]
Does this mean jquery can be bumped up to 1.12 safely?

**Comment by rwjblue** [comment]
@kellyselden - Sadly no.  1.13.12 is strictly a security release. Once all the security stuff is done, I'll be releasing 1.13.13 with the jQuery assertion change.

**Comment by kellyselden** [comment]
@rwjblue Ok. I was mistaken

**Comment by rwjblue** [comment]
@homu retry

**Pull request merged**
