### PR TITLE
Prints an error message instead of throwing an error

### PR DESCRIPTION
**Pull request by twokul**
fixes https://github.com/ember-cli/ember-cli/issues/6172

### CODE REVIEW

**Comment by stefanpenner** [comment]
Seems reasonable, although if possible a quick unit test would be lovely.

**Comment by nathanhammond** [comment]
I suppose we're treating this as a "non-exceptional" error with this strategy. No, it didn't get you what you thought it would, but it _did_ run to completion.

I'm comfortable with that. @ember-cli/core?

**Comment by Turbo87** [comment]
I'm fine with this changed, although given the new simplicity of the `validateAssetPath()` method I'd vote for inlining that method completely, otherwise the name might also be a bit misleading.

**Comment by twokul** [comment]
@stefanpenner will add a test today

@Turbo87 sure or maybe rename to better communicate what it does

**Comment by twokul** [comment]
@stefanpenner turns out we have decent code coverage and scenario with error message is tested. let me know if you want me to add additional tests.

**Comment by stefanpenner** [comment]
@twokul good to hear there are lots of existing tests, is it possible though to add 1 additional scenario:

```
Prints an error message instead of throwing an error 
```

**Comment by twokul** [comment]
@stefanpenner imo seems arbitrary? you wouldn’t write that kind of test if the original behaviour was to just print a message and keep going, basically testing behaviour that does not exist anymore. that said I can add a test, just wanted to make sure

**Comment by stefanpenner** [comment]
@twokul alright, if you feel strongly the change in behavior isn't worth testing. I'm fine with skipping :)

**Comment by twokul** [comment]
@stefanpenner added a test, good Sir. thanks for the review 😄

**Comment by stefanpenner** [comment]
:shipit:  when green.

**Pull request merged**
