### PR TITLE
Documentation Theme

### PR DESCRIPTION
**Pull request by Turbo87**
This PR adds a custom theme for the YUIDoc output

screenshot of the current state

### CODE REVIEW

**Comment by Turbo87** [comment]
bildschirmfoto 2016-04-27 um 18 33 17

**Comment by stefanpenner** [comment]
Nice 

@leo may also want at this, let's see.

**Comment by leo** [comment]
Where does this show up?

**Comment by Turbo87** [comment]
@leo http://emberjs.com/api/

**Comment by Turbo87** [comment]
bildschirmfoto 2016-04-27 um 19 44 27

**Comment by Turbo87** [comment]
@stefanpenner I've extracted the theme into a separate project at https://github.com/Turbo87/yuidoc-ember-cli-theme. This PR pulls it in via npm and should be ready for merging now. I'll iterate further in the other project.

**Comment by leo** [comment]
Ahhh, okay. Currently pretty busy atm, so I won't be able to enhance anything now. Might be able to look into it later after it landed! :blush:

**Comment by stefanpenner** [comment]
this looks like a good step, we can continue to improve over time. Thanks!

@homu r+

**Pull request merged**
