### PR TITLE
[ENHANCEMENT] Better ASCII art

### LINKED ISSUE #2587: Commission better ASCII art for the initial commit message
Tomster and "Ember" are unfortunately obscure in this auto-generated ASCII block, appearing in `git log` in new projects.

```
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,....,,........,.. . .  .,...........,
,,,,,,,,,,,,,,,:...,,.,,,,,,,,,,,,,,,,,,,,,.,,.,,......... .~.::::.  ..........,
,,,,,,,,,,,,.  .. ..    .. ..,... ,+7ZOOOZ7=, . .,.....   ~.=::::::  ..........,
,,,,,,,,,,  .====IIIIISZ. .. 7ZSIIIIIIIIIIIIIII7ZO... .::..+:::::::= ..........,
,,,,,,,,, .=~:~~:~==IIIIII7ZIIIIIIIIIIIIIIIIIIIIIIISZ:....+::::::::, ..........,
,,,,,,,,,  :::~~~~~~~==77ZIIIIIIIIIIIIIIIIIIIIIIIIIII7O..=~:::::::~............,
,,,,,,,,,..~:::~~~~~~~=ZIIIII77777777777IIIIIIIIIIIIIIIZ==::::::::. :..........,
,,,,,,,,,,. ::::~~~~~:=I7777777777777777777777IIIIIIIIIIS=:::::::. ............,
,,,,,,,,,,. .::,:~~~:::SO8DD8OSII7777777777777777IIIIIIIIZ::::::  .............,
,,,,,,,,,,,, .~M8ZD888OOOOOOOOOOO8DMM7I77I7Z8NMMMMNDZIIIIIZ:::+. ..............,
,,,,,,,,,,,,=. ZM888DD,::,,,,,:SN88O88DDD88OOO88888888OO8MM~=.S, ..............,
,,,,,,,,,,,,,~   N8D:             :88NMMM888O,,,...,:,=NDD8~:88M..,............,
,,,,,,,,,,,,,,, .M8D,     MS      ,8DZS7SM8S.           .,ND8DNM...............,
,,,,,,,,,,,,,,,. ,DD     OMN     .O8M777S88M      =D      ?DD~  ... ............
,,,,,,,,,,,,,,,,. M8~.   .M.     ~8M77777SM8.     DMO    .ND= ..   .............
,,,,,,,,,,,,,,,, .~M8:          =8D877777SMDN.     M,     DM= ..................
,,,,,,,,,,,,,,,  :.~M8NO?=:=?ZM88DMS7===I77N8M.         .MM7S ..................
,,,,,,,,,,,,,,  :...=7MNDDDDDNMMNSS777?777SZND888NDS+==O8M7IIZ..................
,,,,,,,,,,,,,  :.....,,,:~~=SSSS77777777777SS7NMMNDDDDDNM7IIIIS.................
,,,,,,,,,,,,..~.......,,,,,,,=777777777777777777SZMMOS777IIIIIS ................
,,,,,,,,,,,, ~..........:~~:,,,:?7777777SSS8MMMN88DZ777777IIIII+.~+?I777777II?+=
,,,,,,,,,,,.:..............?N8DNNN++=~~::,,NN8888D=,,......IIIIO.SZZZZZZZZZZZZZZ
,,,,,,,,,,. :................N8888S...,....M88888O,,,........IIZ.~77IIIIIIII7777
,,,,,,,,,, :...........,.....+8888N....,...NN888M,,,.........,IS.:II77IIIIIIIIII
,,,,,,,,,, ~.................,M88D+~...~..===~+M,,,...........IO.=++?I7777IIIIII
,,,,,,,,,,.~.................,,DM=====::::::::::,,............I7 =====+?I777IIII
.......... ,.................,:M===:::::::::::=,,............~7 .==++====+?I77II
..........,.~.................,,=:::::::::,. ,,,.............IS .. .===+====?I77
,,,,,,,,,,,  ~.......................,,,. ..,.  ............:Z.  .+.    ======?I
,,,,,,,,,,,, .~........................ .S7777  ............:.  .~:,. =..=======
.............,.~,...................., .777S77S  ..........~. . .::=+::. =======
,,,,,,,,,,,,,,=. .~....................777 .777.........,:Z  .:::::::~....~=====
.................:..::...............  77+  77S......~:777ZZ  .=::::::::, :~~===
,,,,,,,,,,,,,,,,,, .ZZ7I::............S77..S77?  ~:,,~+7777Z7Z7I7+~::~+   ~~::~=
,,,,,,,,,,,,,,,,, .ZZ7777~,,,:~~~:::  77I ~777  ,,,,,,,=777IIIII77O.  . ~~~~~~::
,,,,,,,,,,,,,,,,. ,ZZII7=,,,,,,,,,,. =77 .777. .,,,,,,...:IIIIII7Z  :~~~~~~~~~~~
........,.. .... ., . 7~.. .,,. ..,. 777.777=  ....... .   .III+ . .~.  ~~~~~~~~
.......  .   .    . ,.   . .  .  .. .S77777?.   ....  ..7S7      ,   ... :~~~~~~
...... .S777777.  +77+  7777  777S  .777777777?     .S777777    77?.S777 .~~~~~~
..... .7777.+777 .S77. 7777+.7777I   7777777777I   .S77S.?77+  I77+S7777 .~~~~~~
....  777S   77I  777 77777 77777:  ,777~. .7777.  777S.  77: .777+7777? .~.. :~
,.    777  .S77. ?77SS7777SS77777   I77S    ?777.  777  .S77. .77777 777   .:. :
  7S==7777777=  .S77777 77777 77S. .S77,    777I  ?7777777S.  I77777.777SS777+ .
 :77777777S,.  .:77777 =7777= 77S. .777.   .777..7777777?.  .I77777. ,777777. .~
   ..7777+... S7777777 7777S. 77S. S777.  .S7777777777S .. S777777+ . ..: . ..~~
,,,. .S7777777777777S. S777,  777777777777777777S. 77777777777777S..~~,. .:~~~~~
:::::..~777777I..S77.   77S  .S777S .?77777S?..  ..  S77777S  ?77  :~~~~~~~~~~~~
.....   .....   . . ...    ... ..  .          ..==::.  ...  .  . ..~~~~~~~~~~~~~
.........,.,:.....,:.....=.....,,....,.:.... ...:+~::::,,::::::,:~~~~~~~~~~~~~~~
```

Automated tools produce ASCII images of very low quality compared with some of the handcrafted ASCII art easily found online. To honor Tomster's place in history starting with ember-cli v1, it is worth asking the community (perhaps in an open competition) to handcraft the first commit ASCII art with a preference for smaller dimensions.

### PR DESCRIPTION
**Pull request by johnnyshields**
fixes #2587

### CODE REVIEW

**Comment by joostdevries** [comment]
:+1:

**Comment by chadhietala** [comment]
:100: Better ASCII art is better.

**Comment by stefanpenner** [comment]
this breaks 0.1.10 on some shells, seems like some characters are escaping out of the commit message

**Comment by stefanpenner** [comment]
the "`"

**Comment by stefanpenner** [comment]
hot-patching the tomster...

**Comment by johnnyshields** [comment]
yikes yep apologies for that!

**Comment by johnnyshields** [comment]
there are single quote chars as well '

**Comment by stefanpenner** [comment]
no problem, https://github.com/ember-cli/ember-cli/pull/3126

**Comment by stefanpenner** [comment]
@johnnyshields if you have any ideas to fixup design issues i may have caused with 3126 let me know. I just needed to quickly fix it so i can release and got to sleep

**Comment by johnnyshields** [comment]
Apologies again for the headache I'll check it in a bit.

**Comment by johnnyshields** [comment]
Did minor touchups #3130 if you're interested. No `, ', or " chars this time.

**Pull request merged**
