### PR TITLE
print bower and phantom versions in travis logs

### PR DESCRIPTION
**Pull request by kellyselden**
Added it to my app. Thought it would be useful for everyone to compliment travis' default node, npm, and nvm printing.

capture

### CODE REVIEW

**Comment by kellyselden** [comment]
Also, I was curious if phantomjs was on v2 yet on travis, the main reason I added it.

**Comment by stefanpenner** [comment]
@homu r+

**Comment by Turbo87** [comment]
@kellyselden are you sure that phantomjs output is working as expect?

I'm using `npm install phantomjs-prebuilt` [here](https://github.com/Turbo87/skylines-ember/blob/master/.travis.yml#L19) and the test output shows PhantomJS 2.1, but your screenshot shows 1.9 instead.

**Comment by kellyselden** [comment]
@Turbo87 You're on to something. The phantomjs version is not finding the one ember uses for some reason?

**Comment by Turbo87** [comment]
yep. I'm not sure how testem looks up phantomjs, but apparently it is not using the same one as `phantomjs --version`.

**Comment by kellyselden** [comment]
Filed an issue #5906

**Pull request merged**
