### PR TITLE
Update help string for route blueprint/generator

### PR DESCRIPTION
**Pull request by jhr007**
Updated the 'route' description in the blueprint to reflect it also generates a template file.

### CODE REVIEW

**Comment by kellyselden** [comment]
The matching tests must be updated, but then :+1:

**Comment by jhr007** [comment]
Done. The tests should be restarted.

**Comment by jhr007** [comment]
Never mind, the tests already kicked off. <spam-apology>

**Comment by kellyselden** [comment]
@homu r+

**Pull request merged**
