### PR TITLE
Update ember-ajax to 2.0.

### PR DESCRIPTION
**Pull request by rwjblue**

### CODE REVIEW

**Comment by jaswilli** [comment]
It would be nice to get `status` code handling sorted out before a new major version bump is included in ember-cli. See: https://github.com/ember-cli/ember-ajax/pull/62

**Comment by alexlafroscia** [comment]
@jaswilli I took care of that, `2.0.1` has that fix as @rwjblue suggested.

**Comment by rwjblue** [comment]
Thanks @jaswilli for catching that, should be sorted now with 2.0.1. I'll update the version in this PR shortly.

**Comment by rwjblue** [comment]
Updated to ember-ajax@2.0.1.

**Comment by rwjblue** [comment]
@homu r+

**Pull request merged**
