### PR TITLE
fix: allow use of prettier on index.html

### PR DESCRIPTION
**Pull request by lougreenwood**
### Problem

When using Prettier to auto-format HTML files on save, if the `index.html` file is saved, Prettier will perform the following conversion where space padding is applied to `{{rootURL}}`:

from:
`<script src="{{rootURL}}assets/vendor.js"></script>`

to:
`<script src="{{ rootURL }}assets/vendor.js"></script>`

Because `ember-cli` expects exactly `{{rootURL}}` - the output of Prettier causes the app to fail to boot because `ember-cli` has not performed the usual replacements on `{{ rootURL }}`.

### Solution

Add optional spaces to the regex used to identify these `{{rootURL}}` tags in index.html.

This PR also allows space padding for the following tags: `{{EMBER_ENV}}` `{{MODULE_PREFIX}}`.

**Note:**
The fix was not added for `{{content-for ...}}` because Prettier only applies this padding when a tag is part of a string literal (`<script src="{{ rootURL }}...">`) and `{{content-for ...}}` seems to not be used in string literals.

This can easily be added for safety if required.

### CODE REVIEW

**Comment by rwjblue** [comment]
@lougreenwood - This looks good, would you mind updating this PR in the GitHub UI to target the `beta` branch and rebasing out all but this commit? If that doesn't make sense, I'm happy to help you do it.

**Comment by rwjblue** [comment]
Ironically, CI is failing due to prettier issues.

```
/home/travis/build/ember-cli/ember-cli/tests/unit/utilities/ember-app-utils-test.js
  19:27  error  Replace `"{{rootURL}}",·"{{·rootURL·}}",·"foo"` with `'{{rootURL}}',·'{{·rootURL·}}',·'foo'`                          prettier/prettier
  25:11  error  Insert `·`                                                                                                            prettier/prettier
  28:9   error  Insert `;`                                                                                                            prettier/prettier
  30:23  error  Insert `;`                                                                                                            prettier/prettier
  31:48  error  Insert `;`                                                                                                            prettier/prettier
  38:27  error  Replace `"{{EMBER_ENV}}",·"{{·EMBER_ENV·}}",·"foo"` with `'{{EMBER_ENV}}',·'{{·EMBER_ENV·}}',·'foo'`                  prettier/prettier
  44:11  error  Insert `·`                                                                                                            prettier/prettier
  47:9   error  Insert `;`                                                                                                            prettier/prettier
  49:23  error  Insert `;`                                                                                                            prettier/prettier
  50:48  error  Insert `;`                                                                                                            prettier/prettier
  57:27  error  Replace `"{{MODULE_PREFIX}}",·"{{·MODULE_PREFIX·}}",·"foo"` with `'{{MODULE_PREFIX}}',·'{{·MODULE_PREFIX·}}',·'foo'`  prettier/prettier
  63:11  error  Insert `·`                                                                                                            prettier/prettier
  66:9   error  Insert `;`                                                                                                            prettier/prettier
  68:23  error  Insert `;`                                                                                                            prettier/prettier
  69:48  error  Insert `;`                                                                                                            prettier/prettier
```

I think you can run `yarn lint --fix` to get it auto-fixed.

**Comment by lougreenwood** [comment]
I think I made a mess of trying to rebase this, so I'm going to create a fresh branch off of beta and cherry pick my commits as a new PR for that new branch.

**Pull request closed without merging**
