### PR TITLE
print the `serving on http://host:port/basePath` after each rebuild

### PR DESCRIPTION
**Pull request by stefanpenner**
this has literally been killing me since the start of time.

- [x] fix tests

### CODE REVIEW

**Comment by Turbo87** [comment]
hmm... if you have a lot of build output then I understand the need to see that line *after* the build. I could however also imagine repeating those lines over and over being a little annoying... 🤔

**Comment by rwjblue** [comment]
I'm also in favor of this generally speaking.  I can't tell you how many times I have forgotten the port I was serving a given app on.

**Comment by stefanpenner** [comment]
I could put it on the same line as `build success`

```
build sucessful, serving on: http://localhost:4200
```

**Comment by stefanpenner** [comment]
screen shot 2017-03-10 at 3 19 37 pm

**Comment by rwjblue** [comment]
@homu r+

**Pull request merged**
