### PR TITLE
enable both relative and absolute treePaths (npm v3 fix)

### PR DESCRIPTION
**Pull request by stefanpenner**
related PR to ember-cli-ic-ajax https://github.com/rwjblue/ember-cli-ic-ajax/pull/9

- [x] confirm it works
- [x] fix tests
- [x] release ember-cli-ic-ajax so the tests can possibly pass
- [ ] last windows failure

### CODE REVIEW

**Comment by rwjblue** [comment]
ember-cli-ic-ajax@0.1.3 was released, can you bump in this PR?

**Comment by rwjblue** [comment]
Rereleased ember-cli-ic-ajax as 0.2.0

**Comment by stefanpenner** [comment]
@rwjblue thanks, this should be updated. Lets see what CI says.

**Comment by rwjblue** [comment]
Restarting AppVeyor.

**Comment by rwjblue** [comment]
Released v0.2.1 of ember-cli-ic-ajax with a fix for Windows path issue (see https://github.com/rwjblue/ember-cli-ic-ajax/pull/12), might need to update that here for AppVeyor?

**Comment by rwjblue** [comment]
Needs a rebase, but I believe that the appveyor tests are unrelated...

**Comment by stefanpenner** [comment]
rebased, pending tests now.

**Comment by stefanpenner** [comment]
rerunnin the second travis-ci test

**Comment by stefanpenner** [comment]
checking what is up with appveyor

**Comment by stefanpenner** [comment]
windows failure looks legit: 
```
 1) Acceptance: addon-smoke-test ember addon foo, clean from scratch:
     the object {
  "code": 1
  "errors": []
  "output": [
    "version: 0.2.7--57bc72d91b\r\n"
    "Building\r\n"
    "Build failed.\r\n"
    "ENOTDIR, not a directory 'C:\\projects\\ember-cli\\tmp\\some-cool-addon\\node_modules\\ember-cli-ic-ajax\\node_modules\\ic-ajax\\dist\\cjs\\main.js'\r\n"
    "Error: ENOTDIR, not a directory 'C:\\projects\\ember-cli\\tmp\\some-cool-addon\\node_modules\\ember-cli-ic-ajax\\node_modules\\ic-ajax\\dist\\cjs\\main.js'\n    at Error (native)\n    at Object.fs.readdirSync (fs.js:761:18)\n    at C:\\projects\\ember-cli\\node_modules\\broccoli-merge-trees\\index.js:32:21\n    at Array.map (native)\n    at mergeRelativePath (C:\\projects\\ember-cli\\node_modules\\broccoli-merge-trees\\index.js:30:29)\n    at C:\\projects\\ember-cli\\node_modules\\broccoli-merge-trees\\index.js:23:5\n    at lib$rsvp$$internal$$tryCatch (C:\\projects\\ember-cli\\node_modules\\rsvp\\dist\\rsvp.js:489:16)\n    at lib$rsvp$$internal$$invokeCallback (C:\\projects\\ember-cli\\node_modules\\rsvp\\dist\\rsvp.js:501:17)\n    at lib$rsvp$$internal$$publish (C:\\projects\\ember-cli\\node_modules\\rsvp\\dist\\rsvp.js:472:11)\n    at lib$rsvp$asap$$flush (C:\\projects\\ember-cli\\node_modules\\rsvp\\dist\\rsvp.js:1290:9)\n    at process._tickCallback (node.js:355:11)\r\n"
  ]
} was thrown, throw an Error :)
  Error: the object {
    "code": 1
    "errors": []
    "output": [
      "version: 0.2.7--57bc72d91b\r\n"
      "Building\r\n"
      "Build failed.\r\n"
    ]
  } was thrown, throw an Error :)
 
  2) Acceptance: addon-smoke-test ember addon without addon/ directory:
     Error: timeout of 450000ms exceeded. Ensure the done() callback is being called in this test.
```

**Comment by stefanpenner** [comment]
think I have a fix, lets see..

**Pull request merged**
