### PR TITLE
Normalize end-of-line characters in strings to compare prior to diffing

### LINKED ISSUE #6767: ember init - diff shows each line changed when having non-uniform line endings
Diffing in `lib/models/file-info` seems to not ignore white space differences and this caused difficulties for me when working on systems with unequal line endings.
`init` will prompt for every single file to be overwritten. It will show that each line is different. 

Procedure:
1) Updated ember-cli on a windows machine
2) Checked out an ember app located on a mac and did all the usual pkg update procedures, finalizing with `ember init`
3) `ember init` complained that all files differ on every line, turns out because of the varying line endings

There might be some line ending normalization needed in this case prior to passing the input to createPatch. I think my git config is also as it should be: `core.autocrlf input` on mac and `core.autocrlf true` on windows, since on windows it is definitely preferred to have \r\n line endings in the same way it is not preferred to have \r\n on bsd or gnu/linux.

### PR DESCRIPTION
**Pull request by koopa**
Resolves #6767

### CODE REVIEW

**Comment by stefanpenner** [comment]
looks good, can a unit test be added?

**Comment by koopa** [comment]
I will gladly provide one as soon as I figure out how to properly (still quite new to this).
Also I messed up with the replace, I should probably wait until that is resolved and not try to replace a promise :)

**Comment by btecu** [comment]
Thanks for fixing this!

**Comment by stefanpenner** [comment]
it appears there is a legit test failure on posix:

```
not ok 770 Unit - FileInfo normalizes line endings before comparing files
  AssertionError: expected 'confirm' to equal 'identical'
      at tests/unit/models/file-info-test.js:177:23
      at tryCatch (node_modules/rsvp/dist/rsvp.js:538:12)
      at invokeCallback (node_modules/rsvp/dist/rsvp.js:553:13)
      at publish (node_modules/rsvp/dist/rsvp.js:521:7)
      at flush (node_modules/rsvp/dist/rsvp.js:2373:5)
```

**Comment by koopa** [comment]
This should take care of that

**Comment by Turbo87** [comment]
@homu r+

**Comment by Turbo87** [comment]
@homu retry

**Pull request merged**
