### PR TITLE
[ENHANCEMENT] Exclude dist and tmp dirs from search in vscode

### PR DESCRIPTION
**Pull request by Tyriar**
Improve find in files in Visual Studio Code by excluding generated files in
a workspace config file.

---

Not sure if you accept editor-specific changes like this but I found ember-cli far more convenient with vscode when this was included after a little experimentation. (FYI I work on vscode)

image

I couldn't find any similar tests but let me know if you want one.

### CODE REVIEW

**Comment by stefanpenner** [comment]
We don't currently provide editor specific configuration, rather such configuration should be provided be an addon. Otherwise we will end up generating a dozen set of such configurations speculatively. 

Although I recognize the value, the cost of lots of unused files also quite high.

**Comment by Turbo87** [comment]
I tend to agree. Creating such files should probably be the responsibility of vsc-ember-cli instead.

**Comment by Tyriar** [comment]
No worries, thanks for considering the change.

**Comment by stefanpenner** [comment]
@Tyriar if you have an idea to allow us to bundle these helpful files, without eagerly polluting the users file trees, im all ears.

**Comment by Turbo87** [comment]
something like an `ember-cli-ide-files` addon with blueprints for the major IDEs maybe?

**Comment by Tyriar** [comment]
The best thing may be to have vscode use the contents of `.gitignore` as part of `search.exclude`, that way this behavior would be the default.

**Comment by stefanpenner** [comment]
@Tyriar yes totally

**Pull request closed without merging**
