### PR TITLE
Update ember-cli-qunit to mitigate Chrome sourcemap issue.

### PR DESCRIPTION
**Pull request by rwjblue**
https://github.com/ember-cli/ember-cli-qunit/pull/39

### CODE REVIEW

**Comment by stefanpenner** [comment]
I mentioned this to @paul_irish, he had not been aware. Someone should open a chrome dev tools bug report.

**Comment by nathanpalmer** [comment]
I'm really glad to see this here. It's been a big painpoint for us during the conversion to ember-cli.

Related chromium bug: https://code.google.com/p/chromium/issues/detail?id=424191 -- I haven't dug into it too much yet to see if it gets at the room of what we're looking at here.

**Comment by SirZach** [comment]
will <code>ember-cli-mocha</code> be required to make similar adjustments to solve this issue? i'm noticing this bug and i'm not using <code>ember-cli-qunit</code>

**Comment by rwjblue** [comment]
@SirZach - ember-cli-mocha is updated with these changes as of 0.4.2: https://github.com/switchfly/ember-cli-mocha/pull/34

**Comment by mgenev** [comment]
i can't quite tell if this is fixed or what i'm supposed to do, my sourcemaps used to work and then they stopped at some upgrade of ember-cli :-/ I have 0.2.0 and it's still not working

**Pull request closed without merging**
