### PR TITLE
testem 1.3.0

### PR DESCRIPTION
**Pull request by kellyselden**

### CODE REVIEW

**Comment by kellyselden** [comment]
@homu r+

**Comment by johanneswuerbach** [comment]
Mind directly bumping to https://github.com/testem/testem/releases/tag/v1.3.0, I fixed another bug regarding the startup and testem is not failing more transparently when it can't connect to the browser.

**Comment by kellyselden** [comment]
@johanneswuerbach done.

**Comment by kellyselden** [comment]
@homu r+

**Pull request merged**
