### PR TITLE
Always create addon trees when developing an addon

### LINKED ISSUE #3906: [0.2.3] Unit test blueprint mistaken as actual test
I've only tried this in an addon environment. 

Step 1: `ember generate blueprint foo-test`
Step 2: Visit `/tests`
Step 3: TestLoader Failures: dummy/blueprints/foo-test: could not be loaded

screen shot 2015-04-15 at 12 00 44 pm

***Update*** It also happens in an app environment.

### PR DESCRIPTION
**Pull request by marcioj**
If we create a new addon and start the server `includedModules()` will return an empty object, since there isn't any module, so the addon tree is skipped.
But if later we add a new file, for instance using `ember g initializer foo`, these files aren't included in the pipeline because no tree was created initially and tests will fail with `Could not find module ember-simple-validate/initializers/foo imported from dummy/initializers/foo`

Fixes #3906

### CODE REVIEW

**Comment by marcioj** [comment]
Travis isn't helping today: `sh: 1: istanbul: not found` :(
Not sure if I'm doing something wrong here

**Comment by kellyselden** [comment]
I added the istanbul coverage, but I don't see anything that would cause this to stop working.

**Comment by marcioj** [comment]
Thanks for the reply @kellyselden.
I believe this is related with the travis ci cache.
Could you please cleanup the cache for this branch and restart the build?

**Comment by stefanpenner** [comment]
@marcioj i purged the cache, it seemed to solve this for other PR :)

**Comment by marcioj** [comment]
Thanks @stefanpenner!
Unfortunately my tests aren't passing in travis, I'll check it out tonight.

**Comment by stefanpenner** [comment]
@marcioj thanks :)

**Comment by marcioj** [comment]
After some debugging I found the issue. Looks like the `process.env.EMBER_ADDON_ENV` wasn't  being properly cleaned in [addon-test.js](https://github.com/ember-cli/ember-cli/blob/master/tests/unit/models/addon-test.js#L362).
`process.env.EMBER_ADDON_ENV = undefined` will coerce the undefined value to a string, which will return the string 'undefined' when called. This affect the EMBER_ADDON_ENV normalization done in [ember-addon.js](https://github.com/ember-cli/ember-cli/blob/master/lib/broccoli/ember-addon.js#L24), which will not setup the variable to 'development' because the 'undefined' string is present. And in the end will affect the [Addon#isDevelopingAddon](https://github.com/ember-cli/ember-cli/blob/master/lib/models/addon.js#L185) making it always return false and which make my tests fail since it's just intended to be used when the addon is being developed.
I changed addon-test.js to handle this.

**Comment by stefanpenner** [comment]
@marcioj nice find!

**Comment by marcioj** [comment]
I changed the way I was closing the test server to just send a `q`, like we do in the terminal.
Previously using `killCliProcess` was causing a problem of don't killing phantomjs processes, so other tests running phantomjs will hang forever.
Unfortunately sending the `q` in this way will throw other error which I sent a fix to testem in airportyh/testem#544.
With this fix I believe all will work. So we need to wait for this patch be merged and a new testem version be released.

**Comment by johanneswuerbach** [comment]
The fix is included in testem `v0.8.2`, thanks for the PR.

**Comment by marcioj** [comment]
Thanks for the release @johanneswuerbach !

**Comment by stefanpenner** [comment]
@johanneswuerbach <3

**Comment by marcioj** [comment]
@stefanpenner :+1: / :-1: ?

**Pull request merged**
