### PR TITLE
correct code formatting

### PR DESCRIPTION
**Pull request by bekzod**
makes it clearer confusing formatting

### CODE REVIEW

**Comment by stefanpenner** [comment]
```
    413:23  error  Unexpected block statement surrounding arrow body  arrow-body-style
    418:47  error  Missing semicolon      
```

Please make sure to run lint tests before :)

**Comment by Turbo87** [comment]
I don't think this change makes the code any more readable then what we had before. What we would like to use are async functions but due to our Node support policy we unfortunately can't use those yet...

**Comment by bekzod** [comment]
ok, but I haven't seen such promise formatting before :P , free to close

**Comment by stefanpenner** [comment]
> I don't think this change makes the code any more readable then what we had before. What we would like to use are async functions but due to our Node support policy we unfortunately can't use those yet...

we could use `co`

**Comment by Turbo87** [comment]
> we could use co

unfortunately we can't use co-wrapped functions as ES6 class methods 😞

**Pull request closed without merging**
