### PR TITLE
Config hook called too soon during serve

### PR DESCRIPTION
**Pull request by thoov**
Porting: https://github.com/ember-cli/ember-cli/pull/7861 to the release branch

### CODE REVIEW

**Comment by Turbo87** [comment]
given https://github.com/ember-cli/ember-cli/issues/7870 I don't think we should port this back to the `release` branch until the issue is solved

**Comment by rwjblue** [comment]
Agreed

**Comment by rwjblue** [comment]
The fix for the reported issue landed in https://github.com/ember-cli/ember-cli/pull/7875 (though is still not included here ATM)

**Comment by stefanpenner** [comment]
restarting appveyor.

**Comment by Turbo87** [comment]
restarted appveyor again. let's hope it works this time…

**Comment by stefanpenner** [comment]
@Turbo87 I think `release` is just having issues, unrelated to our code changes...

**Pull request closed without merging**
