### PR TITLE
Make npm/bower install more copy/paste friendly

### PR DESCRIPTION
**Pull request by knownasilya**

### CODE REVIEW

**Comment by rwjblue** [comment]
I'm fairly sure && doesn't work on all supported platforms.

**Comment by knownasilya** [comment]
Does `rm -rf` work one windows? I assumed that those instructions were not for all OSs. But `&&` does work on windows http://stackoverflow.com/a/8055430/483616

**Comment by jonnii** [comment]
@knownasilya `&&` only works in `cmd.exe`, doesn't work if the user is using powershell.

**Comment by knownasilya** [comment]
What about `rm -rf`, which is already in the instructions.

**Comment by jonnii** [comment]
@knownasilya I _think_ so? I can test it tomorrow when I'm at work. I know `rm` exists as an alias, but there are two flags to `remove-item` that start with `f` (filter and force) so not sure if you need to disambiguate by doing something like `rm -force -recurse`.

**Comment by stefanpenner** [comment]
also doesn't work in fish shell

**Pull request closed without merging**
