### PR TITLE
Bump ember-qunit-notification version.

### PR DESCRIPTION
**Pull request by nathanhammond**
Dependent upon:
https://github.com/dockyard/ember-qunit-notifications/pull/6 (And a 0.1.0 tag of that project.)

Which was dependent upon
https://github.com/dockyard/qunit-notifications/pull/24

Just cascading the changes through the ecosystem.

### CODE REVIEW

**Comment by stefanpenner** [comment]
@nathanhammond can you rebase, master is now green.

**Comment by stefanpenner** [comment]
@homu r+

**Comment by nathanhammond** [comment]
@homu retry

**Comment by stefanpenner** [comment]
@homu retry

**Pull request merged**
