### PR TITLE
Fix reading npm package names with a version specifier

### LINKED ISSUE #5880: "ember install package@version" fails after npm
### What went wrong

I (and I think most users) expect `ember install` to match reasonably with `npm install` in terms of support for the way packages are defined. For example, I would expect both of these to result in the same version of the package being added to my project:

```sh
npm install ember-cp-validations@~2.7.0
ember install ember-cp-validations@~2.7.0
```

I'm now seeing that what happens if you attempt the `ember install` above is that the modification is made to `package.json`, but then the user gets an error

```
Install failed. Could not find addon with name: ember-cp-validations@~2.7.0
```

### Suspected cause

To me, this smells like we're losing the distinction between name and "name@target" at the time we attempt to run an installation blueprint. Sure enough, even after you get the above error, if you run the blueprint explicitly

```
ember g ember-cp-validations
```

Everything is run as you would expect.

### This used to work fine

- I tested with ember-cli `1.13.8` and `2.5.0`, and this bug doesn't appear to be present

### To reproduce

```sh
ember new ember123 && \
   cd ember123 && \
   npm install --save-dev ember-cli@2.6.0-beta.2 && \
   ember install ember-cp-validations@~2.7.0
```
 
Output from ember version --verbose:
```
ember-cli: 2.6.0-beta.2
http_parser: 2.6.2
node: 5.10.1
v8: 4.6.85.31
uv: 1.8.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 47
openssl: 1.0.2g
os: darwin x64
```

### PR DESCRIPTION
**Pull request by Turbo87**
This PR finishes https://github.com/ember-cli/ember-cli/pull/5883 and moves it to the `beta` branch.

Resolves #5880

/cc @martndemus @nathanhammond @mike-north @stefanpenner @rwjblue

### CODE REVIEW

**Comment by martndemus** [comment]
:+1:

**Comment by stefanpenner** [comment]
:shipit:

**Comment by nathanhammond** [comment]
🚢, waiting on tests for homu.

**Comment by nathanhammond** [comment]
(once landed I'll release our last beta.)

**Comment by Turbo87** [comment]
It would be awesome if you could give this a quick test drive before merging. It should work but I'm not sure I covered all the corner cases.

**Comment by Turbo87** [comment]
Travis is green now 🎉

**Comment by nathanhammond** [comment]
@homu r+

**Comment by Turbo87** [comment]
Looks like @homu *can* handle non-master branches :)

**Comment by cbfx** [comment]
strange.

```
› ember install sinon@^9.0.2
```

```
🚧  Installing packages... This might take a couple of minutes.
Yarn: Installed sinon@^9.0.2
Install failed. Could not find addon with name: sinon@^9.0.2
```

**Pull request merged**
