### PR TITLE
Sort package.json according to the package.json documentation

### PR DESCRIPTION
**Pull request by Turbo87**
This PR sorts our own `package.json` file according to the order in the [documentation](https://docs.npmjs.com/files/package.json). It also sorts that file in the `app` blueprint the same way and introduces [sort-package-json](https://github.com/keithamus/sort-package-json) to make sure that the file is sorted properly for the `addon` blueprint too.

Note that this is also the same order that `npm init` will create for you.

/cc @rwjblue @stefanpenner @kellyselden

### CODE REVIEW

**Comment by stefanpenner** [comment]
big 👍

**Comment by kellyselden** [comment]
Looks great!

**Comment by Turbo87** [comment]
I guess we shouldn't merge while ci is broken?

**Comment by nathanhammond** [comment]
Confirm that we should hold merge until we fix CI. 😞

**Comment by nathanhammond** [comment]
Restarted builds. Didn't review closely enough to actually approve.

**Comment by Turbo87** [comment]
@homu r+

**Pull request merged**
