### PR TITLE
Revert #6193

### PR DESCRIPTION
**Pull request by nathanhammond**
Optimistic change, didn't actually do any testing. RE: https://github.com/ember-cli/ember-cli/issues/6274

### CODE REVIEW

**Comment by nathanhammond** [comment]
@homu r+

**Comment by Turbo87** [comment]
> Appears to work

Unfortunately not...

**Comment by nathanhammond** [comment]
Intermittent failures, not the 100% red of before.

**Comment by nathanhammond** [comment]
Just restarted the job, about to ask homu for a retry which I know will pass.

**Comment by Turbo87** [comment]
did you see my comment in https://github.com/ember-cli/ember-cli/issues/6274? I have a feeling something else might be wrong and this would just hide the symptoms.

**Comment by Turbo87** [comment]
FWIW after reading the backlog I'm fine with this change but I'm still not quite comfortable not knowing what was actually causing those issues.

**Comment by Turbo87** [comment]
@nathanhammond this needs to be backported to the beta branch

**Comment by nathanhammond** [comment]
Backported; we've been broken for so long that master and beta hadn't diverged.

**Comment by rwwagner90** [comment]
@nathanhammond I just threw together a quick polyfill for this, to fix my 1.13 failures. If you would like, I could submit a PR to use it. https://github.com/shipshapecode/ember-assign-polyfill

**Comment by nathanhammond** [comment]
TODO: Confirm if we have checked in an old `bower.json` as a fixture.

**Comment by rwjblue** [comment]
Likely caused by the error fixed in https://github.com/emberjs/ember.js/pull/14366

**Comment by Turbo87** [comment]
makes sense. should we revert the revert?

**Comment by rwjblue** [comment]
Ya, we should give it a whirl.

**Comment by nathanhammond** [comment]
https://github.com/ember-cli/ember-cli/pull/6305

**Pull request merged**
