### PR TITLE
adding new changelog diffs

### PR DESCRIPTION
**Pull request by kellyselden**
cc @nathanhammond

### CODE REVIEW

**Comment by nathanhammond** [comment]
@homu r+

**Comment by stefanpenner** [comment]
@nathanhammond try again, you are now a homu ember-cli reviewer

**Comment by nathanhammond** [comment]
@homu r+

**Comment by kellyselden** [comment]
@stefanpenner are people other than you able to add homu approvers?

**Comment by stefanpenner** [comment]
@kellyselden unsure, what do you see when you navigate to http://homu.io/r/ember-cli/ember-cli ?

**Comment by Turbo87** [comment]
I've updated the release notes at https://github.com/ember-cli/ember-cli/releases/tag/v2.4.3 with these changes too

**Comment by kellyselden** [comment]
@Turbo87 thanks. I got sidetracked and forgot

**Pull request merged**
