### PR TITLE
Clean up dependencies

### PR DESCRIPTION
**Pull request by Turbo87**
This PR cleans up the `dependencies` section in the `package.json` file. It removes several dependencies that are no longer needed now that most blueprints are moved into the legacy blueprints repository. It also updates the "chalk" dependency and does some general cleanup.

### CODE REVIEW

**Comment by Turbo87** [comment]
@stefanpenner it would be good if you could verify that 6f1e2d6 and 2edb8a1 are not breaking anything that I'm not aware of.

**Comment by Turbo87** [comment]
wow, even AppVeyor is fine with this :trollface:

**Comment by stefanpenner** [comment]
> wow, even AppVeyor is fine with this 

:tada:

**Comment by stefanpenner** [comment]
> @stefanpenner it would be good if you could verify that 6f1e2d6 and 2edb8a1 are not breaking anything that I'm not aware of.

both look good

**Comment by stefanpenner** [comment]
@homu r+

**Pull request merged**
