### PR TITLE
expand wildcard before sending to `npm i`

### PR DESCRIPTION
**Pull request by kellyselden**
I needed to do this for it to work with the wildcard.

@stefanpenner @rwjblue Does this make sense, or is there some way you guys have got it to work?

### CODE REVIEW

**Comment by stefanpenner** [comment]
> @stefanpenner @rwjblue Does this make sense, or is there some way you guys have got it to work?

strange, works for me. What version of sh are you using?

**Comment by rwjblue** [comment]
@stefanpenner - I also can not do the command listed, and this PR seems to fix.  I am using zsh@5.0.8 as my default shell, and bash@3.2.57 is what `sh --version` reports.

**Comment by kellyselden** [comment]
@stefanpenner I was doing it line by line using unix executables in Windows cmd.

**Comment by stefanpenner** [comment]
@rwjblue prepare release runs in bin/sh not zsh. Are you sure it does not work for you when running the script?

**Comment by stefanpenner** [comment]
```
± % zsh                                                                                                                                                                                                     
± % npm i -g ./rsvp-*.tgz
/usr/local/lib
└── rsvp@3.1.0
```

```
± % zsh --version                                                                                                                                                                                           !25144
zsh 5.0.5 (x86_64-apple-darwin14.0)
```

```
± % bash
bash-3.2$ npm i -g ./rsvp-*.tgz
/usr/local/lib
└── rsvp@3.1.0
```
```
bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin14)
Copyright (C) 2007 Free Software Foundation, Inc.
```

**Comment by stefanpenner** [comment]
what is the result for:

```
echo ./*.tgz
```

**Comment by kellyselden** [comment]
```
C:\Users\kselden\Downloads>echo ./*.tgz
./*.tgz
```
But I'm the outlier, it's not really expected to work for me.

**Comment by stefanpenner** [comment]
@kellyselden can you try in git-bash?

**Comment by kellyselden** [comment]
```
kselden@XXX  ~/Downloads
$ echo ./*.tgz
./ember-cli-2.2.0-beta.5.tgz
```

**Comment by rwjblue** [comment]
@stefanpenner - I am not certain. I know it doesn't work when running the commands directly, but I don't know if it errors when running the script.

**Comment by stefanpenner** [comment]
I'll have to believe your env is broken, this is just a primitive of shell expansion

**Comment by stefanpenner** [comment]
I believe the existing script is correct when run in a posix shell.  (git bash on Windows)

If someone can demonstrate or provide docs as to why @rwjblue is having issues we can revisit. @rwjblue I'll take a look on your machine when we are in Austin. This mystery perplexes me

**Comment by kellyselden** [comment]
I think all issues are addressed. This code should not be necessary.

**Pull request closed without merging**
