### PR TITLE
Test powershell for appveyor builds

### PR DESCRIPTION
**Pull request by raytiley**
If this doesn't screw anything else up it would allow us to test #3341 correctly.

### CODE REVIEW

**Comment by stefanpenner** [comment]
should we test both? or.. just recommend ps

**Comment by raytiley** [comment]
Should probably test both since both are included on a default system. I'll work on getting this going and fix the power shell tests. Seems like just a funky CI thing with paths.

**Comment by abuiles** [comment]
@raytiley  ping

**Comment by raytiley** [comment]
retrying this on appveyor just to see how it behaves.

**Comment by stefanpenner** [comment]
@raytiley should we rest both ps and cmd ? or..

**Comment by raytiley** [comment]
I'm not sure if it really matters. I would probably be good to test both because the environments differ in how they can format output (the ansi color codes comes to mind). But i'm hesitant to double our windows CI time until we can get the tests a bit faster.

**Pull request merged**
