### PR TITLE
consolidate package.json normalization

### PR DESCRIPTION
**Pull request by kellyselden**
I noticed when generating an in-repo addon, the terminating new line was getting removed from `package.json`. This bug was fixed in addon generation, so the code was consolidated so everyone gets the new line. Then I added tests.

### CODE REVIEW

**Comment by nathanhammond** [comment]
> "Ugh, this is annoying." /@kellyselden goes and fixes it.

Awesome. My only comment at first pass is that this isn't limited to `package.json` ... it's really any JSON file. So let's name it something different?

**Comment by kellyselden** [comment]
@nathanhammond How about `stringifyAndNormalize`?

**Comment by nathanhammond** [comment]
`stringifyAndNormalize`: 👍

**Comment by kellyselden** [comment]
@nathanhammond: updated.

**Comment by nathanhammond** [comment]
@homu r+

**Pull request merged**
