### PR TITLE
Update to _findHost to use do/while.

### PR DESCRIPTION
**Pull request by nathanhammond**
I'm pretty sure that this is identical to the current implementation, but y'all make sure I'm not crazy.

/cc @Turbo87 @xcambar @rwjblue

### CODE REVIEW

**Comment by nathanhammond** [comment]
Related to #6042 and #6043.

**Comment by rwjblue** [comment]
LGTM

**Comment by nathanhammond** [comment]
@homu r+

**Comment by stefanpenner** [comment]
👍

**Pull request merged**
