### PR TITLE
ESLint: Use recommended rules preset

### PR DESCRIPTION
**Pull request by Turbo87**
This PR adds the `eslint:recommended` rules preset to `.eslintrc.js` and fixes the few issues that came up.

- `no-console` is disabled because we obviously do need to use the console in a CLI.
- `comma-dangle` is disabled because the code in the project is inconsistent about this and I wasn't sure what the desired style is and whether we want to enforce it.

### CODE REVIEW

**Comment by Turbo87** [comment]
@rwjblue @stefanpenner @kellyselden any thoughts on this?

the "recommended" rules are the ones with a checkmark at http://eslint.org/docs/rules/

**Comment by rwjblue** [comment]
@homu r+

**Comment by Turbo87** [comment]
hmm, I don't think the test failure is related to my changes. the original Travis PR test seems to have passed.

**Comment by rwjblue** [comment]
@homu retry

**Comment by Turbo87** [comment]
oh well... looks like we have a few more flaky tests to fix...

**Pull request merged**
