### PR TITLE
Update `ember-welcome-page` usage to angle brackets

### PR DESCRIPTION
**Pull request by locks**

### CODE REVIEW

**Comment by rwjblue** [comment]
Need to update the fixtures here:

https://github.com/ember-cli/ember-cli/blob/94a678276a96794e3196c8e71c7fc2a76e8dd617/tests/fixtures/addon/yarn/tests/dummy/app/templates/application.hbs#L2

https://github.com/ember-cli/ember-cli/blob/94a678276a96794e3196c8e71c7fc2a76e8dd617/tests/fixtures/app/yarn/app/templates/application.hbs#L2

**Comment by stefanpenner** [comment]
fancy

**Comment by ppcano** [comment]
screen shot 2019-01-27 at 6 50 56 am

The `ember-welcome-page` project should also change its copy:

remove the `<WelcomePage />` component from your `application.hbs`

Note: MU apps defines the template at `ui/routes/application/template.hbs`.

**Comment by rwjblue** [comment]
Great point @ppcano! Mind tweaking the addon to change the copy? With a stretch goal of possibly keeping `{{welcome-page}}` displayed for Ember < 3.4 and detecting MU to display the correct location...

**Comment by rwjblue** [comment]
ping @locks - mind updating the fixtures I linked to?

**Comment by locks** [comment]
On it!

**Comment by locks** [comment]
```
not ok 1329 Acceptance: smoke-test ember test wasm
      Running: node_modules/ember-cli/bin/ember build in: /home/travis/build/ember-cli/ember-cli/tmp/some_cool_app_clone-lah7ZT3o.tmp
```

🤔

**Comment by rwjblue** [comment]
https://github.com/ember-cli/ember-welcome-page/pull/124 updates the messaging to use angle bracket invocation as well, it is released in v4.0.0.

**Pull request merged**
