### PR TITLE
Upgrade istanbul to nyc

### PR DESCRIPTION
**Pull request by dcyriller**
The CI job generating code coverage is often failing. This PR is an attempt at fixing this.

It upgrades istanbul to its 2.0 API. `istanbul` npm package is deprecated in favor of`nyc`.

### CODE REVIEW

**Comment by rwjblue** [comment]
>  I'll trim the PR to keep the istanbul upgrade.

Sounds good. I'm also trying to figure out what the heck is going on with this job, though I don't thing its directly related to istanbul...

**Comment by rwjblue** [comment]
Would you mind rebasing against master (after https://github.com/ember-cli/ember-cli/pull/7972)?

**Comment by rwjblue** [comment]
meh, lets just do it 😸

**Comment by dcyriller** [comment]
Sorry, I wasn't behind my computer!

Have you noticed that we added a third stage to the CI build? Do you want me to revert this? https://github.com/ember-cli/ember-cli/pull/7968/files#diff-354f30a63fb0907d4ad57269548329e3R27

**Comment by dcyriller** [comment]
I opened a PR to make the adjustment. Feel free to close it if not relevant.

**Pull request merged**
