### PR TITLE
[WIP] Figure out AppVeyor issue

### LINKED ISSUE #5781: AppVeyor builds are failing
This AppVeyor builds are currently failing, most likely due to a transitive dependency update that is causing trouble.

The failing test is "Acceptance: brocfile-smoke-test addon trees are not jshinted" and fails with:

```js
{
  "code": 1
  "errors": [
    "Not all tests passed.\r\n"
    "Error: Not all tests passed.\n    at EventEmitter.App.getExitCode (C:\\projects\\ember-cli\\node_modules\\testem\\lib\\app.js:382:14)\n    at EventEmitter.<anonymous> (C:\\projects\\ember-cli\\node_modules\\testem\\lib\\app.js:195:39)\n    at C:\\projects\\ember-cli\\node_modules\\async\\lib\\async.js:726:13\n    at C:\\projects\\ember-cli\\node_modules\\async\\lib\\async.js:52:16\n    at C:\\projects\\ember-cli\\node_modules\\async\\lib\\async.js:269:32\n    at C:\\projects\\ember-cli\\node_modules\\async\\lib\\async.js:44:16\n    at C:\\projects\\ember-cli\\node_modules\\async\\lib\\async.js:723:17\n    at C:\\projects\\ember-cli\\node_modules\\async\\lib\\async.js:167:37\n    at EventEmitter.App.removeSignalListeners (C:\\projects\\ember-cli\\node_modules\\testem\\lib\\app.js:411:5)\n    at C:\\projects\\ember-cli\\node_modules\\async\\lib\\async.js:718:13\n    at iterate (C:\\projects\\ember-cli\\node_modules\\async\\lib\\async.js:262:13)\n    at C:\\projects\\ember-cli\\node_modules\\async\\lib\\async.js:274:29\n    at C:\\projects\\ember-cli\\node_modules\\async\\lib\\async.js:44:16\n    at Server.<anonymous> (C:\\projects\\ember-cli\\node_modules\\async\\lib\\async.js:723:17)\n    at Server.<anonymous> (C:\\projects\\ember-cli\\node_modules\\async\\lib\\async.js:167:37)\n    at Server.g (events.js:260:16)\r\n"
  ]
  "output": [
    "Building\r\n"
    "Built project successfully. Stored in \"C:\\projects\\ember-cli\\tmp\\some-cool-app\\tmp\\class-tests_dist-C0lXF3tp.tmp\".\r\n"
    "ok 1 PhantomJS 2.1 - JSHint - app.js: should pass jshint\nok 2 PhantomJS 2.1 - JSHint - helpers/destroy-app.js: should pass jshint\nok 3 PhantomJS 2.1 - JSHint - helpers/module-for-acceptance.js: should pass jshint\nok 4 PhantomJS 2.1 - JSHint - helpers/resolver.js: should pass jshint\nok 5 PhantomJS 2.1 - JSHint - helpers/start-app.js: should pass jshint\nok 6 PhantomJS 2.1 - JSHint - resolver.js: should pass jshint\nok 7 PhantomJS 2.1 - JSHint - router.js: should pass jshint\nok 8 PhantomJS 2.1 - JSHint - test-helper.js: should pass jshint\nnot ok 9 PhantomJS 2.1 - TestLoader Failures: some-cool-app/tests/unit/routes/horrible-route-test: could not be loaded\n    ---\n        actual: >\n            null\n        stack: >\n            http://localhost:7357/assets/tests.js:138:28\n            exports@http://localhost:7357/assets/vendor.js:92:39\n            build@http://localhost:7357/assets/vendor.js:142:17\n            findModule@http://localhost:7357/assets/vendor.js:190:14\n            requireModule@http://localhost:7357/assets/vendor.js:177:22\n            require@http://localhost:7357/assets/test-loader.js:67:16\n            loadModules@http://localhost:7357/assets/test-loader.js:58:25\n            load@http://localhost:7357/assets/test-loader.js:89:35\n            http://localhost:7357/assets/test-support.js:6477:20\n        message: >\n            Died on test #1 moduleLoadFailure@http://localhost:7357/assets/test-support.js:6468:15\n            require@http://localhost:7357/assets/test-loader.js:69:31\n            loadModules@http://localhost:7357/assets/test-loader.js:58:25\n            load@http://localhost:7357/assets/test-loader.js:89:35\n            http://localhost:7357/assets/test-support.js:6477:20: Can't find variable: Blah\n        Log: |\n    ...\n"
    "\n1..9\n# tests 9\n# pass  8\n# skip  0\n# fail  1\n"
  ]
  "signal": [null]
}
```

The relevant piece here is `Can't find variable: Blah`, which means that the `horrible-route-test.js` file was actually attempted to run even though the `ember test` command is called with `--filter=jshint`.

A diff of the installed NPM packages is available at https://gist.github.com/Turbo87/f3d697e64fe40604d5c383973ba65e6e/revisions.

/cc @nathanhammond

### PR DESCRIPTION
**Pull request by Turbo87**
This is a temporary PR to try to figure out the broken AppVeyor build.

Hopefully resolves #5781

### CODE REVIEW

**Comment by Turbo87** [comment]
NPM packages diff: https://gist.github.com/Turbo87/f3d697e64fe40604d5c383973ba65e6e/revisions

**Comment by nathanhammond** [comment]
At this point I think we just need to get a repro on Windows. Unfortunately my VM stalls hard on these exact tests and won't hit a `debugger` making this exceptionally painful.

**Comment by nathanhammond** [comment]
Going to land this for now. Will open issue to unpin it.

@homu r+

**Comment by Turbo87** [comment]
@nathanhammond should we maybe pin it in `package.json` instead so that user projects also get a working version?

**Pull request merged**
