### PR TITLE
Update to lodash 4

### PR DESCRIPTION
**Pull request by jcope2013**
Relevant change include 

- Removed category names from module paths 
- contains alias removed in favor of includes
- pluck removed in favor of map
- where removed in favor of filter
- omit no longer takes function argument, use omitBy/isNull
- uniq no longer takes function argument, use uniqBy

https://github.com/lodash/lodash/wiki/Changelog

### CODE REVIEW

**Comment by stefanpenner** [comment]
Awesome thanks!

@homu r+

**Comment by jcope2013** [comment]
tests should pass now

**Comment by kellyselden** [comment]
@homu retry

**Comment by stefanpenner** [comment]
@homu retry

**Comment by stefanpenner** [comment]
@home r+

**Comment by kellyselden** [comment]
@stefanpenner homu doesn't like us anymore apparently

**Comment by stefanpenner** [comment]
@homu +r (i did typo above, lets try again)

**Comment by trabus** [comment]
@jcope2013 I think you may have missed this line:
https://github.com/ember-cli/ember-cli/blob/master/lib/models/file-info.js#L18

**Comment by trabus** [comment]
Looks like AppVeyor is still having issues with the blueprint tests, which are most likely related to the `file-info` use of `lodash/template`. Uncertain if there are any changes that would affect the template rendering on Windows, but that seems like a good place to start looking.

**Comment by jcope2013** [comment]
@trabus not sure they are related to this PR as they are failing in other PR's also https://github.com/ember-cli/ember-cli/pull/5374 and a whole bunch of other ones

**Comment by trabus** [comment]
@jcope2013 @kellyselden Looks like they started with this PR: 
https://github.com/ember-cli/ember-cli/pull/5345

It seems the change of the eol character changed the result to something other than what the tests were expecting.

**Comment by stefanpenner** [comment]
they are failing, (to do timeouts, yes we must address that) but as @trabus pointed out there are also template specific issues in this test run.

**Pull request merged**
