### PR TITLE
Update valid-platform-version.js

### PR DESCRIPTION
**Pull request by wldcordeiro**
Add io.js 3.0.0+ to the list of valid platform versions.

### CODE REVIEW

**Comment by stefanpenner** [comment]
needs rebase

**Comment by wldcordeiro** [comment]
Not sure how I go about that, do I fetch upstream, merge then rebase? When I try that I'm not seeing the merge commit or any others except for the most recent on master 8b69135

**Comment by stefanpenner** [comment]
steps:

1. `git rebase upstream/master`
2. resolve conflicts in `lib/models/update-checker.js` via `git rebase --skip` since we want the code already on master for this conflict.
3. newly rebased PR -> https://github.com/ember-cli/ember-cli/pull/4599 (closing this one in-favor of that one.)

**Comment by wldcordeiro** [comment]
Ah okay I had tried

1. `git fetch upstream`
2. `git rebase -i`

Good to know.

**Pull request closed without merging**
