### PR TITLE
Adding change logging for backwards compatibility

### PR DESCRIPTION
**Pull request by thoov**
Adding logging to support broccoli-sane-watchers' logic

### CODE REVIEW

**Comment by thoov** [comment]
cc: @stefanpenner @oligriffiths

**Comment by stefanpenner** [comment]
Looks like a relevant failure:

```
not ok 968 Server Watcher watcher:change logs that the file was changed
  expected 'file foo.txt undefined\nFile changed: "foo.txt"\n' to equal 'File changed: "foo.txt"\n'
  AssertionError: expected 'file foo.txt undefined\nFile changed: "foo.txt"\n' to equal 'File changed: "foo.txt"\n'
      at Context.<anonymous> (tests/unit/models/server-watcher-test.js:33:28)
```

**Comment by thoov** [comment]
FYI: this logging isn't exactly one-to-one with brococli-sane-watcher. This PR will only log once per build (even if multiple things change as the change event is not fired if a rebuild is already happening: https://github.com/broccolijs/broccoli/blob/master/lib/watcher.js#L69)

Example if you delete 2 files at the same time the current watcher would log:

```
file deleted controllers/bar.js
file added controllers/foo.js
```

And the new watcher would just log:

```
file deleted controllers/bar.js
```

If we want to keep exact pairity then we need to move this logic to here: https://github.com/broccolijs/broccoli/blob/master/lib/watcher_adapter.js#L17

cc: @stefanpenner @oligriffiths

**Comment by oligriffiths** [comment]
Once we do the console UI work we can revisit this in Broccoli

**Comment by rwjblue** [comment]
FWIW, I do think we want to do this in Broccoli. Knowing only one of the changed files would essentially mean that things like the hot reloader are only able to reload the first changed file (not all).

**Pull request merged**
