### PR TITLE
attempt AppVeyor node 12 fix

### PR DESCRIPTION
**Pull request by kellyselden**
https://www.appveyor.com/docs/lang/nodejs-iojs/#installing-any-version-of-nodejs-or-iojs

### CODE REVIEW

**Comment by kellyselden** [comment]
Anyone know why AppVeyor isn't running?

**Comment by kellyselden** [comment]
It took its time.

**Comment by rwjblue** [comment]
@kellyselden - Lets land this one (and close #8649 since we'll merge lts-3-8 into release), sound good?

**Comment by kellyselden** [comment]
Sounds good.

**Comment by rwjblue** [comment]
OK, merged into all the branches now (lts-3-8, release, beta, and master).

**Pull request merged**
