### PR TITLE
Package upgrades

### PR DESCRIPTION
**Pull request by sethbrasile**
ember-cli-release 0.2.4 through 0.2.7 breaks ember-cli tests

https://travis-ci.org/ember-cli/ember-cli/jobs/83942510

### CODE REVIEW

**Comment by elwayman02** [comment]
@stefanpenner @rwjblue can we get @homu to try this out, now that travis tests are passing?

**Comment by slindberg** [comment]
Just starting to look into this, but I'm unsure why you think that ember-cli-release is breaking appveyor, since it's still failing after downgrading to v0.2.4?

**Comment by slindberg** [comment]
So, ember-cli-release does some mild hackery with the `Command` class to initialize the `availableOptions` array, and something goes wrong when it [gets required](https://github.com/lytics/ember-cli-release/blob/v0.2.7/lib/commands/release.js#L12). The test suite is doing some fancy things to mimic node modules, one of them being [symlinking the `ember-cli` package to the project root](https://github.com/ember-cli/ember-cli/blob/master/tests/helpers/acceptance.js#L166-L174). Near as I can tell, this is what's causing it to blow up, but I don't have a solution at the moment.

Perhaps the easiest way would be to avoid using the `Command` class altogether by adding the ability for commands to specify `availableOptions` as a function (ember-cli feature). @rwjblue mentioned that the the `release` command could just short circuit if the class isn't found, but I'm not a huge fan of that solution. I'll look into better options this weekend.

**Comment by rwjblue** [comment]
making availableOptions a function seems like a good option

**Comment by stefanpenner** [comment]
kicking appveyor

**Comment by slindberg** [comment]
@rwjblue I opened a PR (#4966) for supporting `availableOptions` as a function. I think this is the best long-term solution, but I realized it doesn't really help for this situation since I can't target an ember-cli release with the fix, even if the above PR is merged. In the meantime I've removed the command model require in ember-cli-release with a questionable hack (lytics/ember-cli-release#32), which I've verified fixes this issue. Would love to get your input on those PRs.

**Comment by rwjblue** [comment]
@slindberg - Thank you for digging into this.  It is definitely annoying that everything actually works in reality, but the test infrastructure here in ember-cli causes an issue with addons extending the command object.  I left a few comments on the various PR's you linked.

**Comment by slindberg** [comment]
Released version [0.2.8](https://github.com/lytics/ember-cli-release/tree/v0.2.8) of ember-cli-release, which should fix this issue.

**Comment by sethbrasile** [comment]
thanks @slindberg, updated. We'll see if it passes in a couple hours :D

**Comment by slindberg** [comment]
Hard to believe that this diff reduces test coverage... but either way, looks like `ember-cli-release` isn't causing test failures anymore :tada:

**Comment by kellyselden** [comment]
Can we get a squash please?

**Comment by elwayman02** [comment]
@sethbrasile @slindberg @kellyselden I updated & squashed the original PR #4891

**Comment by sethbrasile** [comment]
:+1:

**Pull request closed without merging**
