### PR TITLE
suggest testing addons against LTS

### PR DESCRIPTION
**Pull request by kellyselden**
probably a good idea to default testing addons against LTS versions.

### CODE REVIEW

**Comment by rwjblue** [comment]
Seems good to me. When 2.8 becomes an LTS, we can drop 1.13 and keep 2.4 and 2.8.

**Comment by kellyselden** [comment]
@rwjblue Or keep 1.x until a 3.x comes out? or is 2.x LTS an indefinite thing?

**Comment by nathanhammond** [comment]
This is a reasonable change for now; 2.8 doesn't go LTS for another release cycle at which point we can add it in and drop 1.13. Also, it's covered by `default` and `release` for newly-init'd addons.

@kellyselden Can you target this at the `beta` branch? Otherwise this won't land in time for the above to be true.

**Comment by kellyselden** [comment]
@nathanhammond retargeted.

**Comment by kellyselden** [comment]
@homu r+

**Pull request closed without merging**
