### PR TITLE
Pin "testem" to v1.8.1

### PR DESCRIPTION
**Pull request by Turbo87**
let's see if this fixes the builds...

/cc @rwjblue

### CODE REVIEW

**Comment by Turbo87** [comment]
Looks like this is indeed fixing things... Maybe we should keep testem pinned in the future.

**Comment by rwjblue** [comment]
Yeah, but that is also unfortunate. We have been able to take advantage of the loose constraint much more than it has bitten us.

Perhaps we could test with ember-cli's CI before releasing `testem`?  I have mixed feelings about that...

**Comment by johanneswuerbach** [comment]
Strange, after noticing the test failure I marked the package as new version deprecated, but it seems to still install it.

I'll go back to releasing a rc next time again.

**Comment by johanneswuerbach** [comment]
Published testem v1.9.1, which is v1.8.1 re-published until all issue have been resolved, sorry about that 😢 .

**Comment by rwjblue** [comment]
@johanneswuerbach - Thank you for jumping on it!

**Comment by Turbo87** [comment]
Guess we can close this now. Thanks @johanneswuerbach :)

**Pull request closed without merging**
