### PR TITLE
Fix `ember new --yarn` not using yarn

### PR DESCRIPTION
**Pull request by Turbo87**
Resolves https://github.com/ember-cli/ember-cli/issues/7511

/cc @PieterJanVdb @gossi @lennyburdette

### CODE REVIEW

**Comment by rwjblue** [comment]
Can you add a smoke test that confirms yarn.lock is created? One possible place for that would be the fixture tests, but you could do it elsewhere also...

**Comment by rwjblue** [comment]
The simplest thing would be to add another assertion to these tests https://github.com/ember-cli/ember-cli/blob/master/tests/acceptance/new-test.js#L468-L490 that just confirms yarn.lock is _present_...

**Comment by Turbo87** [comment]
@rwjblue the tests you linked run using `--skip-npm`, but that means that `yarn` will actually never run and thus not create a `yarn.lock` file either 🤔

**Comment by rwjblue** [comment]
Yeah, I see that now.  I guess I assumed that even if we didn't run `yarn install` we would emit a `yarn.lock`, but clearly that is not true.

**Comment by Turbo87** [comment]
> Assuming you have smoke tested this locally (npm link + ember new foo --yarn) and confirmed it is working "for real", I'm 👍 .

yep, seemed to work correctly for all cases now (`ember new --yarn`, `ember install --no-yarn`, ...)

**Pull request merged**
