### PR TITLE
improve boot by 300ms -> 400ms

### PR DESCRIPTION
**Pull request by stefanpenner**

### CODE REVIEW

**Comment by jakecraige** [comment]
Would it be possible to add a test for boot time perf? That would be a great way to watch for regressions

**Comment by stefanpenner** [comment]
> Would it be possible to add a test for boot time perf? That would be a great way to watch for regressions

CI server is pretty crappy re: perf. But maybe a test we can run only locally?

**Comment by jakecraige** [comment]
Yeah I guess the system perf affects the test :/ But yeah, some way to easily check it / keep an eye on it in a consistent format would be nice

**Comment by stefanpenner** [comment]
apparently i can't program, will investigate these failures after work... "(unless someone has time to look earlier)"

**Comment by stefanpenner** [comment]
> Yeah I guess the system perf affects the test :/ But yeah, some way to easily check it / keep an eye on it in a consistent format would be nice

i gave this some thought, how about a test that only run when `CI=false` ?

**Comment by jakecraige** [comment]
Sounds fine to me :+1:

**Pull request merged**
