### PR TITLE
use async/await in ember-try config

### PR DESCRIPTION
**Pull request by kellyselden**

### CODE REVIEW

**Comment by kellyselden** [comment]
Good idea.

**Comment by kellyselden** [comment]
@rwjblue I believe you lose the concurrency of Promise.all that way. I will make the change, but just wanted to point it out.

**Comment by kellyselden** [comment]
@rwjblue changes and rebased.

**Comment by rwjblue** [comment]
Ya, true (RE: the concurrency), but I think the clarity is much better and _probably_ still worth it...

**Comment by pgengler** [comment]
FWIW, I tried this out on a project and I get an eslint parse failure on `async function`:
```
5:24  error  Parsing error: Unexpected token function
```

where line 5 is;
```module.exports = async function() {```

(Node v10.15.3 and eslint v5.16.0)

**Comment by pgengler** [comment]
Nevermind, figured it out ... I didn't update the top-level .eslintrc.js to get rid of the `ecmaVersion` override (#8659). Sorry!

**Comment by kellyselden** [comment]
Thanks @rwjblue!

**Pull request merged**
