### PR TITLE
Allow addon.include to change mutate built-in app.imports

### PR DESCRIPTION
**Pull request by stefanpenner**
- [ ] see if this works
- [ ] anyone apposed?
- [ ] tests

### CODE REVIEW

**Comment by stefanpenner** [comment]
cc @mbutki

**Comment by nathanhammond** [comment]
This probably unblocks the work done here: https://github.com/ef4/ember-browserify/pull/100

I believe I only found one addon that would be impacted by this. Possibly @zackthehuman's i18n work? Regardless, only likely to be encountered by skilled maintainers who can code around it.

**Comment by stefanpenner** [comment]
@nathanhammond https://github.com/ember-cli/ember-cli/pull/7059

**Comment by stefanpenner** [comment]
Looks like exploring this will require additional deep dive.

**Comment by rwjblue** [comment]
I believe that the logic in `populateLegacyFiles` needs to be modified, so that the `app.import`'s that are done currently are inverted (and `prepend: true` option is added).  Without changing that, this change is likely a breaking change (as evidenced by the failing tests).

@stefanpenner is working on making the ordering (specifically for ember-cli-shims) less important in https://github.com/ember-cli/ember-cli-shims/pull/118, but updating ember-cli versions generally doesn't require updating other related blueprint packages so we should take care to ensure that this PR passes using the current version of ember-cli-shims (1.2.0-beta.2)...

**Comment by Turbo87** [comment]
closing due to inactivity and conflicts

**Pull request closed without merging**
