### PR TITLE
Use `ember` test helper in Smoke Tests

### PR DESCRIPTION
**Pull request by seanpdoyle**
The `ember` command is a faster way to run ember-cli in tests.

https://github.com/ember-cli/ember-cli/pull/4954#discussion_r42235864

### CODE REVIEW

**Comment by seanpdoyle** [comment]
@kellyselden do we have any idea why this would break the test sutie?

**Comment by kellyselden** [comment]
https://github.com/ember-cli/ember-cli/blob/master/tests/acceptance/smoke-test-slow.js#L149

These are throughout the code. The `ember` helper has an obscure bug in it. Unfortunately, this means we can't use it everywhere yet.

**Comment by stefanpenner** [comment]
seems to have gone stale. I would like to recommend closing PR if they are no longer being pursued.

**Comment by seanpdoyle** [comment]
@stefanpenner looking at the diff, is there any reason this shouldn't pass?

**Comment by stefanpenner** [comment]
@homu r+

**Comment by seanpdoyle** [comment]
@stefanpenner do I just keep re-running until we're green? What do you think is the root of the problem here?

**Comment by stefanpenner** [comment]
unsure, let me try locally

**Comment by stefanpenner** [comment]
found whats causing grief: https://github.com/joliss/node-quick-temp/issues/8

**Comment by stefanpenner** [comment]
https://github.com/ember-cli/ember-cli/pull/5140

**Pull request closed without merging**
