### PR TITLE
[ENHANCEMENT] Add `directory` option to `addon` command

### PR DESCRIPTION
**Pull request by Serabe**
The `addon` command is built upon `new` but there was no option for `--directory`. This PR just adds that option.

I found no place to add a test for the options.

### CODE REVIEW

**Comment by Serabe** [comment]
Tests ready.

**Comment by Serabe** [comment]
Tests added.

**Comment by kellyselden** [comment]
@homu r+

**Comment by kellyselden** [comment]
Thank you.

**Pull request merged**
