### PR TITLE
Fix StylePlugin to readTree(inputTree) and getExt to take inputTreeRoot.

### PR DESCRIPTION
**Pull request by krisselden**
This is a first step in making my-addon/addon/styles and my-addon/app/styles work with style plugins, next step is to actually correctly setup options given to preprocessCSS.

### CODE REVIEW

**Comment by krisselden** [comment]
Not sure what's up with the tests, running npm test locally passed for me.

**Comment by chadhietala** [comment]
@krisselden can you run `npm run test-all` locally? `npm test` doesn't run the "slow" acceptance tests and it looks like the failures are in there.  This test has the failures is this test https://github.com/ember-cli/ember-cli/blob/master/tests/acceptance/brocfile-smoke-test-slow.js.

**Comment by stefanpenner** [comment]
needs rebase

**Comment by krisselden** [comment]
@stefanpenner I've rebased, still haven't had a chance to investigate the acceptance test, I've tried this change in a project, and it worked well.  @chadhietala confirm, I'm able to reproduce the failing test locally now, wasn't at first aware of the slow running tests.

**Comment by krisselden** [comment]
@pzuraq  I'd like to coordinate with you on #3063 to get this stuff incrementally in a better place.

**Comment by sandstrom** [comment]
Thanks @krisselden and @pzuraq! :boat:

**Comment by rwjblue** [comment]
Replaced by https://github.com/ember-cli/ember-cli/pull/3069.

**Comment by krisselden** [comment]
thanks @pzuraq for getting the tests green for me.

**Comment by pzuraq** [comment]
No prob! And thanks again @krisselden for the better strategy, it was much better than the kludged solution I came up with.

**Pull request closed without merging**
