### PR TITLE
tests: Remove unused variables

### PR DESCRIPTION
**Pull request by Turbo87**
... and enable `no-unused-vars` ESLint rule inside the `tests` folder to prevent this from happening again.

### CODE REVIEW

**Comment by rwjblue** [comment]
```
not ok 8 eslint should have no errors in tests/unit
  Error: Code did not pass lint rules
  tests/unit/broccoli/ember-app-test.js
    663:17  error  'app' is assigned a value but never used  no-unused-vars
  
  tests/unit/models/builder-test.js
    201:7   error  'instrumentationArg' is not defined  no-undef
    286:11  error  'instrumentationArg' is not defined  no-undef
  
  ✖ 3 problems (3 errors, 0 warnings)
  
      at Context.<anonymous> (node_modules/mocha-eslint/index.js:36:15)
```

**Comment by stefanpenner** [comment]
@Turbo87 yarn.lock needs resolve, then :shipit:

**Comment by Turbo87** [comment]
@rwjblue Y U BREAK ME??!

**Comment by rwjblue** [comment]
😽

**Comment by Turbo87** [comment]
@homu r+

**Pull request merged**
