### PR TITLE
[DOC]Fix --test-port description

### PR DESCRIPTION
**Pull request by akashdsouza**
As per https://github.com/ember-cli/ember-cli/issues/7289

### CODE REVIEW

**Comment by rwjblue** [comment]
Changes look good, but there are some failing tests (which have assertions around the help output) that I think you will need to update before we can merge.

**Comment by akashdsouza** [comment]
Fixed the failing tests

**Comment by akashdsouza** [comment]
I'm not sure why it has failed on AppVeyor though

**Comment by kellyselden** [comment]
Rerunning to see if it fixes itself.

**Comment by rwjblue** [comment]
Thank you!!

**Pull request merged**
