### PR TITLE
added `app` directory for linting

### LINKED ISSUE #5839: JSHint doesn't work for addon's app folder.
The app folder isn't getting jshinted for addons. 
## Steps to reproduce:
1. Create a new addons `ember addon my-addon`
2. Create a component `ember generate component my-component`
3. Add a jshint error in `app/components/my-component.js`, for example add an unused var `var x;`
4. Run ember test. 
## Expected

My tests will fail with a jshint error
## Actual

No JSHint tests are run for the app directory. 

Output from ember version --verbose:

```
ember-cli: 2.5.0
node: 4.2.4
os: darwin x64
```

Related to https://github.com/ember-cli/ember-cli/issues/4371

### PR DESCRIPTION
**Pull request by bekzod**
fixes #5839

### CODE REVIEW

**Comment by bekzod** [comment]
probably needs restart

**Comment by kellyselden** [comment]
restarted

**Comment by rwjblue** [comment]
Hmm. I would have preferred to land https://github.com/ember-cli/ember-cli/pull/7037 instead of this 😢

**Comment by Turbo87** [comment]
@rwjblue sorry, wasn't aware of that one... long running branches/PRs are bad! 😞

**Pull request merged**
